//! `HandlerDispatch` — the indirection the `#[component]` and `#[handlers]`
//! macros use to coordinate. `#[component]` emits a `ComponentState::invoke`
//! that delegates here; `#[handlers]` emits the actual match-by-name body.

use js_sys::Array;
use wasm_bindgen::JsValue;

pub trait HandlerDispatch {
    fn invoke_handler(&mut self, key: &str, args: &Array) -> JsValue;

    /// Called once after the component is mounted and its subtree is
    /// fully bound. The `#[handlers]` macro generates an override that
    /// delegates to the user's `on_mount` method when one exists.
    fn mount(&mut self) {}

    /// Called once just before the component unmounts, while the
    /// state is still mutable and the scope is still in the registry.
    /// Override generated by `#[handlers]` when the user writes
    /// `on_unmount`.
    fn unmount(&mut self) {}

    /// True iff the component author actually wrote an `on_mount`
    /// method. The walker uses this to decide whether to fire a
    /// `trigger_scope` sweep after [`mount`] — components with no
    /// hook should not pay for a sweep.
    fn has_on_mount(&self) -> bool {
        false
    }

    /// Symmetric with [`has_on_mount`] for `on_unmount`. Currently
    /// informational — the walker doesn't sweep on unmount — but kept
    /// for parity and so future devtools can show per-component
    /// lifecycle coverage.
    fn has_on_unmount(&self) -> bool {
        false
    }
}
