//! Component scopes and the JS-`Proxy` bridge they expose to directives.
//!
//! A scope owns a `ComponentState` (macro-generated), a stable `ScopeId`, and
//! a `js_sys::Proxy` whose `get`/`set` traps plug into [`crate::reactive`] so
//! any directive that reads a field through the proxy gets auto-subscribed.

use std::cell::RefCell;
use std::collections::HashMap;
use std::rc::Rc;

use js_sys::{Array, Function, Object, Proxy, Reflect};
use wasm_bindgen::closure::Closure;
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsValue;
use web_sys::Element;

use crate::magics;
use crate::reactive::{next_scope_id, track, trigger, trigger_scope, ScopeId};

/// Implemented by components (generated by `#[component]` + `#[handlers]`).
pub trait ComponentState: 'static {
    /// Read a declared field as a JsValue (for proxy `get`).
    fn get(&self, key: &str) -> JsValue;

    /// Write a declared field from a JsValue (for proxy `set`).
    fn set(&mut self, key: &str, value: JsValue);

    /// All data keys this component exposes. Used for sweep-triggers after
    /// a handler invocation.
    fn keys(&self) -> &'static [&'static str];

    /// Invoke a named method on `&mut self` with JS-land arguments.
    /// Returns a JsValue (or `JsValue::UNDEFINED` for void methods).
    fn invoke(&mut self, key: &str, args: &Array) -> JsValue;
}

/// A live component instance bound to a DOM element.
#[derive(Clone)]
pub struct Scope {
    pub id: ScopeId,
    pub state: Rc<RefCell<dyn ComponentState>>,
}

thread_local! {
    /// Registry of live scopes keyed by id. Directives look up the scope
    /// here to invoke handlers when an event fires.
    static SCOPES: RefCell<HashMap<ScopeId, Scope>> = RefCell::new(HashMap::new());

    /// The element the current directive is running against. Set by the
    /// walker immediately around each directive call so `$el` works without
    /// threading the element through every call site.
    static CURRENT_EL: RefCell<Option<Element>> = const { RefCell::new(None) };
}

impl Scope {
    pub fn new(state: Rc<RefCell<dyn ComponentState>>) -> Self {
        let id = next_scope_id();
        let scope = Scope { id, state };
        SCOPES.with(|s| s.borrow_mut().insert(id, scope.clone()));
        scope
    }

    /// Look up a live scope by id.
    pub fn find(id: ScopeId) -> Option<Scope> {
        SCOPES.with(|s| s.borrow().get(&id).cloned())
    }

    /// Remove a scope from the registry. Called when its element is unmounted.
    pub fn remove(id: ScopeId) {
        SCOPES.with(|s| s.borrow_mut().remove(&id));
    }

    /// Build a `js_sys::Proxy` whose `get` trap records dependencies and
    /// whose `set` trap triggers them. The proxy is what every directive
    /// reads through.
    pub fn into_proxy(&self) -> JsValue {
        let target = Object::new();
        let handler = Object::new();
        let scope_id = self.id;
        let state_for_get = self.state.clone();
        let state_for_set = self.state.clone();

        let get_closure = Closure::wrap(Box::new(
            move |_target: JsValue, key: JsValue, _receiver: JsValue| -> JsValue {
                let Some(key_str) = key.as_string() else {
                    return JsValue::UNDEFINED;
                };
                // Magics take priority over user fields.
                if key_str.starts_with('$') {
                    return magics::resolve(&key_str, scope_id);
                }
                track(scope_id, &key_str);
                state_for_get.borrow().get(&key_str)
            },
        ) as Box<dyn Fn(JsValue, JsValue, JsValue) -> JsValue>);

        let set_closure = Closure::wrap(Box::new(
            move |_target: JsValue, key: JsValue, value: JsValue, _receiver: JsValue| -> bool {
                let Some(key_str) = key.as_string() else { return false };
                state_for_set.borrow_mut().set(&key_str, value);
                trigger(scope_id, &key_str);
                true
            },
        )
            as Box<dyn Fn(JsValue, JsValue, JsValue, JsValue) -> bool>);

        Reflect::set(&handler, &"get".into(), get_closure.as_ref().unchecked_ref())
            .expect("set get trap");
        Reflect::set(&handler, &"set".into(), set_closure.as_ref().unchecked_ref())
            .expect("set set trap");

        // Closures outlive this call; the proxy holds them via the JS handler
        // object. `forget` leaks them intentionally — they live as long as
        // the scope itself, and scopes live for the lifetime of their element.
        get_closure.forget();
        set_closure.forget();

        Proxy::new(&target, &handler).into()
    }

    /// Invoke a handler by name. Mutates Rust state directly, then sweep-
    /// triggers every key on this scope so effects re-evaluate.
    pub fn invoke(&self, key: &str, args: &Array) -> JsValue {
        let out = self.state.borrow_mut().invoke(key, args);
        trigger_scope(self.id);
        out
    }
}

/// Set the current element for the duration of a directive call. The caller
/// is responsible for clearing it on exit.
pub fn with_current_el<R>(el: &Element, f: impl FnOnce() -> R) -> R {
    let prev = CURRENT_EL.with(|c| c.replace(Some(el.clone())));
    let out = f();
    CURRENT_EL.with(|c| *c.borrow_mut() = prev);
    out
}

/// The element the current directive is running against, if any.
pub fn current_el() -> Option<Element> {
    CURRENT_EL.with(|c| c.borrow().clone())
}

// A compact helper for callers that need to pull a scope out of the registry
// by id without importing the inner types.
pub fn invoke_handler(scope_id: ScopeId, key: &str, args: &Array) -> JsValue {
    match Scope::find(scope_id) {
        Some(s) => s.invoke(key, args),
        None => JsValue::UNDEFINED,
    }
}

#[allow(dead_code)]
fn _type_check(_: &Function) {}
