//! Component scopes and the JS-`Proxy` bridge they expose to directives.
//!
//! A scope owns a `ComponentState` (macro-generated), a stable `ScopeId`, and
//! a `js_sys::Proxy` whose `get`/`set` traps plug into [`crate::reactive`] so
//! any directive that reads a field through the proxy gets auto-subscribed.

use std::any::Any;
use std::cell::RefCell;
use std::collections::HashMap;
use std::rc::Rc;

use js_sys::{Array, Function, Object, Proxy, Reflect};
use wasm_bindgen::closure::Closure;
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsValue;
use web_sys::Element;

use crate::magics;
use crate::reactive::{next_scope_id, track, trigger, trigger_scope, ScopeId};

/// Implemented by components (generated by `#[component]` + `#[handlers]`).
pub trait ComponentState: 'static {
    /// Read a declared field as a JsValue (for proxy `get`).
    fn get(&self, key: &str) -> JsValue;

    /// Write a declared field from a JsValue (for proxy `set`).
    fn set(&mut self, key: &str, value: JsValue);

    /// All data keys this component exposes. Used for sweep-triggers after
    /// a handler invocation.
    fn keys(&self) -> &'static [&'static str];

    /// RFC-031 — is `key` annotated `#[prop]`? Returns `false` for
    /// state fields (the default — anything not explicitly
    /// marked as part of the parent contract). Used by
    /// `apply_static_props`, `pp-bind`'s child-prop write, and
    /// `pp-model`'s mirror-in leg to keep parents out of state.
    /// Unknown keys return `false` — the runtime also uses
    /// `keys()` / `set()` to know which fields exist at all.
    fn is_prop(&self, key: &str) -> bool {
        let _ = key;
        false
    }

    /// True iff `key` is a `#[model]` field. Runtime uses this for
    /// assignment-driven model publication and devtools metadata.
    fn is_model(&self, key: &str) -> bool {
        let _ = key;
        false
    }

    /// Public wire name reserved by a `#[model]` field. Returns `None`
    /// for non-model keys.
    fn model_name(&self, key: &str) -> Option<&'static str> {
        let _ = key;
        None
    }

    /// Serialize a model field with any field-level serde attrs still
    /// in play. Defaults to the plain field getter so non-component
    /// scopes keep compiling.
    fn get_model_value(&self, key: &str) -> JsValue {
        self.get(key)
    }

    /// Invoke a named method on `&mut self` with JS-land arguments.
    /// Returns a JsValue (or `JsValue::UNDEFINED` for void methods).
    fn invoke(&mut self, key: &str, args: &Array) -> JsValue;

    /// Lifecycle — called once right after the scope is minted and
    /// its RFC-027 parent is set, *before* the template's children
    /// walk. Lets compound-component children initialise fields
    /// from injected context so directives in their template see
    /// the populated values on first bind. Default no-op;
    /// `#[component]` wires the user's `on_setup` when one exists.
    fn setup(&mut self) {}

    /// Lifecycle — called once after the component's subtree is fully
    /// bound. Default no-op; `#[component]` wires the user's
    /// `on_mount` when one exists. RFC-032: receives a
    /// `LifecycleContext` so handler signatures can extract the
    /// rendered root, scope id, refs, etc. via `From`.
    fn mount(&mut self, ctx: crate::lifecycle::LifecycleContext<'_>) {
        let _ = ctx;
    }

    /// Lifecycle — called once, scheduled via `tick::next` AFTER
    /// `mount()` returns. Takes `&self` (not `&mut self`) so
    /// proxy-reading code inside the hook (watches, refs, etc.)
    /// doesn't clash with the scope's state borrow. Mutation in
    /// on_ready goes through `pocopine::this::<Self>().update(...)`.
    /// Default no-op; `#[component]` wires the user's `on_ready`
    /// when one exists. See RFC-026 / RFC-029 / RFC-032.
    fn on_ready(&self, ctx: crate::lifecycle::LifecycleContext<'_>) {
        let _ = ctx;
    }

    /// Lifecycle — called once just before the component is torn down.
    /// Default no-op; `#[component]` wires the user's `on_unmount`
    /// when one exists.
    fn unmount(&mut self) {}

    /// True iff the component has a user-defined `on_setup`.
    /// `mount_component` uses this to skip the setup call for
    /// components without the hook.
    fn has_setup(&self) -> bool {
        false
    }

    /// True iff the component actually has a user-defined `on_mount`.
    /// Lets the walker skip the post-mount `trigger_scope` sweep for
    /// components that don't need it — critical for recursive
    /// children, where a blanket sweep would cascade through the
    /// whole subtree.
    fn has_on_mount(&self) -> bool {
        false
    }

    /// True iff the component has a user-defined `on_ready` hook.
    /// Walker uses this to decide whether to schedule a microtask
    /// after mount — components without the hook pay nothing.
    fn has_on_ready(&self) -> bool {
        false
    }

    /// Symmetric with [`has_on_mount`]. Kept for parity; reserved
    /// for future devtools coverage displays.
    fn has_on_unmount(&self) -> bool {
        false
    }

    /// RFC-038 — enter preset name the component declared at
    /// `#[component(transition = "…")]` (or `transition_in`). The
    /// walker calls this once post-template-clone to stamp the
    /// preset's `pp-transition:*` attrs on the rendered root.
    fn transition_in_preset(&self) -> &'static str {
        ""
    }

    /// RFC-038 — leave preset name (`transition` or `transition_out`).
    fn transition_out_preset(&self) -> &'static str {
        ""
    }

    /// RFC-038 — keyed-pp-for layout-animation kind (only `"flip"`
    /// today). The walker's for_.rs hooks check this to decide
    /// whether to FLIP-animate reordered clones.
    fn animate_kind(&self) -> &'static str {
        ""
    }

    /// Human-readable tag / type name used by devtools. Default
    /// `"?"`; `#[component]` / `#[store]` override with the concrete
    /// kebab-case name.
    fn type_name(&self) -> &'static str {
        "?"
    }
}

/// A live component instance bound to a DOM element.
///
/// Holds both the type-erased `ComponentState` handle the walker uses and
/// a typed `Rc<RefCell<T>>` behind an `Any` for handler code that wants
/// to mutate the underlying Rust struct directly (see
/// [`crate::this`](crate::handle::this)).
#[derive(Clone)]
pub struct Scope {
    pub id: ScopeId,
    pub state: Rc<RefCell<dyn ComponentState>>,
    /// `Rc<RefCell<T>>` erased behind `dyn Any`. `T` is the concrete
    /// struct the user annotated with `#[component]` / `#[store]`.
    /// Downcast via [`Scope::typed`] to mutate Rust fields directly.
    pub typed: Rc<dyn Any>,
}

/// Type-erased storage for the two `Closure`s backing a proxy's
/// `get` and `set` traps. Kept as a `Vec<Box<dyn Any>>` so the
/// per-trap type parameters don't pollute the side-table's type.
/// Dropping the `Box<dyn Any>` drops the underlying `Closure`,
/// which reclaims the `Box<dyn Fn>` behind it — the whole point of
/// this table (old code called `.forget()` and leaked forever).
type AnyClosures = Vec<Box<dyn Any>>;

thread_local! {
    /// Registry of live scopes keyed by id. Directives look up the scope
    /// here to invoke handlers when an event fires.
    static SCOPES: RefCell<HashMap<ScopeId, Scope>> = RefCell::new(HashMap::new());

    /// Proxy-trap closures pinned to their owning scope id. Previously
    /// these were leaked via `Closure::forget()` — the comment there
    /// claimed "live as long as the scope" but `Scope::remove` had no
    /// code path to recover them. With the side-table, `Scope::remove`
    /// drops the entry and the two `Box<dyn Fn>` boxes behind the
    /// closures are reclaimed.
    static PROXY_CLOSURES: RefCell<HashMap<ScopeId, AnyClosures>> =
        RefCell::new(HashMap::new());

    /// The element the current directive is running against. Set by the
    /// walker immediately around each directive call so `$el` works without
    /// threading the element through every call site.
    static CURRENT_EL: RefCell<Option<Element>> = const { RefCell::new(None) };

    /// The scope whose handler is currently executing, if any. Set by
    /// `Scope::invoke` for the duration of the call so handlers can
    /// discover their own id — useful when a handler needs to capture the
    /// id for an `async` task that will mutate the scope after the
    /// handler returns.
    static CURRENT_SCOPE_ID: std::cell::Cell<Option<ScopeId>> =
        const { std::cell::Cell::new(None) };
}

impl Scope {
    /// Build a scope from a typed `Rc<RefCell<T>>`. Stashes both the
    /// type-erased and the typed form so later code (walker + handler
    /// handles) can choose the right one.
    pub fn new<T: ComponentState + 'static>(state: Rc<RefCell<T>>) -> Self {
        let id = next_scope_id();
        let erased: Rc<RefCell<dyn ComponentState>> = state.clone();
        let typed: Rc<dyn Any> = Rc::new(state);
        let scope = Scope {
            id,
            state: erased,
            typed,
        };
        SCOPES.with(|s| s.borrow_mut().insert(id, scope.clone()));
        scope
    }

    /// Look up a live scope by id.
    pub fn find(id: ScopeId) -> Option<Scope> {
        SCOPES.with(|s| s.borrow().get(&id).cloned())
    }

    /// Snapshot of every live scope, sorted by id. Devtools reads this
    /// to render the scope list.
    pub fn all() -> Vec<Scope> {
        SCOPES.with(|s| {
            let mut out: Vec<Scope> = s.borrow().values().cloned().collect();
            out.sort_by_key(|sc| sc.id.0);
            out
        })
    }

    /// Remove a scope from the registry. Called when its element is
    /// unmounted. Also drops any refs + captured slot content
    /// registered against this scope so we don't leak element
    /// handles.
    pub fn remove(id: ScopeId) {
        SCOPES.with(|s| s.borrow_mut().remove(&id));
        crate::refs::clear_scope(id);
        crate::slots::clear(id);
        crate::id::clear_scope(id);
        crate::context::clear_scope(id);
        crate::reactive::clear_scope(id);
        crate::component_computed::clear_scope(id);
        crate::model_runtime::clear_scope(id);
        crate::task::clear_scope(id);
        // Drop the proxy-trap closures that were pinned in
        // `into_proxy`. The `Box<dyn Any>` drop chain runs the
        // `Closure` destructor, which releases the underlying
        // `Box<dyn Fn>`.
        PROXY_CLOSURES.with(|m| {
            m.borrow_mut().remove(&id);
        });
    }

    /// Recover the typed inner `Rc<RefCell<T>>`, if `T` matches the struct
    /// this scope was created with. `None` on type mismatch.
    pub fn typed<T: 'static>(&self) -> Option<Rc<RefCell<T>>> {
        self.typed.downcast_ref::<Rc<RefCell<T>>>().cloned()
    }

    /// Build a `js_sys::Proxy` whose `get` trap records dependencies and
    /// whose `set` trap triggers them. The proxy is what every directive
    /// reads through.
    pub fn into_proxy(&self) -> JsValue {
        let target = Object::new();
        let handler = Object::new();
        let scope_id = self.id;
        let state_for_get = self.state.clone();
        let state_for_set = self.state.clone();

        let get_closure = Closure::wrap(Box::new(
            move |_target: JsValue, key: JsValue, _receiver: JsValue| -> JsValue {
                let Some(key_str) = key.as_string() else {
                    return JsValue::UNDEFINED;
                };
                // Magics take priority over user fields.
                if key_str.starts_with('$') {
                    return magics::resolve(&key_str, scope_id);
                }
                track(scope_id, &key_str);
                state_for_get.borrow().get(&key_str)
            },
        )
            as Box<dyn Fn(JsValue, JsValue, JsValue) -> JsValue>);

        let set_closure = Closure::wrap(Box::new(
            move |_target: JsValue, key: JsValue, value: JsValue, _receiver: JsValue| -> bool {
                let Some(key_str) = key.as_string() else {
                    return false;
                };
                let origin = crate::model_runtime::current_write_origin();
                crate::model_runtime::with_scope_write(scope_id, origin, || {
                    state_for_set.borrow_mut().set(&key_str, value);
                });
                trigger(scope_id, &key_str);
                true
            },
        )
            as Box<dyn Fn(JsValue, JsValue, JsValue, JsValue) -> bool>);

        Reflect::set(
            &handler,
            &"get".into(),
            get_closure.as_ref().unchecked_ref(),
        )
        .expect("set get trap");
        Reflect::set(
            &handler,
            &"set".into(),
            set_closure.as_ref().unchecked_ref(),
        )
        .expect("set set trap");

        // Pin the two closures in the per-scope side-table. The
        // handler `Object` holds their JS function pointers; we
        // hold the Rust `Closure` wrappers so the `Box<dyn Fn>`
        // they own is dropped when `Scope::remove` runs. Previously
        // a `.forget()` call leaked both boxes for the life of the
        // process.
        PROXY_CLOSURES.with(|m| {
            m.borrow_mut().entry(scope_id).or_default().extend([
                Box::new(get_closure) as Box<dyn Any>,
                Box::new(set_closure) as Box<dyn Any>,
            ]);
        });

        Proxy::new(&target, &handler).into()
    }

    /// Invoke a handler by name. Mutates Rust state directly, then sweep-
    /// triggers every key on this scope so effects re-evaluate.
    pub fn invoke(&self, key: &str, args: &Array) -> JsValue {
        let prev = CURRENT_SCOPE_ID.with(|c| c.replace(Some(self.id)));
        #[cfg(feature = "devtools")]
        let start = crate::devtools::ring::now_ms_for_scope();
        let out = crate::model_runtime::with_scope_write(
            self.id,
            crate::model_runtime::WriteOrigin::LocalHandler,
            || self.state.borrow_mut().invoke(key, args),
        );
        CURRENT_SCOPE_ID.with(|c| c.set(prev));
        trigger_scope(self.id);
        // Devtools hook — fired after trigger_scope so any effect
        // runs scheduled by this handler are visible on the timeline
        // with a seq > this handler's.
        #[cfg(feature = "devtools")]
        {
            let dur = std::time::Duration::from_micros(
                ((crate::devtools::ring::now_ms_for_scope() - start).max(0.0) * 1000.0) as u64,
            );
            crate::devtools::hooks::fire_handler_invoke(self.id, key, args, dur);
        }
        out
    }
}

/// The scope whose handler is currently on the stack. `None` outside of a
/// handler invocation. Handlers use this to hand their id to an async task:
///
/// ```ignore
/// pub fn init(&mut self) {
///     let id = pocopine::current_scope_id().unwrap();
///     self.loading = true;
///     wasm_bindgen_futures::spawn_local(async move {
///         let post = api::get_post(1).await;
///         if let Some(scope) = Scope::find(id) {
///             scope.state.borrow_mut().set("title", /* ... */);
///             pocopine::reactive::trigger_scope(id);
///         }
///     });
/// }
/// ```
pub fn current_scope_id() -> Option<ScopeId> {
    CURRENT_SCOPE_ID.with(|c| c.get())
}

/// Run `f` with `CURRENT_SCOPE_ID` set to `id`, restoring the prior
/// value on exit. Used by [`crate::handle::Handle::update`] so
/// `dispatch!` / `this::<T>()` called from inside an async update
/// closure still sees its own scope. Also used internally by
/// [`Scope::invoke`].
pub fn with_current_scope_id<R>(id: ScopeId, f: impl FnOnce() -> R) -> R {
    let prev = CURRENT_SCOPE_ID.with(|c| c.replace(Some(id)));
    let out = f();
    CURRENT_SCOPE_ID.with(|c| c.set(prev));
    out
}

/// Set the current element for the duration of a directive call. The caller
/// is responsible for clearing it on exit.
pub fn with_current_el<R>(el: &Element, f: impl FnOnce() -> R) -> R {
    let prev = CURRENT_EL.with(|c| c.replace(Some(el.clone())));
    let out = f();
    CURRENT_EL.with(|c| *c.borrow_mut() = prev);
    out
}

/// The element the current directive is running against, if any.
pub fn current_el() -> Option<Element> {
    CURRENT_EL.with(|c| c.borrow().clone())
}

// A compact helper for callers that need to pull a scope out of the registry
// by id without importing the inner types.
pub fn invoke_handler(scope_id: ScopeId, key: &str, args: &Array) -> JsValue {
    match Scope::find(scope_id) {
        Some(s) => s.invoke(key, args),
        None => JsValue::UNDEFINED,
    }
}

#[allow(dead_code)]
fn _type_check(_: &Function) {}
