[package]
name = "fat-routes"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pocopine = { path = "../../crates/pocopine", default-features = false }
wasm-bindgen = { workspace = true }
serde = { workspace = true }
js-sys = { workspace = true }
