//! The canonical Agenkit example (RFC-093), authored with the `#[ai_tool]` /
//! `#[ai_flow]` macros (RFC-093 §D14).
//!
//! Run with: `cargo run -p pocopine-agenkit --example summarize`
//!
//! **Flows are internal logic, not endpoints.** A real app exposes a flow
//! through a plain `#[server]` function and threads the caller identity with
//! the Agenkit server plugin:
//!
//! ```ignore
//! Server::new(router)
//!     .with_auth(my_auth)
//!     .plugin(pocopine_agenkit::server::agenkit_server_plugin(agenkit))
//!     .serve(addr).await?;
//!
//! #[server(public)]
//! pub async fn summarize(input: SummarizeInput) -> ServerResult<Summary> {
//!     pocopine_server::active_plugin::<Agenkit>()
//!         .expect("agenkit_server_plugin installed")
//!         .flow(Summarize).input(input).run()    // typed marker from #[ai_flow]
//!         .await
//!         .map_err(|e| pocopine_agenkit::server::to_server_error(&e))
//! }
//! ```
//!
//! The plugin's principal layer scopes the request `Principal`, so the flow's
//! tools/retrieval/threads run under the caller (§D5/§D10/§D15 DC-5) — the
//! `#[server]` body never touches the principal directly.
//!
//! This example just runs the flow in-process (no server); the runtime is
//! host-only, so the body is gated off `wasm32`.

#[cfg(not(target_arch = "wasm32"))]
mod host {
    use pocopine_agenkit::prelude::*;
    use pocopine_agenkit::{ai_flow, ai_tool};
    use serde::{Deserialize, Serialize};

    #[derive(Serialize, Deserialize, schemars::JsonSchema)]
    struct SummarizeInput {
        prompt: String,
    }

    #[derive(Serialize, Deserialize, Debug, schemars::JsonSchema)]
    struct Summary {
        title: String,
        words: u32,
    }

    #[derive(Deserialize, schemars::JsonSchema)]
    struct WordCountInput {
        text: String,
    }

    /// Count the words in a string.
    #[ai_tool]
    async fn word_count(input: WordCountInput, _ctx: AiToolContext) -> AgenkitResult<u32> {
        Ok(input.text.split_whitespace().count() as u32)
    }

    /// The flow: typed input, typed structured output, one trace tree.
    #[ai_flow(tools("word_count"))]
    async fn summarize(input: SummarizeInput, ctx: AiFlowContext) -> AgenkitResult<Summary> {
        ctx.ai()
            .system("Summarize the prompt as a title and a word count.")
            .prompt(input.prompt)
            .schema::<Summary>()
            .generate_structured()
            .await
    }

    /// Configure AI once (§D3).
    fn agenkit() -> Agenkit {
        Agenkit::builder()
            .provider(
                MockProvider::new("local")
                    .default_structured(serde_json::json!({"title": "Uploads", "words": 12})),
            )
            .default_model(ModelRef::new("local/default"))
            .tool(WordCount) // unit struct generated by #[ai_tool]
            .flow(Summarize) // marker struct generated by #[ai_flow]
            .build()
            .expect("valid runtime")
    }

    pub async fn run() -> Result<(), Box<dyn std::error::Error>> {
        // In a server this is the body of a `#[server]` fn (see the module docs);
        // here we run the flow directly. The typed `flow(Summarize)` call checks
        // the input against `SummarizeInput` and infers the `Summary` output; it
        // runs under the ambient principal (anonymous in this standalone example).
        let summary: Summary = agenkit()
            .flow(Summarize)
            .input(SummarizeInput {
                prompt: "How do uploads work?".to_string(),
            })
            .run()
            .await?;
        println!("summary: {summary:?}");
        Ok(())
    }
}

#[cfg(not(target_arch = "wasm32"))]
#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    host::run().await
}

/// The runtime does not build for `wasm32`; keep the example target compiling.
#[cfg(target_arch = "wasm32")]
fn main() {}
