//! The canonical Agenkit example (RFC-093), authored with the `#[ai_tool]` /
//! `#[ai_flow]` / `#[ai_server_flow]` macros (RFC-093 §D14).
//!
//! Run with: `cargo run -p pocopine-agenkit --example summarize`
//!
//! A real app swaps `MockProvider` for a hosted provider (server-only
//! credentials). The browser calls `summarize_endpoint(input)`; the generated
//! bridge fetches the principal-aware flow route on wasm and calls
//! `run_public_flow` on the host.
//!
//! The runtime is host-only, so the example body is gated off `wasm32`; the
//! workspace's wasm build keeps a no-op `main`.

#[cfg(not(target_arch = "wasm32"))]
mod host {
    use pocopine_agenkit::prelude::*;
    use pocopine_agenkit::{ai_flow, ai_server_flow, ai_tool};
    use pocopine_core::ServerError;
    use serde::{Deserialize, Serialize};

    #[derive(Serialize, Deserialize, schemars::JsonSchema)]
    struct SummarizeInput {
        prompt: String,
    }

    #[derive(Serialize, Deserialize, Debug, schemars::JsonSchema)]
    struct Summary {
        title: String,
        words: u32,
    }

    #[derive(Deserialize, schemars::JsonSchema)]
    struct WordCountInput {
        text: String,
    }

    /// Count the words in a string.
    #[ai_tool]
    async fn word_count(input: WordCountInput, _ctx: AiToolContext) -> AgenkitResult<u32> {
        Ok(input.text.split_whitespace().count() as u32)
    }

    /// The app-callable flow: typed input, typed structured output, one trace tree.
    #[ai_flow(public, tools("word_count"))]
    async fn summarize(input: SummarizeInput, ctx: AiFlowContext) -> AgenkitResult<Summary> {
        ctx.ai()
            .system("Summarize the prompt as a title and a word count.")
            .prompt(input.prompt)
            .schema::<Summary>()
            .generate_structured()
            .await
    }

    /// The public-flow bridge the browser calls. Host body becomes
    /// `agenkit().run_public_flow("summarize", input)`.
    #[ai_server_flow(flow = "summarize", runtime = agenkit)]
    pub async fn summarize_endpoint(input: SummarizeInput) -> Result<Summary, ServerError> {}

    /// Configure AI once (§D3).
    fn agenkit() -> Agenkit {
        Agenkit::builder()
            .provider(
                MockProvider::new("local")
                    .default_structured(serde_json::json!({"title": "Uploads", "words": 12})),
            )
            .default_model(ModelRef::new("local/default"))
            .tool(WordCount) // unit struct generated by #[ai_tool]
            .flow(summarize()) // `fn summarize() -> impl FlowHandler` generated by #[ai_flow]
            .build()
            .expect("valid runtime")
    }

    pub async fn run() -> Result<(), Box<dyn std::error::Error>> {
        let summary = summarize_endpoint(SummarizeInput {
            prompt: "How do uploads work?".to_string(),
        })
        .await?;
        println!("summary: {summary:?}");
        Ok(())
    }
}

#[cfg(not(target_arch = "wasm32"))]
#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    host::run().await
}

/// The runtime does not build for `wasm32`; keep the example target compiling.
#[cfg(target_arch = "wasm32")]
fn main() {}
