// This file was generated by Pocopine's vendored ts-rs fork. Do not edit this file manually.

export type FirebaseAuthUser = { token: string, uid: string, email: string | null, name: string | null, photoUrl: string | null, };
