use std::future::Future;
use std::pin::Pin;

use pocopine_core::ServerResult;
use pocopine_server::RequestContext;
use serde_json::Value;

use crate::{
    SyncError, SyncPullRequest, SyncPullResponse, SyncPushRequest, SyncPushResponse, SyncResult,
};

/// Future returned by a stream source.
pub type SyncBoxFuture<'a, T> = Pin<Box<dyn Future<Output = SyncResult<T>> + Send + 'a>>;

/// Future returned by a stream guard.
pub type SyncGuardFuture<'a> = Pin<Box<dyn Future<Output = ServerResult<()>> + Send + 'a>>;

/// Server-side source for one registered sync stream.
///
/// The request context is passed into each source call after stream-level
/// authorization has succeeded. Sources still own tenant filtering, cursor
/// validation, and any per-row visibility rules.
pub trait SyncStreamSource: Send + Sync + 'static {
    /// Server-registered stream name.
    fn stream(&self) -> &crate::SyncStreamName;

    /// Public collection name represented by this stream.
    fn collection(&self) -> &crate::SyncCollectionName;

    /// Current cursor, if the source can cheaply report it.
    fn current_cursor(&self, ctx: &RequestContext) -> Option<crate::SyncCursor> {
        let _ = ctx;
        None
    }

    /// Opaque principal scope for one authenticated request.
    ///
    /// The framework calls this on every `/open` and `/pull` and stamps
    /// the result onto the response, so the client can tell WHICH
    /// principal's truth it is settling. Derive it from the
    /// authenticated context — a user id, tenant id, or a stable hash
    /// of either. The client never interprets the value; it only
    /// compares for equality against the scope persisted with its
    /// durable cache compartment, refusing to let one principal's
    /// responses overwrite another principal's cached rows (the
    /// session-expired-to-guest clobber).
    ///
    /// Default `None` = this stream doesn't scope responses; the
    /// client-side guard stays inert and behavior is unchanged. An
    /// `Err` fails the request — a source that scopes MUST be able to
    /// name the principal, and answering unscoped when the session
    /// can't be resolved is exactly the bug this hook exists to stop.
    fn scope<'a>(&'a self, ctx: &'a RequestContext) -> SyncBoxFuture<'a, Option<crate::SyncScope>> {
        let _ = ctx;
        Box::pin(async { Ok(None) })
    }

    /// Application-level schema version for this stream's row/draft shape.
    ///
    /// Bump this whenever the row, draft, or payload shape changes in a way
    /// that older cached data or queued mutations cannot deserialize into.
    /// The version is advertised on every `/open` response so the client
    /// can detect mismatches and either drop its cache + queue (default
    /// from `SyncLocalStore::clear_stream`) or migrate via the opt-in
    /// `migrate_payload` path on this trait (shipping in a follow-up).
    ///
    /// Defaults to `1` — apps that never bump never need to think about
    /// this. Authors using `#[resource]` set this through the
    /// `schema_version = N` attribute; bare `SyncStreamSource` impls
    /// override this method directly.
    fn schema_version(&self) -> u32 {
        crate::protocol::default_schema_version_one()
    }

    /// Validate the subscription parameters sent by the client on
    /// `/open`, `/pull`, and `/push`.
    ///
    /// **Safe default:** any non-empty params map is rejected. Sources
    /// that have not declared a `params(...)` schema cannot know what
    /// the keys mean, so silently letting arbitrary params travel to
    /// `pull`/`push` would let a malicious client smuggle filter state
    /// the source has no contract for. Override this method (or use
    /// `#[resource(params(...))]`, which generates a typed validator)
    /// to opt into shape subscriptions.
    ///
    /// Sources generated by `#[resource(params(...))]` override this
    /// with a strongly-typed validator that:
    ///
    /// * Rejects unknown param keys (`InvalidValue { field, value }`).
    /// * Coerces each value into its declared comparator type
    ///   (`InSet<T>`, `Range<T>`, `Contains`, bare `T`, `Option<T>`).
    /// * Requires all non-`Option` params to be present.
    ///
    /// `Err` here surfaces as `BadRequest` via `server_error`; the
    /// open/pull/push handler rejects the request before invoking
    /// the source.
    fn validate_params(&self, params: &crate::StreamParams) -> SyncResult<()> {
        // The default validator accepts empty params AND
        // reserved-only params (keys prefixed with `__`). Reserved
        // keys carry framework-level metadata — `__order_by`,
        // `__limit`, etc. — that any source can safely ignore.
        // Sources that don't declare a shape should still pass for
        // wire envelopes that only carry reserved-key metadata.
        // Non-reserved keys still require an opt-in override.
        if params.keys().all(|k| k.starts_with("__")) {
            Ok(())
        } else {
            Err(SyncError::invalid_value(
                "params",
                "stream does not declare any subscription params (override SyncStreamSource::validate_params or use #[resource(params(...))])",
            ))
        }
    }

    /// Validate subscription parameters specifically for the `/push`
    /// endpoint. Defaults to [`validate_params`] so a single
    /// declaration governs `/open`, `/pull`, AND `/push` for sources
    /// that want strict shape validation everywhere.
    ///
    /// CRUD-style sources opt out of strict push validation by
    /// overriding this method to accept an empty `params` map (and
    /// only an empty map) — see `CrudResource::validate_push_params`.
    /// The rationale: generated CRUD `create`/`save`/`remove` writes
    /// don't know which subscription they belong to and the per-row
    /// tenant identity lives inside the mutation payload (see
    /// `docs/sync-shape-subscriptions.md`'s pitfalls). For shape-
    /// aware sources that DO require params on every push, the
    /// default keeps the strict gate.
    ///
    /// [`validate_params`]: SyncStreamSource::validate_params
    fn validate_push_params(&self, params: &crate::StreamParams) -> SyncResult<()> {
        self.validate_params(params)
    }

    /// Pull changes or a snapshot for this stream.
    fn pull<'a>(
        &'a self,
        ctx: RequestContext,
        request: SyncPullRequest,
    ) -> SyncBoxFuture<'a, SyncPullResponse<Value>>;

    /// Push client mutations for this stream.
    fn push<'a>(
        &'a self,
        ctx: RequestContext,
        request: SyncPushRequest<Value>,
    ) -> SyncBoxFuture<'a, SyncPushResponse<Value>> {
        let _ = ctx;
        let _ = request;
        Box::pin(async {
            Err(SyncError::unsupported(
                "push is not implemented for this stream",
            ))
        })
    }

    /// Migrate a client-side mutation payload encoded under `from` to
    /// the source's currently-advertised schema version `to`.
    ///
    /// The framework's `push_handler` invokes this once per mutation
    /// when the request's `schema_version` is **strictly less than**
    /// `self.schema_version()`. A newer client pushing to an older
    /// server (rolling-deploy edge case) is NOT routed through
    /// migration — the source receives the newer-shape payload as-is.
    ///
    /// The default implementation returns `SyncError::SchemaMigration`
    /// so any out-of-tree source that hasn't opted in surfaces a clean
    /// per-mutation rejection rather than silently mis-deserializing
    /// stale payloads into the new shape. Apps that want to accept
    /// stale pushes (e.g. to preserve side-effecting writes like
    /// payments across a schema bump) override this method directly or
    /// use the `#[resource(schema_version = N, migrate_with = path)]`
    /// macro attribute which generates the impl.
    ///
    /// On `Ok`, the framework stores the migrated payload alongside
    /// the original (via `ClientMutation::migration_outcome`) so the
    /// source can deserialize the migrated value while still keying
    /// its idempotency log on the original wire payload. On `Err`,
    /// the framework stores the error reason in the same sidecar —
    /// the source surfaces it as a per-mutation rejection ONLY for
    /// mutations not already in its idempotency log (a retry of an
    /// already-accepted mutation succeeds even if the migrator now
    /// rejects). See `ClientMutation::take_processing_payload`.
    ///
    /// **Envelope constraint.** This method migrates the
    /// `serde_json::Value` payload only — it CANNOT migrate the
    /// outer `ClientMutation` (`key`, `op`, `base_version`). For
    /// changes to row-key shape (e.g. ID rename), prefer the
    /// default drop-the-cache path: bump `schema_version`, let the
    /// client wipe pending mutations + canonical rows, and rebuild
    /// from `/pull`.
    fn migrate_payload<'a>(&'a self, from: u32, to: u32, value: Value) -> SyncBoxFuture<'a, Value> {
        let _ = value;
        let stream = self.stream().as_str().to_string();
        Box::pin(async move { Err(SyncError::schema_migration(stream, from, to)) })
    }

    /// Project a canonical row payload into the [`StreamParams`] that
    /// identify which subscribers care about it (RFC 088 §C).
    ///
    /// The server hashes the returned params and publishes the
    /// resulting invalidation to a per-(stream, params_hash) topic
    /// so only clients whose subscription params match wake up.
    /// Clients on the matching `(stream, params)` subscription
    /// compute the SAME hash and listen on the SAME topic — see
    /// [`crate::protocol::stream_params_hash`] for the contract.
    ///
    /// Default: empty params, equivalent to bare-topic publish only
    /// (backwards-compatible). The `#[query_resource]` macro
    /// auto-emits an override that projects each `#[query_param]`
    /// field into the params map; sources written by hand can
    /// override to opt into precise routing.
    ///
    /// The framework calls this AFTER the source's `push` returned
    /// `accepted` and the row has been persisted, so it sees the
    /// post-mutation row shape. A `None` return falls back to the
    /// bare-topic publish path (no per-params routing).
    ///
    /// Errors propagate up to `invalidate_stream_with_row`, which
    /// logs them via `tracing::warn!` and falls back to bare publish
    /// — a malformed row must NOT block the canonical write.
    fn row_to_params(&self, _row: &Value) -> SyncResult<crate::StreamParams> {
        Ok(crate::StreamParams::new())
    }
}
