[package]
name = "hn"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.pocopine]
bin = "server"
port = 3001

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "server"
path = "src/bin/server.rs"

[dependencies]
pocopine = { path = "../../crates/pocopine" }
wasm-bindgen = { workspace = true }
serde = { workspace = true }
web-sys = { version = "0.3", features = ["Window", "Performance"] }
js-sys = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pocopine-server = { path = "../../crates/pocopine-server" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net"] }
reqwest = { version = "0.12", default-features = false, features = [
    "json",
    "rustls-tls-webpki-roots",
] }
futures = "0.3"
