[package]
name = "site"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.pocopine]
bin = "server"
port = 3000

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "server"
path = "src/bin/server.rs"

[dependencies]
pocopine = { path = "../../crates/pocopine" }
wasm-bindgen = { workspace = true }
serde = { workspace = true }
web-sys = { version = "0.3", features = ["Window", "Performance"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pocopine-server = { path = "../../crates/pocopine-server" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net"] }
serde_json = "1"
