//! Project-level compile entry (RFC 092 build/dev integration).
//!
//! Ties the pieces together for a front-end (the CLI): read `@theme`
//! tokens, extract classes from every `.poco` source, dedup + sort for
//! deterministic output, then compile. The CLI owns discovery (which
//! files) and IO (writing the stylesheet); this owns the compile.

use std::collections::BTreeMap;
use std::path::PathBuf;

use crate::extract::{extract_poco, UsedClass};
use crate::{CompileOptions, Compiler, Diagnostic, Severity, ThemeTokens};

/// One `.poco` source file to compile.
#[derive(Debug, Clone)]
pub struct SourceFile {
    pub path: PathBuf,
    pub source: String,
}

/// Result of compiling a whole project's worth of `.poco` files.
#[derive(Debug, Default)]
pub struct ProjectCss {
    /// Deterministic stylesheet for every used utility.
    pub css: String,
    /// All diagnostics (extraction + compilation), in file order.
    pub diagnostics: Vec<Diagnostic>,
    /// File table — `Span::file` indexes into this. Mirrors the order
    /// of the `files` slice passed to [`compile_project`].
    pub files: Vec<PathBuf>,
}

impl ProjectCss {
    pub fn has_errors(&self) -> bool {
        self.diagnostics
            .iter()
            .any(|d| d.severity == Severity::Error)
    }

    pub fn error_count(&self) -> usize {
        self.diagnostics
            .iter()
            .filter(|d| d.severity == Severity::Error)
            .count()
    }
}

const HEADER: &str = "/* Generated by Pine Stylekit — do not edit. */\n";

/// Compile a project: `theme_css` is the app CSS holding `@theme`
/// tokens; `files` are the `.poco` sources to scan. Output is
/// deterministic — classes are deduped and sorted before emission, so
/// the same inputs always yield byte-identical CSS.
pub fn compile_project(
    theme_css: &str,
    files: &[SourceFile],
    options: CompileOptions,
) -> ProjectCss {
    let tokens = ThemeTokens::from_css(theme_css);
    let compiler = Compiler::new(tokens, options);

    let mut diagnostics = Vec::new();
    // Dedup by class literal; BTreeMap keeps emission order stable.
    let mut unique: BTreeMap<String, UsedClass> = BTreeMap::new();

    for (id, file) in files.iter().enumerate() {
        let extraction = extract_poco(id as u32, &file.source);
        diagnostics.extend(extraction.diagnostics);
        for class in extraction.classes {
            unique.entry(class.value.clone()).or_insert(class);
        }
    }

    let used: Vec<UsedClass> = unique.into_values().collect();
    let mut compiled = compiler.compile(&used);
    diagnostics.append(&mut compiled.diagnostics);

    ProjectCss {
        css: format!("{HEADER}{}", compiled.css),
        diagnostics,
        files: files.iter().map(|f| f.path.clone()).collect(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn compiles_two_files_deterministically() {
        let theme = "@theme { --color-surface: #fff; }";
        let files = vec![
            SourceFile {
                path: "a.poco".into(),
                source: r#"<div class="flex bg-surface"></div>"#.into(),
            },
            SourceFile {
                path: "b.poco".into(),
                // `flex` repeated across files emits once.
                source: r#"<span class="flex items-center"></span>"#.into(),
            },
        ];
        let out = compile_project(theme, &files, CompileOptions::default());
        assert!(!out.has_errors(), "{:?}", out.diagnostics);
        assert_eq!(out.css.matches(".flex {").count(), 1, "dedup across files");
        assert!(out.css.starts_with(HEADER));
        // Re-running yields identical bytes.
        let again = compile_project(theme, &files, CompileOptions::default());
        assert_eq!(out.css, again.css);
    }

    #[test]
    fn surfaces_unknown_token_with_file() {
        let files = vec![SourceFile {
            path: "x.poco".into(),
            source: r#"<div class="bg-ghost"></div>"#.into(),
        }];
        let out = compile_project("@theme {}", &files, CompileOptions::default());
        assert!(out.has_errors());
        assert_eq!(out.diagnostics[0].span.file, 0);
    }
}
