//! Project-level compile entry (RFC 092 build/dev integration).
//!
//! Ties the pieces together for a front-end (the CLI): read `@theme`
//! tokens, extract classes from every `.poco` source, dedup + sort for
//! deterministic output, then compile. The CLI owns discovery (which
//! files) and IO (writing the stylesheet); this owns the compile.

use std::collections::BTreeMap;
use std::path::PathBuf;

use crate::extract::{extract_poco, UsedClass};
use crate::{CompileOptions, Compiler, Diagnostic, Severity, ThemeTokens};

/// One `.poco` source file to compile.
#[derive(Debug, Clone)]
pub struct SourceFile {
    pub path: PathBuf,
    pub source: String,
}

/// Result of compiling a whole project's worth of `.poco` files.
#[derive(Debug, Default)]
pub struct ProjectCss {
    /// Deterministic stylesheet for every used utility.
    pub css: String,
    /// All diagnostics (extraction + compilation), in file order.
    pub diagnostics: Vec<Diagnostic>,
    /// File table — `Span::file` indexes into this. Mirrors the order
    /// of the `files` slice passed to [`compile_project`].
    pub files: Vec<PathBuf>,
}

impl ProjectCss {
    pub fn has_errors(&self) -> bool {
        self.diagnostics
            .iter()
            .any(|d| d.severity == Severity::Error)
    }

    pub fn error_count(&self) -> usize {
        self.diagnostics
            .iter()
            .filter(|d| d.severity == Severity::Error)
            .count()
    }
}

const HEADER: &str = "/* Generated by Pine Stylekit — do not edit. */\n";

/// Base reset (Preflight, M2-B) — a close subset of Tailwind v4's
/// Preflight: border-box everywhere, margin/padding zeroing, and the
/// native-control resets that opt out of browser-default styling (form
/// controls get a transparent background so a bare `<button>`/`<input>`
/// doesn't show the OS-native grey, etc.). Toggle via
/// [`CompileOptions::preflight`]. The `@keyframes` are stylekit's (Tailwind
/// defines them outside Preflight) so `animate-*` utilities have targets.
const PREFLIGHT: &str = "\
*, ::before, ::after, ::backdrop, ::file-selector-button { box-sizing: border-box; border-width: 0; border-style: solid; }
* { margin: 0; padding: 0; }
html, :host { line-height: 1.5; -webkit-text-size-adjust: 100%; tab-size: 4; font-family: var(--font-sans, ui-sans-serif, system-ui, sans-serif); -webkit-tap-highlight-color: transparent; }
body { min-height: 100vh; line-height: inherit; -webkit-font-smoothing: antialiased; }
hr { height: 0; color: inherit; border-top-width: 1px; }
h1, h2, h3, h4, h5, h6 { font-size: inherit; font-weight: inherit; }
a { color: inherit; text-decoration: inherit; }
b, strong { font-weight: bolder; }
code, kbd, samp, pre { font-family: var(--font-mono, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace); font-size: 1em; }
small { font-size: 80%; }
sub, sup { font-size: 75%; line-height: 0; position: relative; vertical-align: baseline; }
sub { bottom: -0.25em; }
sup { top: -0.5em; }
table { text-indent: 0; border-color: inherit; border-collapse: collapse; }
img, svg, video, canvas, audio, iframe, embed, object { display: block; vertical-align: middle; }
img, video { max-width: 100%; height: auto; }
button, input, select, optgroup, textarea, ::file-selector-button { font: inherit; letter-spacing: inherit; color: inherit; border-radius: 0; background-color: transparent; opacity: 1; }
::placeholder { opacity: 1; }
textarea { resize: vertical; }
summary { display: list-item; }
progress { vertical-align: baseline; }
button, input:where([type=button], [type=reset], [type=submit]), ::file-selector-button { cursor: pointer; -webkit-appearance: button; appearance: button; }
:disabled { cursor: default; }
ol, ul, menu { list-style: none; }
@keyframes spin { to { transform: rotate(360deg); } }
@keyframes ping { 75%, 100% { transform: scale(2); opacity: 0; } }
@keyframes pulse { 50% { opacity: 0.5; } }
@keyframes bounce { 0%, 100% { transform: translateY(-25%); animation-timing-function: cubic-bezier(0.8, 0, 1, 1); } 50% { transform: none; animation-timing-function: cubic-bezier(0, 0, 0.2, 1); } }
";

/// Collect class names defined as real rules in the author's CSS — every
/// `.ident` that appears in a *selector*. Comments, string literals, and
/// **declaration blocks** (a style rule's `{ … }` body) are skipped, so a
/// `.foo` mentioned in a comment, inside `content: ".foo"` / `url(...)`, or
/// as part of a property value is NOT mistaken for a component class (which
/// would make the compiler silently drop the real utility of the same name).
///
/// Selectors nested inside an at-rule that holds a *rule list* — `@media`,
/// `@supports`, `@container`, `@layer`, `@scope`, `@document` — are still
/// collected: those bodies are selector context, not declarations. (Tracking
/// declaration blocks rather than raw brace depth is what makes that work.)
fn defined_classes(css: &str) -> std::collections::BTreeSet<String> {
    let mut set = std::collections::BTreeSet::new();
    let bytes = css.as_bytes();
    let mut i = 0;
    // Stack of "is this block a declaration body?" — class selectors live in
    // selector position (top level, or inside an at-rule's rule list), never
    // inside a style rule's declaration body.
    let mut decl_stack: Vec<bool> = Vec::new();
    // Start of the current prelude (selector / at-rule head); reset at every
    // structural delimiter so the next `{` can be classified.
    let mut prelude_start = 0usize;
    while i < bytes.len() {
        match bytes[i] {
            // Skip block comments.
            b'/' if bytes.get(i + 1) == Some(&b'*') => {
                let comment_start = i;
                i += 2;
                while i < bytes.len() && !(bytes[i] == b'*' && bytes.get(i + 1) == Some(&b'/')) {
                    i += 1;
                }
                i += 2;
                // A comment leading a prelude (only whitespace before it) is
                // not part of the selector / at-rule head — drop it so the
                // next `{` is classified by its real first token (e.g. an
                // `@media` banner comment doesn't hide the at-rule).
                if css[prelude_start..comment_start].trim().is_empty() {
                    prelude_start = i;
                }
            }
            // Skip string literals (handles `content: ".x"`, `url("…")`).
            q @ (b'"' | b'\'') => {
                i += 1;
                while i < bytes.len() && bytes[i] != q {
                    i += if bytes[i] == b'\\' { 2 } else { 1 };
                }
                i += 1;
            }
            b'{' => {
                // An at-rule that holds a rule list keeps selector context for
                // its body; everything else (style rules, `@font-face`, …) is
                // a declaration block.
                let prelude = css[prelude_start..i].trim_start();
                let holds_rule_list = prelude.strip_prefix('@').is_some_and(|rest| {
                    let name: String = rest
                        .chars()
                        .take_while(|c| c.is_ascii_alphanumeric() || *c == '-')
                        .flat_map(char::to_lowercase)
                        .collect();
                    matches!(
                        name.as_str(),
                        "media" | "supports" | "container" | "layer" | "scope" | "document"
                    )
                });
                decl_stack.push(!holds_rule_list);
                prelude_start = i + 1;
                i += 1;
            }
            b'}' => {
                decl_stack.pop();
                prelude_start = i + 1;
                i += 1;
            }
            b';' => {
                prelude_start = i + 1;
                i += 1;
            }
            b'.' if !matches!(decl_stack.last(), Some(true)) => {
                let start = i + 1;
                if start < bytes.len()
                    && (bytes[start].is_ascii_alphabetic()
                        || bytes[start] == b'_'
                        || bytes[start] == b'-')
                {
                    let mut j = start;
                    while j < bytes.len()
                        && (bytes[j].is_ascii_alphanumeric()
                            || bytes[j] == b'-'
                            || bytes[j] == b'_')
                    {
                        j += 1;
                    }
                    set.insert(css[start..j].to_string());
                    i = j;
                } else {
                    i += 1;
                }
            }
            _ => i += 1,
        }
    }
    set
}

/// Compile a project: `theme_css` is the app CSS holding `@theme`
/// tokens; `files` are the `.poco` sources to scan. Output is
/// deterministic — classes are deduped and sorted before emission, so
/// the same inputs always yield byte-identical CSS.
pub fn compile_project(
    theme_css: &str,
    files: &[SourceFile],
    options: CompileOptions,
) -> ProjectCss {
    let tokens = ThemeTokens::from_css(theme_css);
    let root_css = tokens.to_root_css();
    // Author's hand-written CSS (component classes, @media, [data-theme]
    // overrides, @keyframes) — emitted verbatim alongside the utilities.
    let passthrough = crate::tokens::non_theme_css(theme_css);
    let preflight = if options.preflight { PREFLIGHT } else { "" };
    // Class names the author defined in that CSS are valid component
    // classes — register them so the compiler skips (not errors on) them.
    let mut options = options;
    options.known_classes = defined_classes(&passthrough);
    let compiler = Compiler::new(tokens, options);

    let mut diagnostics = Vec::new();
    // An unterminated `@theme {` makes both the token reader and the
    // passthrough skip to EOF, silently dropping everything after it —
    // warn so the author sees a signal instead of vanished CSS.
    if crate::tokens::has_unterminated_theme(theme_css) {
        diagnostics.push(Diagnostic::warning(
            "unterminated `@theme {` block (missing `}`) — CSS after it was dropped",
        ));
    }
    // Dedup by class literal; BTreeMap keeps emission order stable.
    let mut unique: BTreeMap<String, UsedClass> = BTreeMap::new();

    for (id, file) in files.iter().enumerate() {
        let extraction = extract_poco(id as u32, &file.source);
        diagnostics.extend(extraction.diagnostics);
        for class in extraction.classes {
            unique.entry(class.value.clone()).or_insert(class);
        }
    }

    let used: Vec<UsedClass> = unique.into_values().collect();
    let mut compiled = compiler.compile(&used);
    diagnostics.append(&mut compiled.diagnostics);

    ProjectCss {
        css: format!(
            "{HEADER}{preflight}{root_css}{}\n{passthrough}\n",
            compiled.css
        ),
        diagnostics,
        files: files.iter().map(|f| f.path.clone()).collect(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn compiles_two_files_deterministically() {
        let theme = "@theme { --color-surface: #fff; }";
        let files = vec![
            SourceFile {
                path: "a.poco".into(),
                source: r#"<div class="flex bg-surface"></div>"#.into(),
            },
            SourceFile {
                path: "b.poco".into(),
                // `flex` repeated across files emits once.
                source: r#"<span class="flex items-center"></span>"#.into(),
            },
        ];
        let out = compile_project(theme, &files, CompileOptions::default());
        assert!(!out.has_errors(), "{:?}", out.diagnostics);
        assert_eq!(out.css.matches(".flex {").count(), 1, "dedup across files");
        assert!(out.css.starts_with(HEADER));
        // Self-contained: tokens emitted to :root, preflight present.
        assert!(out.css.contains(":root {"));
        assert!(out.css.contains("--color-surface: #fff;"));
        assert!(out.css.contains("box-sizing: border-box;"));
        // Re-running yields identical bytes.
        let again = compile_project(theme, &files, CompileOptions::default());
        assert_eq!(out.css, again.css);
    }

    #[test]
    fn preflight_can_be_disabled() {
        let files = vec![SourceFile {
            path: "a.poco".into(),
            source: r#"<div class="flex"></div>"#.into(),
        }];
        let on = compile_project("@theme {}", &files, CompileOptions::default());
        assert!(on.css.contains("box-sizing: border-box"));
        let off = compile_project(
            "@theme {}",
            &files,
            CompileOptions {
                preflight: false,
                ..Default::default()
            },
        );
        assert!(!off.css.contains("box-sizing"));
        assert!(off.css.contains(".flex {"));
    }

    #[test]
    fn passes_through_custom_css_and_registers_its_classes() {
        // app.css mixes @theme tokens with hand-written component CSS.
        // A comment mentioning `@theme` must NOT strip the rule below it.
        let theme = "\
@theme { --color-surface: #fff; }
/* component classes — overrides @theme nowhere, just a mention */
.cfe-card { padding: 1rem; }
[data-theme=\"dark\"] { --color-surface: #111; }
@media (min-width: 1024px) { .cfe-card { padding: 2rem; } }";
        let files = vec![SourceFile {
            path: "a.poco".into(),
            // `cfe-card` is author-defined (not a utility) → no error;
            // `flex` is a real utility → emitted.
            source: r#"<div class="cfe-card flex"></div>"#.into(),
        }];
        let out = compile_project(theme, &files, CompileOptions::default());
        assert!(!out.has_errors(), "{:?}", out.diagnostics);
        // Custom rules + dark override + media query survive verbatim.
        assert!(out.css.contains(".cfe-card { padding: 1rem; }"));
        assert!(out.css.contains("[data-theme=\"dark\"]"));
        assert!(out.css.contains("@media (min-width: 1024px)"));
        // The utility still compiled.
        assert!(out.css.contains(".flex {"));
    }

    #[test]
    fn class_mention_in_comment_or_string_is_not_a_known_class() {
        // A `.flex` mentioned in a comment / string / url() must NOT be
        // registered as a component class — else the real `.flex` utility
        // is silently dropped (no rule, no error).
        let theme = "\
@theme { --color-surface: #fff; }
/* prefer .flex for layout; see .grid too */
.card { padding: 1rem; background: url(\".sprite.png\"); content: \".inline\"; }";
        let files = vec![SourceFile {
            path: "a.poco".into(),
            source: r#"<div class="flex grid inline"></div>"#.into(),
        }];
        let out = compile_project(theme, &files, CompileOptions::default());
        assert!(!out.has_errors(), "{:?}", out.diagnostics);
        // The utilities mentioned only in the comment/string still emit.
        assert!(out.css.contains(".flex {"), "flex dropped");
        assert!(out.css.contains(".grid {"), "grid dropped");
        assert!(out.css.contains(".inline {"), "inline dropped");
        // The real component class is still recognised (no "unknown utility").
        assert!(out.css.contains(".card { padding: 1rem;"));
    }

    #[test]
    fn class_defined_only_inside_at_rule_is_registered() {
        // Regression: a component class that appears *only* inside an at-rule
        // rule list (`@media`, never at the top level) must still register as
        // a known class — otherwise the compiler reports it as an unknown
        // utility. A leading banner comment must not hide the `@media` head.
        let theme = "\
@theme { --color-surface: #fff; }
/* app shell grid — responsive only */
@media (min-width: 1024px) {
  .cfe-shell { grid-template-columns: 280px minmax(0, 1fr); }
  .cfe-shell[data-detail=\"true\"] { grid-template-columns: 280px 1fr 380px; }
}";
        let files = vec![SourceFile {
            path: "a.poco".into(),
            // `cfe-shell` is author-defined inside @media → no error;
            // `flex` is a real utility → emitted.
            source: r#"<div class="cfe-shell flex"></div>"#.into(),
        }];
        let out = compile_project(theme, &files, CompileOptions::default());
        assert!(!out.has_errors(), "{:?}", out.diagnostics);
        assert!(out.css.contains(".flex {"));
        assert!(out.css.contains("@media (min-width: 1024px)"));
    }

    #[test]
    fn preflight_resets_native_form_control_background() {
        // No bg-less form control — `<button>`, `<input>`, `<select>`,
        // `<textarea>` — may fall back to the browser's native (grey) widget
        // background. Tailwind v4 resets them all to transparent, not just
        // buttons, so the reset selector must cover the whole group.
        let files = vec![SourceFile {
            path: "a.poco".into(),
            source: r#"<button class="px-3">Go</button>"#.into(),
        }];
        let out = compile_project("@theme {}", &files, CompileOptions::default());
        assert!(
            out.css.contains(
                "button, input, select, optgroup, textarea, ::file-selector-button { \
                 font: inherit; letter-spacing: inherit; color: inherit; border-radius: 0; \
                 background-color: transparent; opacity: 1; }"
            ),
            "preflight must reset every native form-control background to transparent"
        );
    }

    #[test]
    fn responsive_breakpoints_emit_in_ascending_order() {
        // Regression: `<div class="px-4 sm:px-7 lg:px-9">` must apply px-9 at
        // lg+, not px-7. Utilities are equal specificity, so the @media rules
        // have to emit after the base rule and in ascending breakpoint order
        // (sm < md < lg) — an alphabetical sort puts `lg`(l) before `sm`(s),
        // so a smaller breakpoint clobbers a larger one.
        let files = vec![SourceFile {
            path: "a.poco".into(),
            source: r#"<div class="px-4 sm:px-7 lg:px-9"></div>"#.into(),
        }];
        let out = compile_project("@theme {}", &files, CompileOptions::default());
        assert!(!out.has_errors(), "{:?}", out.diagnostics);
        let base = out.css.find(r"px-4 {").expect("base px-4 emitted");
        let sm = out.css.find(r"sm\:px-7").expect("sm:px-7 emitted");
        let lg = out.css.find(r"lg\:px-9").expect("lg:px-9 emitted");
        assert!(
            base < sm && sm < lg,
            "expected base < sm < lg emission order, got base={base} sm={sm} lg={lg}"
        );
    }

    #[test]
    fn state_attribute_variant_emits_after_hover() {
        // Regression: an active toggle styled with `data-[state=on]:bg-ink-100`
        // must keep that colour when hovered — `hover:bg-ink-10` carries equal
        // specificity, so the state rule has to appear *after* the hover rule
        // in source order (Tailwind's variant order). A plain alphabetical sort
        // puts `data-` before `hover`, letting hover clobber the active state.
        let theme =
            "@theme { --color-surface: #fff; --color-ink-10: #eee; --color-ink-100: #111; }";
        let files = vec![SourceFile {
            path: "a.poco".into(),
            source:
                r#"<button class="bg-surface hover:bg-ink-10 data-[state=on]:bg-ink-100"></button>"#
                    .into(),
        }];
        let out = compile_project(theme, &files, CompileOptions::default());
        assert!(!out.has_errors(), "{:?}", out.diagnostics);
        let hover_at = out
            .css
            .find(r"hover\:bg-ink-10")
            .expect("hover rule emitted");
        let state_at = out
            .css
            .find(r"data-\[state\=on\]\:bg-ink-100")
            .expect("state rule emitted");
        assert!(
            state_at > hover_at,
            "data-[state=on] must emit after hover so the active state wins"
        );
    }

    #[test]
    fn unterminated_theme_block_warns() {
        // Missing `}` on the @theme block — the rest is dropped, but a
        // warning must surface (not silent).
        let theme = "@theme { --color-surface: #fff;\n.card { padding: 1rem; }";
        let files = vec![SourceFile {
            path: "a.poco".into(),
            source: r#"<div class="flex"></div>"#.into(),
        }];
        let out = compile_project(theme, &files, CompileOptions::default());
        assert!(out
            .diagnostics
            .iter()
            .any(|d| d.severity == Severity::Warning && d.message.contains("unterminated")));
        // Well-formed @theme produces no such warning.
        let ok = compile_project(
            "@theme { --color-surface: #fff; }",
            &files,
            CompileOptions::default(),
        );
        assert!(!ok
            .diagnostics
            .iter()
            .any(|d| d.message.contains("unterminated")));
    }

    #[test]
    fn surfaces_unknown_token_with_file() {
        let files = vec![SourceFile {
            path: "x.poco".into(),
            source: r#"<div class="bg-ghost"></div>"#.into(),
        }];
        let out = compile_project("@theme {}", &files, CompileOptions::default());
        assert!(out.has_errors());
        assert_eq!(out.diagnostics[0].span.file, 0);
    }
}
