// @generated by tools/gen-locale-cldr.py; DO NOT EDIT.
// Source/license: ../data/cldr/README.md. Exact decimal predicates, no float rounding.
// Preserve CLDR relation grouping and modulo syntax for review against source.
#![allow(unused_parens, clippy::nonminimal_bool, clippy::manual_is_multiple_of)]
use crate::{PluralArg, PluralCategory};
pub(crate) const OTHER_RULE: u8 = 7;
pub(crate) fn category(rule: u8, a: PluralArg) -> PluralCategory {
    match rule {
        0 => {
            if (a.f == 0 && (a.i == 1)) {
                return PluralCategory::One;
            }
            PluralCategory::Other
        }
        1 => {
            if (a.f == 0 && ((0..=1).contains(&a.i))) {
                return PluralCategory::One;
            }
            PluralCategory::Other
        }
        2 => {
            if (a.i == 0) || (a.f == 0 && (a.i == 1)) {
                return PluralCategory::One;
            }
            PluralCategory::Other
        }
        3 => {
            if (a.f == 0 && (a.i == 0)) {
                return PluralCategory::Zero;
            }
            if (a.f == 0 && (a.i == 1)) {
                return PluralCategory::One;
            }
            if (a.f == 0 && (a.i == 2)) {
                return PluralCategory::Two;
            }
            if (a.f == 0 && ((3..=10).contains(&(a.i % 100)))) {
                return PluralCategory::Few;
            }
            if (a.f == 0 && ((11..=99).contains(&(a.i % 100)))) {
                return PluralCategory::Many;
            }
            PluralCategory::Other
        }
        4 => {
            if ((a.i == 1) && (u64::from(a.v) == 0)) {
                return PluralCategory::One;
            }
            PluralCategory::Other
        }
        5 => {
            if ((a.f == 0 && ((a.i % 10) == 1)) && !(a.f == 0 && ((a.i % 100) == 11))) {
                return PluralCategory::One;
            }
            if ((a.f == 0 && ((2..=4).contains(&(a.i % 10))))
                && !(a.f == 0 && ((12..=14).contains(&(a.i % 100)))))
            {
                return PluralCategory::Few;
            }
            if (a.f == 0 && ((a.i % 10) == 0))
                || (a.f == 0 && ((5..=9).contains(&(a.i % 10))))
                || (a.f == 0 && ((11..=14).contains(&(a.i % 100))))
            {
                return PluralCategory::Many;
            }
            PluralCategory::Other
        }
        6 => {
            if (a.f == 0 && (a.i == 0)) {
                return PluralCategory::Zero;
            }
            if (a.f == 0 && (a.i == 1)) {
                return PluralCategory::One;
            }
            PluralCategory::Other
        }
        7 => PluralCategory::Other,
        8 => {
            if ((a.f == 0 && ((a.i % 10) == 1))
                && !(a.f == 0 && ((a.i % 100) == 11 || (a.i % 100) == 71 || (a.i % 100) == 91)))
            {
                return PluralCategory::One;
            }
            if ((a.f == 0 && ((a.i % 10) == 2))
                && !(a.f == 0 && ((a.i % 100) == 12 || (a.i % 100) == 72 || (a.i % 100) == 92)))
            {
                return PluralCategory::Two;
            }
            if ((a.f == 0 && ((3..=4).contains(&(a.i % 10)) || (a.i % 10) == 9))
                && !(a.f == 0
                    && ((10..=19).contains(&(a.i % 100))
                        || (70..=79).contains(&(a.i % 100))
                        || (90..=99).contains(&(a.i % 100)))))
            {
                return PluralCategory::Few;
            }
            if (!(a.f == 0 && (a.i == 0)) && (a.f == 0 && ((a.i % 1000000) == 0))) {
                return PluralCategory::Many;
            }
            PluralCategory::Other
        }
        9 => {
            if ((u64::from(a.v) == 0) && ((a.i % 10) == 1) && !((a.i % 100) == 11))
                || (((a.f % 10) == 1) && !((a.f % 100) == 11))
            {
                return PluralCategory::One;
            }
            if ((u64::from(a.v) == 0)
                && ((2..=4).contains(&(a.i % 10)))
                && !((12..=14).contains(&(a.i % 100))))
                || (((2..=4).contains(&(a.f % 10))) && !((12..=14).contains(&(a.f % 100))))
            {
                return PluralCategory::Few;
            }
            PluralCategory::Other
        }
        10 => {
            if ((a.i == 1) && (u64::from(a.v) == 0)) {
                return PluralCategory::One;
            }
            if (!(a.i == 0) && ((a.i % 1000000) == 0) && (u64::from(a.v) == 0)) {
                return PluralCategory::Many;
            }
            PluralCategory::Other
        }
        11 => {
            if ((u64::from(a.v) == 0) && (a.i == 1 || a.i == 2 || a.i == 3))
                || ((u64::from(a.v) == 0)
                    && !((a.i % 10) == 4 || (a.i % 10) == 6 || (a.i % 10) == 9))
                || (!(u64::from(a.v) == 0)
                    && !((a.f % 10) == 4 || (a.f % 10) == 6 || (a.f % 10) == 9))
            {
                return PluralCategory::One;
            }
            PluralCategory::Other
        }
        12 => {
            if ((a.i == 1) && (u64::from(a.v) == 0)) {
                return PluralCategory::One;
            }
            if (((2..=4).contains(&a.i)) && (u64::from(a.v) == 0)) {
                return PluralCategory::Few;
            }
            if (!(u64::from(a.v) == 0)) {
                return PluralCategory::Many;
            }
            PluralCategory::Other
        }
        13 => {
            if (a.f == 0 && (a.i == 0)) {
                return PluralCategory::Zero;
            }
            if (a.f == 0 && (a.i == 1)) {
                return PluralCategory::One;
            }
            if (a.f == 0 && (a.i == 2)) {
                return PluralCategory::Two;
            }
            if (a.f == 0 && (a.i == 3)) {
                return PluralCategory::Few;
            }
            if (a.f == 0 && (a.i == 6)) {
                return PluralCategory::Many;
            }
            PluralCategory::Other
        }
        14 => {
            if (a.f == 0 && (a.i == 1)) || (!(a.t() == 0) && (a.i == 0 || a.i == 1)) {
                return PluralCategory::One;
            }
            PluralCategory::Other
        }
        15 => {
            if ((u64::from(a.v) == 0) && ((a.i % 100) == 1)) || ((a.f % 100) == 1) {
                return PluralCategory::One;
            }
            if ((u64::from(a.v) == 0) && ((a.i % 100) == 2)) || ((a.f % 100) == 2) {
                return PluralCategory::Two;
            }
            if ((u64::from(a.v) == 0) && ((3..=4).contains(&(a.i % 100))))
                || ((3..=4).contains(&(a.f % 100)))
            {
                return PluralCategory::Few;
            }
            PluralCategory::Other
        }
        16 => {
            if (a.f == 0 && (a.i == 1)) {
                return PluralCategory::One;
            }
            if (!(a.i == 0) && ((a.i % 1000000) == 0) && (u64::from(a.v) == 0)) {
                return PluralCategory::Many;
            }
            PluralCategory::Other
        }
        17 => {
            if (a.i == 0 || a.i == 1) {
                return PluralCategory::One;
            }
            PluralCategory::Other
        }
        18 => {
            if (a.i == 0 || a.i == 1) {
                return PluralCategory::One;
            }
            if (!(a.i == 0) && ((a.i % 1000000) == 0) && (u64::from(a.v) == 0)) {
                return PluralCategory::Many;
            }
            PluralCategory::Other
        }
        19 => {
            if (a.f == 0 && (a.i == 1)) {
                return PluralCategory::One;
            }
            if (a.f == 0 && (a.i == 2)) {
                return PluralCategory::Two;
            }
            if (a.f == 0 && ((3..=6).contains(&a.i))) {
                return PluralCategory::Few;
            }
            if (a.f == 0 && ((7..=10).contains(&a.i))) {
                return PluralCategory::Many;
            }
            PluralCategory::Other
        }
        20 => {
            if (a.f == 0 && (a.i == 1 || a.i == 11)) {
                return PluralCategory::One;
            }
            if (a.f == 0 && (a.i == 2 || a.i == 12)) {
                return PluralCategory::Two;
            }
            if (a.f == 0 && ((3..=10).contains(&a.i) || (13..=19).contains(&a.i))) {
                return PluralCategory::Few;
            }
            PluralCategory::Other
        }
        21 => {
            if ((u64::from(a.v) == 0) && ((a.i % 10) == 1)) {
                return PluralCategory::One;
            }
            if ((u64::from(a.v) == 0) && ((a.i % 10) == 2)) {
                return PluralCategory::Two;
            }
            if ((u64::from(a.v) == 0)
                && ((a.i % 100) == 0
                    || (a.i % 100) == 20
                    || (a.i % 100) == 40
                    || (a.i % 100) == 60
                    || (a.i % 100) == 80))
            {
                return PluralCategory::Few;
            }
            if (!(u64::from(a.v) == 0)) {
                return PluralCategory::Many;
            }
            PluralCategory::Other
        }
        22 => {
            if ((a.i == 1) && (u64::from(a.v) == 0)) || ((a.i == 0) && !(u64::from(a.v) == 0)) {
                return PluralCategory::One;
            }
            if ((a.i == 2) && (u64::from(a.v) == 0)) {
                return PluralCategory::Two;
            }
            PluralCategory::Other
        }
        23 => {
            if ((a.t() == 0) && ((a.i % 10) == 1) && !((a.i % 100) == 11))
                || (((a.t() % 10) == 1) && !((a.t() % 100) == 11))
            {
                return PluralCategory::One;
            }
            PluralCategory::Other
        }
        24 => {
            if (a.f == 0 && (a.i == 1)) {
                return PluralCategory::One;
            }
            if (a.f == 0 && (a.i == 2)) {
                return PluralCategory::Two;
            }
            PluralCategory::Other
        }
        25 => {
            if (a.f == 0 && (a.i == 0)) {
                return PluralCategory::Zero;
            }
            if (a.f == 0 && (a.i == 1)) {
                return PluralCategory::One;
            }
            if (a.f == 0
                && ((a.i % 100) == 2
                    || (a.i % 100) == 22
                    || (a.i % 100) == 42
                    || (a.i % 100) == 62
                    || (a.i % 100) == 82))
                || ((a.f == 0 && ((a.i % 1000) == 0))
                    && (a.f == 0
                        && ((1000..=20000).contains(&(a.i % 100000))
                            || (a.i % 100000) == 40000
                            || (a.i % 100000) == 60000
                            || (a.i % 100000) == 80000)))
                || (!(a.f == 0 && (a.i == 0)) && (a.f == 0 && ((a.i % 1000000) == 100000)))
            {
                return PluralCategory::Two;
            }
            if (a.f == 0
                && ((a.i % 100) == 3
                    || (a.i % 100) == 23
                    || (a.i % 100) == 43
                    || (a.i % 100) == 63
                    || (a.i % 100) == 83))
            {
                return PluralCategory::Few;
            }
            if (!(a.f == 0 && (a.i == 1))
                && (a.f == 0
                    && ((a.i % 100) == 1
                        || (a.i % 100) == 21
                        || (a.i % 100) == 41
                        || (a.i % 100) == 61
                        || (a.i % 100) == 81)))
            {
                return PluralCategory::Many;
            }
            PluralCategory::Other
        }
        26 => {
            if (a.f == 0 && (a.i == 0)) {
                return PluralCategory::Zero;
            }
            if ((a.i == 0 || a.i == 1) && !(a.f == 0 && (a.i == 0))) {
                return PluralCategory::One;
            }
            PluralCategory::Other
        }
        27 => {
            if ((a.f == 0 && ((a.i % 10) == 1))
                && !(a.f == 0 && ((11..=19).contains(&(a.i % 100)))))
            {
                return PluralCategory::One;
            }
            if ((a.f == 0 && ((2..=9).contains(&(a.i % 10))))
                && !(a.f == 0 && ((11..=19).contains(&(a.i % 100)))))
            {
                return PluralCategory::Few;
            }
            if (!(a.f == 0)) {
                return PluralCategory::Many;
            }
            PluralCategory::Other
        }
        28 => {
            if (a.f == 0 && ((a.i % 10) == 0))
                || (a.f == 0 && ((11..=19).contains(&(a.i % 100))))
                || ((u64::from(a.v) == 2) && ((11..=19).contains(&(a.f % 100))))
            {
                return PluralCategory::Zero;
            }
            if ((a.f == 0 && ((a.i % 10) == 1)) && !(a.f == 0 && ((a.i % 100) == 11)))
                || ((u64::from(a.v) == 2) && ((a.f % 10) == 1) && !((a.f % 100) == 11))
                || (!(u64::from(a.v) == 2) && ((a.f % 10) == 1))
            {
                return PluralCategory::One;
            }
            PluralCategory::Other
        }
        29 => {
            if ((u64::from(a.v) == 0) && ((a.i % 10) == 1) && !((a.i % 100) == 11))
                || (((a.f % 10) == 1) && !((a.f % 100) == 11))
            {
                return PluralCategory::One;
            }
            PluralCategory::Other
        }
        30 => {
            if ((a.i == 1) && (u64::from(a.v) == 0)) {
                return PluralCategory::One;
            }
            if (!(u64::from(a.v) == 0))
                || (a.f == 0 && (a.i == 0))
                || (!(a.f == 0 && (a.i == 1)) && (a.f == 0 && ((1..=19).contains(&(a.i % 100)))))
            {
                return PluralCategory::Few;
            }
            PluralCategory::Other
        }
        31 => {
            if (a.f == 0 && (a.i == 1)) {
                return PluralCategory::One;
            }
            if (a.f == 0 && (a.i == 2)) {
                return PluralCategory::Two;
            }
            if (a.f == 0 && (a.i == 0)) || (a.f == 0 && ((3..=10).contains(&(a.i % 100)))) {
                return PluralCategory::Few;
            }
            if (a.f == 0 && ((11..=19).contains(&(a.i % 100)))) {
                return PluralCategory::Many;
            }
            PluralCategory::Other
        }
        32 => {
            if ((a.i == 1) && (u64::from(a.v) == 0)) {
                return PluralCategory::One;
            }
            if ((u64::from(a.v) == 0)
                && ((2..=4).contains(&(a.i % 10)))
                && !((12..=14).contains(&(a.i % 100))))
            {
                return PluralCategory::Few;
            }
            if ((u64::from(a.v) == 0) && !(a.i == 1) && ((0..=1).contains(&(a.i % 10))))
                || ((u64::from(a.v) == 0) && ((5..=9).contains(&(a.i % 10))))
                || ((u64::from(a.v) == 0) && ((12..=14).contains(&(a.i % 100))))
            {
                return PluralCategory::Many;
            }
            PluralCategory::Other
        }
        33 => {
            if ((0..=1).contains(&a.i)) {
                return PluralCategory::One;
            }
            if (!(a.i == 0) && ((a.i % 1000000) == 0) && (u64::from(a.v) == 0)) {
                return PluralCategory::Many;
            }
            PluralCategory::Other
        }
        34 => {
            if ((u64::from(a.v) == 0) && ((a.i % 10) == 1) && !((a.i % 100) == 11)) {
                return PluralCategory::One;
            }
            if ((u64::from(a.v) == 0)
                && ((2..=4).contains(&(a.i % 10)))
                && !((12..=14).contains(&(a.i % 100))))
            {
                return PluralCategory::Few;
            }
            if ((u64::from(a.v) == 0) && ((a.i % 10) == 0))
                || ((u64::from(a.v) == 0) && ((5..=9).contains(&(a.i % 10))))
                || ((u64::from(a.v) == 0) && ((11..=14).contains(&(a.i % 100))))
            {
                return PluralCategory::Many;
            }
            PluralCategory::Other
        }
        35 => {
            if ((a.f == 0 && ((a.i % 10) == 1)) && !(a.f == 0 && ((a.i % 100) == 11))) {
                return PluralCategory::One;
            }
            if (a.f == 0 && (a.i == 2)) {
                return PluralCategory::Two;
            }
            if (!(a.f == 0 && (a.i == 2))
                && (a.f == 0 && ((2..=9).contains(&(a.i % 10))))
                && !(a.f == 0 && ((11..=19).contains(&(a.i % 100)))))
            {
                return PluralCategory::Few;
            }
            if (!(a.f == 0)) {
                return PluralCategory::Many;
            }
            PluralCategory::Other
        }
        36 => {
            if (a.i == 0) || (a.f == 0 && (a.i == 1)) {
                return PluralCategory::One;
            }
            if (a.f == 0 && ((2..=10).contains(&a.i))) {
                return PluralCategory::Few;
            }
            PluralCategory::Other
        }
        37 => {
            if (a.f == 0 && (a.i == 0 || a.i == 1)) || ((a.i == 0) && (a.f == 1)) {
                return PluralCategory::One;
            }
            PluralCategory::Other
        }
        38 => {
            if ((u64::from(a.v) == 0) && ((a.i % 100) == 1)) {
                return PluralCategory::One;
            }
            if ((u64::from(a.v) == 0) && ((a.i % 100) == 2)) {
                return PluralCategory::Two;
            }
            if ((u64::from(a.v) == 0) && ((3..=4).contains(&(a.i % 100))))
                || (!(u64::from(a.v) == 0))
            {
                return PluralCategory::Few;
            }
            PluralCategory::Other
        }
        39 => {
            if (a.f == 0 && ((0..=1).contains(&a.i))) || (a.f == 0 && ((11..=99).contains(&a.i))) {
                return PluralCategory::One;
            }
            PluralCategory::Other
        }
        _ => PluralCategory::Other,
    }
}
pub(crate) fn rule_for_tag(tag: &str) -> Option<u8> {
    match tag {
        "af" | "an" | "asa" | "az" | "bal" | "bem" | "bez" | "bg" | "brx" | "ce" | "cgg"
        | "chr" | "ckb" | "dv" | "ee" | "el" | "eo" | "eu" | "fo" | "fur" | "gsw" | "ha"
        | "haw" | "hu" | "jgo" | "jmc" | "ka" | "kaj" | "kcg" | "kk" | "kkj" | "kl" | "ks"
        | "ksb" | "ku" | "ky" | "lb" | "lg" | "mas" | "mgo" | "ml" | "mn" | "mr" | "nah" | "nb"
        | "nd" | "ne" | "nn" | "nnh" | "no" | "nr" | "ny" | "nyn" | "om" | "or" | "os" | "pap"
        | "ps" | "rm" | "rof" | "rwk" | "saq" | "sd" | "sdh" | "seh" | "sn" | "so" | "sq"
        | "ss" | "ssy" | "st" | "syr" | "ta" | "te" | "teo" | "tig" | "tk" | "tn" | "tr" | "ts"
        | "ug" | "uz" | "ve" | "vo" | "vun" | "wae" | "xh" | "xog" => Some(0),
        "ak" | "bho" | "csw" | "guw" | "ln" | "mg" | "nso" | "pa" | "ti" | "wa" => Some(1),
        "am" | "as" | "bn" | "doi" | "fa" | "gu" | "hi" | "kn" | "kok" | "kok-Latn" | "pcm"
        | "zu" => Some(2),
        "ar" | "ars" => Some(3),
        "ast" | "de" | "en" | "et" | "fi" | "fy" | "gl" | "ia" | "ie" | "io" | "lij" | "nl"
        | "sc" | "sv" | "sw" | "ur" | "yi" => Some(4),
        "be" => Some(5),
        "blo" | "cv" | "ksh" => Some(6),
        "bm" | "bo" | "dz" | "hnj" | "id" | "ig" | "ii" | "ja" | "jbo" | "jv" | "jw" | "kde"
        | "kea" | "km" | "ko" | "lkt" | "lo" | "ms" | "my" | "nqo" | "osa" | "sah" | "ses"
        | "sg" | "su" | "th" | "to" | "tpi" | "und" | "vi" | "wo" | "yo" | "yue" | "zh" => Some(7),
        "br" => Some(8),
        "bs" | "hr" | "sh" | "sr" => Some(9),
        "ca" | "it" | "lld" | "pt-PT" | "scn" | "vec" => Some(10),
        "ceb" | "fil" | "tl" => Some(11),
        "cs" | "sk" => Some(12),
        "cy" => Some(13),
        "da" => Some(14),
        "dsb" | "hsb" => Some(15),
        "es" => Some(16),
        "ff" | "hy" | "kab" => Some(17),
        "fr" => Some(18),
        "ga" => Some(19),
        "gd" => Some(20),
        "gv" => Some(21),
        "he" => Some(22),
        "is" => Some(23),
        "iu" | "naq" | "sat" | "se" | "sma" | "smi" | "smj" | "smn" | "sms" => Some(24),
        "kw" => Some(25),
        "lag" => Some(26),
        "lt" => Some(27),
        "lv" | "prg" => Some(28),
        "mk" => Some(29),
        "mo" | "ro" => Some(30),
        "mt" => Some(31),
        "pl" => Some(32),
        "pt" => Some(33),
        "ru" | "uk" => Some(34),
        "sgs" => Some(35),
        "shi" => Some(36),
        "si" => Some(37),
        "sl" => Some(38),
        "tzm" => Some(39),
        _ => None,
    }
}
pub(crate) fn parent(tag: &str) -> Option<&'static str> {
    match tag {
        "en-150" | "en-AG" | "en-AI" | "en-AU" | "en-BB" | "en-BM" | "en-BS" | "en-BW"
        | "en-BZ" | "en-CC" | "en-CK" | "en-CM" | "en-CX" | "en-CY" | "en-DG" | "en-DM"
        | "en-ER" | "en-FJ" | "en-FK" | "en-FM" | "en-GB" | "en-GD" | "en-GG" | "en-GH"
        | "en-GI" | "en-GM" | "en-GS" | "en-GY" | "en-HK" | "en-ID" | "en-IE" | "en-IL"
        | "en-IM" | "en-IN" | "en-IO" | "en-JE" | "en-JM" | "en-KE" | "en-KI" | "en-KN"
        | "en-KY" | "en-LC" | "en-LR" | "en-LS" | "en-MG" | "en-MO" | "en-MS" | "en-MT"
        | "en-MU" | "en-MV" | "en-MW" | "en-MY" | "en-NA" | "en-NF" | "en-NG" | "en-NR"
        | "en-NU" | "en-NZ" | "en-PG" | "en-PK" | "en-PN" | "en-PW" | "en-RW" | "en-SB"
        | "en-SC" | "en-SD" | "en-SG" | "en-SH" | "en-SL" | "en-SS" | "en-SX" | "en-SZ"
        | "en-TC" | "en-TK" | "en-TO" | "en-TT" | "en-TV" | "en-TZ" | "en-UG" | "en-VC"
        | "en-VG" | "en-VU" | "en-WS" | "en-ZA" | "en-ZM" | "en-ZW" => Some("en-001"),
        "en-AT" | "en-BE" | "en-CH" | "en-CZ" | "en-DE" | "en-DK" | "en-EE" | "en-ES" | "en-FI"
        | "en-FR" | "en-GE" | "en-HU" | "en-IT" | "en-LT" | "en-LV" | "en-NL" | "en-NO"
        | "en-PL" | "en-PT" | "en-RO" | "en-SE" | "en-SI" | "en-SK" | "en-UA" => Some("en-150"),
        "hi-Latn" => Some("en-IN"),
        "es-AR" | "es-BO" | "es-BR" | "es-BZ" | "es-CL" | "es-CO" | "es-CR" | "es-CU" | "es-DO"
        | "es-EC" | "es-GT" | "es-HN" | "es-JP" | "es-MX" | "es-NI" | "es-PA" | "es-PE"
        | "es-PR" | "es-PY" | "es-SV" | "es-US" | "es-UY" | "es-VE" => Some("es-419"),
        "ht" => Some("fr-HT"),
        "nb" | "nn" | "no-NO" => Some("no"),
        "pt-AO" | "pt-CH" | "pt-CV" | "pt-FR" | "pt-GQ" | "pt-GW" | "pt-LU" | "pt-MO" | "pt-MZ"
        | "pt-ST" | "pt-TL" => Some("pt-PT"),
        "az-Arab" | "az-Cyrl" | "bal-Latn" | "blt-Latn" | "bm-Nkoo" | "bs-Cyrl" | "byn-Latn"
        | "cu-Glag" | "dje-Arab" | "dyo-Arab" | "en-Dsrt" | "en-Shaw" | "ff-Adlm" | "ff-Arab"
        | "ha-Arab" | "iu-Latn" | "kaa-Latn" | "kk-Arab" | "kok-Latn" | "ks-Deva" | "ku-Arab"
        | "kxv-Deva" | "kxv-Orya" | "kxv-Telu" | "ky-Arab" | "ky-Latn" | "ml-Arab" | "mn-Mong"
        | "mni-Mtei" | "ms-Arab" | "pa-Arab" | "sat-Deva" | "sd-Deva" | "sd-Khoj" | "sd-Sind"
        | "shi-Latn" | "so-Arab" | "sr-Latn" | "suz-Sunu" | "sw-Arab" | "tg-Arab" | "ug-Cyrl"
        | "uz-Arab" | "uz-Cyrl" | "vai-Latn" | "wo-Arab" | "yo-Arab" | "yue-Hans" | "zh-Hant" => {
            Some("und")
        }
        "zh-Hant-MO" => Some("zh-Hant-HK"),
        _ => None,
    }
}
