//! Coverage oracle: what fraction of Tailwind's own class-candidate
//! corpus Pine Stylekit resolves to CSS (RFC 092 D3).
//!
//! Pine Stylekit is "shaped, not byte-compatible" — it is an
//! inventory-driven *subset* of Tailwind, so this is NOT an output
//! oracle. The corpus is the *positive* slice only (candidates that
//! appear in a test's expected CSS snapshot — Tailwind's own negative
//! cases like `float-left/foo` and invalid negations are excluded), so
//! the rate is a real signal: the fraction of genuinely-emitted Tailwind
//! candidates Stylekit resolves. It still sits below per-family coverage
//! (reported into the living GitHub issue) because Tailwind's positive
//! set includes the full arbitrary-value matrix and exotic permutations
//! a subset doesn't chase.
//!
//! What this test IS: a **regression floor**. If a refactor breaks a
//! family or the resolver, the rate drops below the floor and trips. It
//! is not a 100% parity target.
//!
//! The corpus is the *positive* slice of Tailwind's candidates (the
//! forms Tailwind emits CSS for — negative cases that emit nothing are
//! excluded), regenerated by `scripts/check-tailwind-conformance.mjs`.
//!
//! Env hooks (used by that script):
//! - `STYLEKIT_CORPUS=<path>` — probe an external candidate file instead
//!   of the baked-in fixture. In this mode the floor is NOT asserted
//!   (it's a probe of an arbitrary Tailwind version, not the pinned
//!   regression guard).
//! - `STYLEKIT_CONFORMANCE_REPORT=<path>` — dump the unresolved
//!   candidates (one per line), so the script can compute per-family
//!   coverage (a family is covered iff ≥1 of its candidates resolves).

use std::collections::BTreeSet;

use pocopine_stylekit::{compile_project, CompileOptions, Severity, SourceFile};

const BAKED_CORPUS: &str = include_str!("fixtures/tailwind-positive.txt");

/// A theme exercising the token-driven families so candidates that
/// reference theme tokens (`bg-surface`, `text-ink-50`, …) can resolve.
/// Tailwind's own palette (`bg-red-500`) resolves via Stylekit's builtin
/// default palette, so most colour candidates work without theme entries.
const THEME: &str = "@theme {\n  --color-surface: #fff;\n  --color-ink-50: #18171a;\n  --color-line: #e5e5e5;\n  --color-accent: #2563eb;\n  --spacing: 0.25rem;\n}";

fn parse_corpus(text: &str) -> Vec<String> {
    text.lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .map(|l| l.to_string())
        .collect()
}

/// A candidate resolves iff compiling a one-class document yields no
/// error diagnostics.
fn resolves(class: &str) -> bool {
    // Single-quote the attribute so candidates containing `"` (e.g.
    // `content-["hello"]`, `font-features-["smcp"]`) don't terminate it.
    let files = vec![SourceFile {
        path: "conformance.poco".into(),
        source: format!("<div class='{class}'></div>"),
    }];
    let out = compile_project(THEME, &files, CompileOptions::default());
    // A candidate counts as covered if it compiles cleanly, OR the only
    // errors are "undefined token" — Stylekit *recognises* the utility
    // and would emit it once the token exists (e.g. `divide-best-blue`,
    // `bg-shadowned` reference tokens these Tailwind tests define). That
    // is a missing token, not a missing utility.
    let mut errors = out
        .diagnostics
        .iter()
        .filter(|d| d.severity == Severity::Error)
        .peekable();
    errors.peek().is_none() || errors.all(|d| d.message.contains("is not a defined token"))
}

#[test]
fn resolve_rate_over_tailwind_corpus() {
    // Probe an external corpus when asked (the conformance script points
    // this at the freshly-downloaded Tailwind version); else the pinned
    // fixture.
    let external = std::env::var("STYLEKIT_CORPUS")
        .ok()
        .map(|p| std::fs::read_to_string(p).expect("STYLEKIT_CORPUS unreadable"));
    let probing = external.is_some();
    let all = parse_corpus(external.as_deref().unwrap_or(BAKED_CORPUS));
    let total = all.len();
    assert!(total > 1000, "corpus looks too small — regenerate it");

    let mut unresolved = BTreeSet::new();
    for class in &all {
        if !resolves(class) {
            unresolved.insert(class.clone());
        }
    }
    let resolved = total - unresolved.len();
    let rate = resolved as f64 / total as f64;

    // Machine-readable dump for the conformance script (per-family
    // coverage + report).
    if let Ok(path) = std::env::var("STYLEKIT_CONFORMANCE_REPORT") {
        let body = unresolved.iter().cloned().collect::<Vec<_>>().join("\n");
        let _ = std::fs::write(
            &path,
            format!(
                "# resolved {resolved}/{total} ({:.1}%)\n{body}\n",
                rate * 100.0
            ),
        );
    }

    eprintln!(
        "tailwind corpus: resolved {resolved}/{total} ({:.1}%); {} unresolved",
        rate * 100.0,
        unresolved.len()
    );

    // Regression floor — set below the live rate (~82% over the clean
    // positive corpus) with headroom for corpus churn. It trips on a
    // family/resolver regression, not on normal subset gaps. Not asserted
    // when probing an external corpus (a coverage snapshot, not the guard).
    if !probing {
        assert!(
            rate >= 0.75,
            "Tailwind-corpus resolve rate {:.1}% fell below the 75% floor \
             ({resolved}/{total}). A family or the resolver likely regressed.",
            rate * 100.0
        );
    }
}
