//! Grammar oracle: run Pine Stylekit's class parser over Tailwind's own
//! class-candidate corpus (RFC 092 D3).
//!
//! We do not promise byte-compatible CSS ("shaped, not compatible"), so
//! this is a *grammar* oracle, not an output oracle:
//!
//! 1. `parse_class` must never panic on any real-world candidate —
//!    including Tailwind's exotic forms (`*:flex`, `**/foo:flex`,
//!    `--@container`, negatives, arbitrary properties).
//! 2. A curated, representative slice must split into exactly the
//!    variants / base / arbitrary we expect.
//!
//! The corpus is regenerated by `scripts/extract-tailwind-candidates.mjs`
//! from the (git-ignored) `tmp/tailwind` clone and committed, so this
//! test is reproducible without the clone.

use std::panic::catch_unwind;

use pocopine_stylekit::parse::{Variant, parse_class};

const CORPUS: &str = include_str!("fixtures/tailwind-candidates.txt");

fn candidates() -> impl Iterator<Item = &'static str> {
    CORPUS
        .lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
}

#[test]
fn parser_never_panics_on_tailwind_corpus() {
    let mut panicked = Vec::new();
    for class in candidates() {
        // Silence the default panic hook noise; we report our own list.
        let prev = std::panic::take_hook();
        std::panic::set_hook(Box::new(|_| {}));
        let ok = catch_unwind(|| {
            let _ = parse_class(class);
        })
        .is_ok();
        std::panic::set_hook(prev);
        if !ok {
            panicked.push(class);
        }
    }
    assert!(
        panicked.is_empty(),
        "parse_class panicked on {} Tailwind candidate(s): {:?}",
        panicked.len(),
        &panicked[..panicked.len().min(20)]
    );
}

#[test]
fn corpus_is_substantial() {
    // Guard against an empty/broken regeneration silently passing the
    // panic test.
    assert!(
        candidates().count() > 1000,
        "corpus looks too small — regenerate the fixture"
    );
}

#[test]
fn representative_split() {
    let cases: &[(&str, &[&str], &str, Option<&str>)] = &[
        ("flex", &[], "flex", None),
        ("items-center", &[], "items-center", None),
        ("hover:bg-surface", &["hover"], "bg-surface", None),
        ("focus-visible:ring-2", &["focus-visible"], "ring-2", None),
        ("md:grid-cols-3", &["md"], "grid-cols-3", None),
        ("text-[13px]", &[], "text", Some("13px")),
        ("w-[calc(100%-2rem)]", &[], "w", Some("calc(100%-2rem)")),
        (
            "grid-cols-[minmax(0,1fr)_80px]",
            &[],
            "grid-cols",
            Some("minmax(0,1fr)_80px"),
        ),
        (
            "data-[state=on]:bg-accent",
            &["data-[state=on]"],
            "bg-accent",
            None,
        ),
        (
            "sm:hover:text-ink-50",
            &["sm", "hover"],
            "text-ink-50",
            None,
        ),
    ];

    for (input, variants, base, arbitrary) in cases {
        let parsed =
            parse_class(input).unwrap_or_else(|d| panic!("`{input}` failed to parse: {d:?}"));
        let expected: Vec<Variant> = variants.iter().map(|v| Variant((*v).to_string())).collect();
        assert_eq!(&parsed.variants, &expected, "variants for `{input}`");
        assert_eq!(parsed.base, *base, "base for `{input}`");
        assert_eq!(
            parsed.arbitrary.as_deref(),
            *arbitrary,
            "arbitrary for `{input}`"
        );
    }
}
