// @generated by gen-model-catalog from LiteLLM's
// model_prices_and_context_window.json. DO NOT EDIT — regenerate via
// `cargo run -p gen-model-catalog`. Source: github.com/BerriAI/litellm (MIT).

use super::catalog::{Model, ModelPricing};

/// Models derived from the upstream LiteLLM price/capability data. Each `id`
/// references the matching `models::*` const, so the alias lives in one place.
#[rustfmt::skip]
pub(super) fn generated() -> Vec<Model> {
    vec![
        Model { id: models::anthropic::CLAUDE_3_7_SONNET_20250219, context_window: 200000, max_output: 64000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 3.0, output: 15.0, cache_read: 0.3, cache_creation: 3.75 } },
        Model { id: models::anthropic::CLAUDE_3_HAIKU_20240307, context_window: 200000, max_output: 4096, reasoning: false, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: true, pricing: ModelPricing { input: 0.25, output: 1.25, cache_read: 0.03, cache_creation: 0.3 } },
        Model { id: models::anthropic::CLAUDE_3_OPUS_20240229, context_window: 200000, max_output: 4096, reasoning: false, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: true, pricing: ModelPricing { input: 15.0, output: 75.0, cache_read: 1.5, cache_creation: 18.75 } },
        Model { id: models::anthropic::CLAUDE_4_OPUS_20250514, context_window: 200000, max_output: 32000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 15.0, output: 75.0, cache_read: 1.5, cache_creation: 18.75 } },
        Model { id: models::anthropic::CLAUDE_4_SONNET_20250514, context_window: 1000000, max_output: 64000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 3.0, output: 15.0, cache_read: 0.3, cache_creation: 3.75 } },
        Model { id: models::anthropic::CLAUDE_FABLE_5, context_window: 1000000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 10.0, output: 50.0, cache_read: 1.0, cache_creation: 12.5 } },
        Model { id: models::anthropic::CLAUDE_HAIKU_4_5, context_window: 200000, max_output: 64000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 1.0, output: 5.0, cache_read: 0.1, cache_creation: 1.25 } },
        Model { id: models::anthropic::CLAUDE_HAIKU_4_5_20251001, context_window: 200000, max_output: 64000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 1.0, output: 5.0, cache_read: 0.1, cache_creation: 1.25 } },
        Model { id: models::anthropic::CLAUDE_MYTHOS_5, context_window: 1000000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 10.0, output: 50.0, cache_read: 1.0, cache_creation: 12.5 } },
        Model { id: models::anthropic::CLAUDE_MYTHOS_PREVIEW, context_window: 1000000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 10.0, output: 50.0, cache_read: 1.0, cache_creation: 12.5 } },
        Model { id: models::anthropic::CLAUDE_OPUS_4_1, context_window: 200000, max_output: 32000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 15.0, output: 75.0, cache_read: 1.5, cache_creation: 18.75 } },
        Model { id: models::anthropic::CLAUDE_OPUS_4_1_20250805, context_window: 200000, max_output: 32000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 15.0, output: 75.0, cache_read: 1.5, cache_creation: 18.75 } },
        Model { id: models::anthropic::CLAUDE_OPUS_4_20250514, context_window: 200000, max_output: 32000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 15.0, output: 75.0, cache_read: 1.5, cache_creation: 18.75 } },
        Model { id: models::anthropic::CLAUDE_OPUS_4_5, context_window: 200000, max_output: 64000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 5.0, output: 25.0, cache_read: 0.5, cache_creation: 6.25 } },
        Model { id: models::anthropic::CLAUDE_OPUS_4_5_20251101, context_window: 200000, max_output: 64000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 5.0, output: 25.0, cache_read: 0.5, cache_creation: 6.25 } },
        Model { id: models::anthropic::CLAUDE_OPUS_4_6, context_window: 1000000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 5.0, output: 25.0, cache_read: 0.5, cache_creation: 6.25 } },
        Model { id: models::anthropic::CLAUDE_OPUS_4_6_20260205, context_window: 1000000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 5.0, output: 25.0, cache_read: 0.5, cache_creation: 6.25 } },
        Model { id: models::anthropic::CLAUDE_OPUS_4_7, context_window: 1000000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 5.0, output: 25.0, cache_read: 0.5, cache_creation: 6.25 } },
        Model { id: models::anthropic::CLAUDE_OPUS_4_7_20260416, context_window: 1000000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 5.0, output: 25.0, cache_read: 0.5, cache_creation: 6.25 } },
        Model { id: models::anthropic::CLAUDE_OPUS_4_8, context_window: 1000000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 5.0, output: 25.0, cache_read: 0.5, cache_creation: 6.25 } },
        Model { id: models::anthropic::CLAUDE_OPUS_5, context_window: 1000000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 5.0, output: 25.0, cache_read: 0.5, cache_creation: 6.25 } },
        Model { id: models::anthropic::CLAUDE_SONNET_4_20250514, context_window: 1000000, max_output: 64000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 3.0, output: 15.0, cache_read: 0.3, cache_creation: 3.75 } },
        Model { id: models::anthropic::CLAUDE_SONNET_4_5, context_window: 200000, max_output: 64000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 3.0, output: 15.0, cache_read: 0.3, cache_creation: 3.75 } },
        Model { id: models::anthropic::CLAUDE_SONNET_4_5_20250929, context_window: 200000, max_output: 64000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 3.0, output: 15.0, cache_read: 0.3, cache_creation: 3.75 } },
        Model { id: models::anthropic::CLAUDE_SONNET_4_6, context_window: 1000000, max_output: 64000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 3.0, output: 15.0, cache_read: 0.3, cache_creation: 3.75 } },
        Model { id: models::anthropic::CLAUDE_SONNET_5, context_window: 1000000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 2.0, output: 10.0, cache_read: 0.2, cache_creation: 2.5 } },
        Model { id: models::openai::CHATGPT_4O_LATEST, context_window: 128000, max_output: 4096, reasoning: false, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: false, pricing: ModelPricing { input: 5.0, output: 15.0, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_3_5_TURBO, context_window: 16385, max_output: 4096, reasoning: false, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 0.5, output: 1.5, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_3_5_TURBO_0125, context_window: 16385, max_output: 4096, reasoning: false, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 0.5, output: 1.5, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_3_5_TURBO_1106, context_window: 16385, max_output: 4096, reasoning: false, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 1.0, output: 2.0, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_3_5_TURBO_16K, context_window: 16385, max_output: 4096, reasoning: false, vision: false, tools: false, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 3.0, output: 4.0, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4, context_window: 8192, max_output: 4096, reasoning: false, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 30.0, output: 60.0, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4_0125_PREVIEW, context_window: 128000, max_output: 4096, reasoning: false, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 10.0, output: 30.0, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4_0314, context_window: 8192, max_output: 4096, reasoning: false, vision: false, tools: false, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 30.0, output: 60.0, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4_0613, context_window: 8192, max_output: 4096, reasoning: false, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 30.0, output: 60.0, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4_1106_PREVIEW, context_window: 128000, max_output: 4096, reasoning: false, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 10.0, output: 30.0, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4_TURBO, context_window: 128000, max_output: 4096, reasoning: false, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: false, pricing: ModelPricing { input: 10.0, output: 30.0, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4_TURBO_2024_04_09, context_window: 128000, max_output: 4096, reasoning: false, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: false, pricing: ModelPricing { input: 10.0, output: 30.0, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4_TURBO_PREVIEW, context_window: 128000, max_output: 4096, reasoning: false, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: false, pricing: ModelPricing { input: 10.0, output: 30.0, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4_1, context_window: 1047576, max_output: 32768, reasoning: false, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 2.0, output: 8.0, cache_read: 0.5, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4_1_2025_04_14, context_window: 1047576, max_output: 32768, reasoning: false, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 2.0, output: 8.0, cache_read: 0.5, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4_1_MINI, context_window: 1047576, max_output: 32768, reasoning: false, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 0.4, output: 1.6, cache_read: 0.1, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4_1_MINI_2025_04_14, context_window: 1047576, max_output: 32768, reasoning: false, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 0.4, output: 1.6, cache_read: 0.1, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4_1_NANO, context_window: 1047576, max_output: 32768, reasoning: false, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 0.1, output: 0.4, cache_read: 0.025, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4_1_NANO_2025_04_14, context_window: 1047576, max_output: 32768, reasoning: false, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 0.1, output: 0.4, cache_read: 0.025, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4O, context_window: 128000, max_output: 16384, reasoning: false, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 2.5, output: 10.0, cache_read: 1.25, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4O_2024_05_13, context_window: 128000, max_output: 4096, reasoning: false, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: false, pricing: ModelPricing { input: 5.0, output: 15.0, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4O_2024_08_06, context_window: 128000, max_output: 16384, reasoning: false, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 2.5, output: 10.0, cache_read: 1.25, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4O_2024_11_20, context_window: 128000, max_output: 16384, reasoning: false, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 2.5, output: 10.0, cache_read: 1.25, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4O_AUDIO_PREVIEW, context_window: 128000, max_output: 16384, reasoning: false, vision: false, tools: true, web_search: false, audio_input: true, audio_output: true, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 2.5, output: 10.0, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4O_AUDIO_PREVIEW_2024_12_17, context_window: 128000, max_output: 16384, reasoning: false, vision: false, tools: true, web_search: false, audio_input: true, audio_output: true, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 2.5, output: 10.0, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4O_AUDIO_PREVIEW_2025_06_03, context_window: 128000, max_output: 16384, reasoning: false, vision: false, tools: true, web_search: false, audio_input: true, audio_output: true, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 2.5, output: 10.0, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4O_MINI, context_window: 128000, max_output: 16384, reasoning: false, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 0.15, output: 0.6, cache_read: 0.075, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4O_MINI_2024_07_18, context_window: 128000, max_output: 16384, reasoning: false, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 0.15, output: 0.6, cache_read: 0.075, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4O_MINI_AUDIO_PREVIEW, context_window: 128000, max_output: 16384, reasoning: false, vision: false, tools: true, web_search: false, audio_input: true, audio_output: true, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 0.15, output: 0.6, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4O_MINI_AUDIO_PREVIEW_2024_12_17, context_window: 128000, max_output: 16384, reasoning: false, vision: false, tools: true, web_search: false, audio_input: true, audio_output: true, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 0.15, output: 0.6, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4O_MINI_SEARCH_PREVIEW, context_window: 128000, max_output: 16384, reasoning: false, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 0.15, output: 0.6, cache_read: 0.075, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4O_MINI_SEARCH_PREVIEW_2025_03_11, context_window: 128000, max_output: 16384, reasoning: false, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 0.15, output: 0.6, cache_read: 0.075, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4O_SEARCH_PREVIEW, context_window: 128000, max_output: 16384, reasoning: false, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 2.5, output: 10.0, cache_read: 1.25, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_4O_SEARCH_PREVIEW_2025_03_11, context_window: 128000, max_output: 16384, reasoning: false, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 2.5, output: 10.0, cache_read: 1.25, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5, context_window: 272000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 1.25, output: 10.0, cache_read: 0.125, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_2025_08_07, context_window: 272000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 1.25, output: 10.0, cache_read: 0.125, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_CHAT, context_window: 128000, max_output: 16384, reasoning: true, vision: true, tools: false, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 1.25, output: 10.0, cache_read: 0.125, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_CHAT_LATEST, context_window: 128000, max_output: 16384, reasoning: true, vision: true, tools: false, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 1.25, output: 10.0, cache_read: 0.125, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_MINI, context_window: 272000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 0.25, output: 2.0, cache_read: 0.025, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_MINI_2025_08_07, context_window: 272000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 0.25, output: 2.0, cache_read: 0.025, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_NANO, context_window: 272000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 0.05, output: 0.4, cache_read: 0.005, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_NANO_2025_08_07, context_window: 272000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 0.05, output: 0.4, cache_read: 0.005, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_SEARCH_API, context_window: 272000, max_output: 128000, reasoning: false, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 1.25, output: 10.0, cache_read: 0.125, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_SEARCH_API_2025_10_14, context_window: 272000, max_output: 128000, reasoning: false, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 1.25, output: 10.0, cache_read: 0.125, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_1, context_window: 272000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: true, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 1.25, output: 10.0, cache_read: 0.125, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_1_2025_11_13, context_window: 272000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: true, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 1.25, output: 10.0, cache_read: 0.125, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_1_CHAT_LATEST, context_window: 128000, max_output: 16384, reasoning: true, vision: true, tools: false, web_search: true, audio_input: false, audio_output: false, image_output: true, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 1.25, output: 10.0, cache_read: 0.125, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_2, context_window: 272000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: true, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 1.75, output: 14.0, cache_read: 0.175, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_2_2025_12_11, context_window: 272000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: true, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 1.75, output: 14.0, cache_read: 0.175, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_2_CHAT_LATEST, context_window: 128000, max_output: 16384, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 1.75, output: 14.0, cache_read: 0.175, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_3_CHAT_LATEST, context_window: 128000, max_output: 16384, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 1.75, output: 14.0, cache_read: 0.175, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_4, context_window: 1050000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 2.5, output: 15.0, cache_read: 0.25, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_4_2026_03_05, context_window: 1050000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 2.5, output: 15.0, cache_read: 0.25, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_4_MINI, context_window: 272000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 0.75, output: 4.5, cache_read: 0.075, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_4_MINI_2026_03_17, context_window: 272000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 0.75, output: 4.5, cache_read: 0.075, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_4_NANO, context_window: 272000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 0.2, output: 1.25, cache_read: 0.02, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_4_NANO_2026_03_17, context_window: 272000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 0.2, output: 1.25, cache_read: 0.02, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_5, context_window: 1050000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 5.0, output: 30.0, cache_read: 0.5, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_5_2026_04_23, context_window: 1050000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 5.0, output: 30.0, cache_read: 0.5, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_5_6, context_window: 1050000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 5.0, output: 30.0, cache_read: 0.5, cache_creation: 6.25 } },
        Model { id: models::openai::GPT_5_6_LUNA, context_window: 1050000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 0.2, output: 1.2, cache_read: 0.02, cache_creation: 0.25 } },
        Model { id: models::openai::GPT_5_6_SOL, context_window: 1050000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 5.0, output: 30.0, cache_read: 0.5, cache_creation: 6.25 } },
        Model { id: models::openai::GPT_5_6_TERRA, context_window: 1050000, max_output: 128000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 2.0, output: 12.0, cache_read: 0.2, cache_creation: 2.5 } },
        Model { id: models::openai::GPT_AUDIO, context_window: 128000, max_output: 16384, reasoning: false, vision: false, tools: true, web_search: false, audio_input: true, audio_output: true, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 2.5, output: 10.0, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_AUDIO_1_5, context_window: 128000, max_output: 16384, reasoning: false, vision: false, tools: true, web_search: false, audio_input: true, audio_output: true, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 2.5, output: 10.0, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_AUDIO_2025_08_28, context_window: 128000, max_output: 16384, reasoning: false, vision: false, tools: true, web_search: false, audio_input: true, audio_output: true, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 2.5, output: 10.0, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_AUDIO_MINI, context_window: 128000, max_output: 16384, reasoning: false, vision: false, tools: true, web_search: false, audio_input: true, audio_output: true, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 0.6, output: 2.4, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_AUDIO_MINI_2025_10_06, context_window: 128000, max_output: 16384, reasoning: false, vision: false, tools: true, web_search: false, audio_input: true, audio_output: true, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 0.6, output: 2.4, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::GPT_AUDIO_MINI_2025_12_15, context_window: 128000, max_output: 16384, reasoning: false, vision: false, tools: true, web_search: false, audio_input: true, audio_output: true, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 0.6, output: 2.4, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::openai::O1, context_window: 200000, max_output: 100000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 15.0, output: 60.0, cache_read: 7.5, cache_creation: 0.0 } },
        Model { id: models::openai::O1_2024_12_17, context_window: 200000, max_output: 100000, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 15.0, output: 60.0, cache_read: 7.5, cache_creation: 0.0 } },
        Model { id: models::openai::O3, context_window: 200000, max_output: 100000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 2.0, output: 8.0, cache_read: 0.5, cache_creation: 0.0 } },
        Model { id: models::openai::O3_2025_04_16, context_window: 200000, max_output: 100000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 2.0, output: 8.0, cache_read: 0.5, cache_creation: 0.0 } },
        Model { id: models::openai::O3_MINI, context_window: 200000, max_output: 100000, reasoning: true, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: true, pricing: ModelPricing { input: 1.1, output: 4.4, cache_read: 0.55, cache_creation: 0.0 } },
        Model { id: models::openai::O3_MINI_2025_01_31, context_window: 200000, max_output: 100000, reasoning: true, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: true, pricing: ModelPricing { input: 1.1, output: 4.4, cache_read: 0.55, cache_creation: 0.0 } },
        Model { id: models::openai::O4_MINI, context_window: 200000, max_output: 100000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 1.1, output: 4.4, cache_read: 0.275, cache_creation: 0.0 } },
        Model { id: models::openai::O4_MINI_2025_04_16, context_window: 200000, max_output: 100000, reasoning: true, vision: true, tools: true, web_search: true, audio_input: false, audio_output: false, image_output: false, pdf_input: true, structured_output: true, pricing: ModelPricing { input: 1.1, output: 4.4, cache_read: 0.275, cache_creation: 0.0 } },
        Model { id: models::qwen::DEEPSEEK_V4_FLASH, context_window: 1000000, max_output: 393216, reasoning: true, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: true, pricing: ModelPricing { input: 0.2, output: 0.4, cache_read: 0.04, cache_creation: 0.0 } },
        Model { id: models::qwen::DEEPSEEK_V4_FLASH_0731, context_window: 1000000, max_output: 393216, reasoning: true, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: true, pricing: ModelPricing { input: 0.2, output: 0.4, cache_read: 0.04, cache_creation: 0.0 } },
        Model { id: models::qwen::DEEPSEEK_V4_PRO, context_window: 1000000, max_output: 393216, reasoning: true, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: true, pricing: ModelPricing { input: 2.4, output: 4.8, cache_read: 0.2, cache_creation: 0.0 } },
        Model { id: models::qwen::GLM_5_1, context_window: 202745, max_output: 131072, reasoning: true, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: true, pricing: ModelPricing { input: 1.4, output: 4.4, cache_read: 0.26, cache_creation: 0.0 } },
        Model { id: models::qwen::GLM_5_2, context_window: 1048576, max_output: 131072, reasoning: true, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: true, pricing: ModelPricing { input: 1.4, output: 4.4, cache_read: 0.28, cache_creation: 0.0 } },
        Model { id: models::qwen::KIMI_K2_7_CODE, context_window: 229376, max_output: 16384, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: true, pricing: ModelPricing { input: 0.95, output: 4.0, cache_read: 0.19, cache_creation: 0.0 } },
        Model { id: models::qwen::QWEN_CODER, context_window: 1000000, max_output: 16384, reasoning: true, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 0.3, output: 1.5, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::qwen::QWEN_MAX, context_window: 30720, max_output: 8192, reasoning: true, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 1.6, output: 6.4, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::qwen::QWEN_PLUS, context_window: 129024, max_output: 16384, reasoning: true, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 0.4, output: 1.2, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::qwen::QWEN_PLUS_2025_01_25, context_window: 129024, max_output: 8192, reasoning: true, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 0.4, output: 1.2, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::qwen::QWEN_PLUS_2025_04_28, context_window: 129024, max_output: 16384, reasoning: true, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 0.4, output: 1.2, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::qwen::QWEN_PLUS_2025_07_14, context_window: 129024, max_output: 16384, reasoning: true, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 0.4, output: 1.2, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::qwen::QWEN_TURBO, context_window: 129024, max_output: 16384, reasoning: true, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 0.05, output: 0.2, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::qwen::QWEN_TURBO_2024_11_01, context_window: 1000000, max_output: 8192, reasoning: true, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 0.05, output: 0.2, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::qwen::QWEN_TURBO_2025_04_28, context_window: 1000000, max_output: 16384, reasoning: true, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 0.05, output: 0.2, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::qwen::QWEN_TURBO_LATEST, context_window: 1000000, max_output: 16384, reasoning: true, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 0.05, output: 0.2, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::qwen::QWEN3_NEXT_80B_A3B_INSTRUCT, context_window: 262144, max_output: 65536, reasoning: false, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 0.15, output: 1.2, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::qwen::QWEN3_NEXT_80B_A3B_THINKING, context_window: 262144, max_output: 65536, reasoning: true, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 0.15, output: 1.2, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::qwen::QWEN3_VL_235B_A22B_INSTRUCT, context_window: 131072, max_output: 32768, reasoning: false, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 0.4, output: 1.6, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::qwen::QWEN3_VL_235B_A22B_THINKING, context_window: 131072, max_output: 32768, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 0.4, output: 4.0, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::qwen::QWEN3_VL_32B_INSTRUCT, context_window: 131072, max_output: 32768, reasoning: false, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 0.16, output: 0.64, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::qwen::QWEN3_VL_32B_THINKING, context_window: 131072, max_output: 32768, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 0.16, output: 2.87, cache_read: 0.0, cache_creation: 0.0 } },
        Model { id: models::qwen::QWEN3_7_MAX, context_window: 991808, max_output: 65536, reasoning: true, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: true, pricing: ModelPricing { input: 2.5, output: 7.5, cache_read: 0.5, cache_creation: 0.0 } },
        Model { id: models::qwen::QWEN3_8_MAX, context_window: 991808, max_output: 131072, reasoning: true, vision: true, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: true, pricing: ModelPricing { input: 2.0, output: 6.0, cache_read: 0.25, cache_creation: 0.0 } },
        Model { id: models::qwen::QWQ_PLUS, context_window: 98304, max_output: 8192, reasoning: true, vision: false, tools: true, web_search: false, audio_input: false, audio_output: false, image_output: false, pdf_input: false, structured_output: false, pricing: ModelPricing { input: 0.8, output: 2.4, cache_read: 0.0, cache_creation: 0.0 } },
    ]
}

/// Typed handles for the known models, grouped by provider.
///
/// `models::anthropic::CLAUDE_OPUS_4_8` is a `const` [`ModelRef`]; pass it
/// anywhere a `ModelRef` is expected. An open-weight model behind a gateway
/// the catalog doesn't index still uses `ModelRef::new("provider/model")`.
#[rustfmt::skip]
pub mod models {
    use pocopine_agenkit_core::ModelRef;

    /// anthropic model handles.
    pub mod anthropic {
        use super::ModelRef;
        /// `anthropic/claude-3-7-sonnet-20250219` · 200K ctx · reasoning · vision
        pub const CLAUDE_3_7_SONNET_20250219: ModelRef = ModelRef::from_static("anthropic/claude-3-7-sonnet-20250219");
        /// `anthropic/claude-3-haiku-20240307` · 200K ctx · vision
        pub const CLAUDE_3_HAIKU_20240307: ModelRef = ModelRef::from_static("anthropic/claude-3-haiku-20240307");
        /// `anthropic/claude-3-opus-20240229` · 200K ctx · vision
        pub const CLAUDE_3_OPUS_20240229: ModelRef = ModelRef::from_static("anthropic/claude-3-opus-20240229");
        /// `anthropic/claude-4-opus-20250514` · 200K ctx · reasoning · vision
        pub const CLAUDE_4_OPUS_20250514: ModelRef = ModelRef::from_static("anthropic/claude-4-opus-20250514");
        /// `anthropic/claude-4-sonnet-20250514` · 1M ctx · reasoning · vision
        pub const CLAUDE_4_SONNET_20250514: ModelRef = ModelRef::from_static("anthropic/claude-4-sonnet-20250514");
        /// `anthropic/claude-fable-5` · 1M ctx · reasoning · vision
        pub const CLAUDE_FABLE_5: ModelRef = ModelRef::from_static("anthropic/claude-fable-5");
        /// `anthropic/claude-haiku-4-5` · 200K ctx · reasoning · vision
        pub const CLAUDE_HAIKU_4_5: ModelRef = ModelRef::from_static("anthropic/claude-haiku-4-5");
        /// `anthropic/claude-haiku-4-5-20251001` · 200K ctx · reasoning · vision
        pub const CLAUDE_HAIKU_4_5_20251001: ModelRef = ModelRef::from_static("anthropic/claude-haiku-4-5-20251001");
        /// `anthropic/claude-mythos-5` · 1M ctx · reasoning · vision
        pub const CLAUDE_MYTHOS_5: ModelRef = ModelRef::from_static("anthropic/claude-mythos-5");
        /// `anthropic/claude-mythos-preview` · 1M ctx · reasoning · vision
        pub const CLAUDE_MYTHOS_PREVIEW: ModelRef = ModelRef::from_static("anthropic/claude-mythos-preview");
        /// `anthropic/claude-opus-4-1` · 200K ctx · reasoning · vision
        pub const CLAUDE_OPUS_4_1: ModelRef = ModelRef::from_static("anthropic/claude-opus-4-1");
        /// `anthropic/claude-opus-4-1-20250805` · 200K ctx · reasoning · vision
        pub const CLAUDE_OPUS_4_1_20250805: ModelRef = ModelRef::from_static("anthropic/claude-opus-4-1-20250805");
        /// `anthropic/claude-opus-4-20250514` · 200K ctx · reasoning · vision
        pub const CLAUDE_OPUS_4_20250514: ModelRef = ModelRef::from_static("anthropic/claude-opus-4-20250514");
        /// `anthropic/claude-opus-4-5` · 200K ctx · reasoning · vision
        pub const CLAUDE_OPUS_4_5: ModelRef = ModelRef::from_static("anthropic/claude-opus-4-5");
        /// `anthropic/claude-opus-4-5-20251101` · 200K ctx · reasoning · vision
        pub const CLAUDE_OPUS_4_5_20251101: ModelRef = ModelRef::from_static("anthropic/claude-opus-4-5-20251101");
        /// `anthropic/claude-opus-4-6` · 1M ctx · reasoning · vision
        pub const CLAUDE_OPUS_4_6: ModelRef = ModelRef::from_static("anthropic/claude-opus-4-6");
        /// `anthropic/claude-opus-4-6-20260205` · 1M ctx · reasoning · vision
        pub const CLAUDE_OPUS_4_6_20260205: ModelRef = ModelRef::from_static("anthropic/claude-opus-4-6-20260205");
        /// `anthropic/claude-opus-4-7` · 1M ctx · reasoning · vision
        pub const CLAUDE_OPUS_4_7: ModelRef = ModelRef::from_static("anthropic/claude-opus-4-7");
        /// `anthropic/claude-opus-4-7-20260416` · 1M ctx · reasoning · vision
        pub const CLAUDE_OPUS_4_7_20260416: ModelRef = ModelRef::from_static("anthropic/claude-opus-4-7-20260416");
        /// `anthropic/claude-opus-4-8` · 1M ctx · reasoning · vision
        pub const CLAUDE_OPUS_4_8: ModelRef = ModelRef::from_static("anthropic/claude-opus-4-8");
        /// `anthropic/claude-opus-5` · 1M ctx · reasoning · vision
        pub const CLAUDE_OPUS_5: ModelRef = ModelRef::from_static("anthropic/claude-opus-5");
        /// `anthropic/claude-sonnet-4-20250514` · 1M ctx · reasoning · vision
        pub const CLAUDE_SONNET_4_20250514: ModelRef = ModelRef::from_static("anthropic/claude-sonnet-4-20250514");
        /// `anthropic/claude-sonnet-4-5` · 200K ctx · reasoning · vision
        pub const CLAUDE_SONNET_4_5: ModelRef = ModelRef::from_static("anthropic/claude-sonnet-4-5");
        /// `anthropic/claude-sonnet-4-5-20250929` · 200K ctx · reasoning · vision
        pub const CLAUDE_SONNET_4_5_20250929: ModelRef = ModelRef::from_static("anthropic/claude-sonnet-4-5-20250929");
        /// `anthropic/claude-sonnet-4-6` · 1M ctx · reasoning · vision
        pub const CLAUDE_SONNET_4_6: ModelRef = ModelRef::from_static("anthropic/claude-sonnet-4-6");
        /// `anthropic/claude-sonnet-5` · 1M ctx · reasoning · vision
        pub const CLAUDE_SONNET_5: ModelRef = ModelRef::from_static("anthropic/claude-sonnet-5");
    }

    /// openai model handles.
    pub mod openai {
        use super::ModelRef;
        /// `openai/chatgpt-4o-latest` · 128K ctx · vision
        pub const CHATGPT_4O_LATEST: ModelRef = ModelRef::from_static("openai/chatgpt-4o-latest");
        /// `openai/gpt-3.5-turbo` · 16385 ctx
        pub const GPT_3_5_TURBO: ModelRef = ModelRef::from_static("openai/gpt-3.5-turbo");
        /// `openai/gpt-3.5-turbo-0125` · 16385 ctx
        pub const GPT_3_5_TURBO_0125: ModelRef = ModelRef::from_static("openai/gpt-3.5-turbo-0125");
        /// `openai/gpt-3.5-turbo-1106` · 16385 ctx
        pub const GPT_3_5_TURBO_1106: ModelRef = ModelRef::from_static("openai/gpt-3.5-turbo-1106");
        /// `openai/gpt-3.5-turbo-16k` · 16385 ctx
        pub const GPT_3_5_TURBO_16K: ModelRef = ModelRef::from_static("openai/gpt-3.5-turbo-16k");
        /// `openai/gpt-4` · 8192 ctx
        pub const GPT_4: ModelRef = ModelRef::from_static("openai/gpt-4");
        /// `openai/gpt-4-0125-preview` · 128K ctx
        pub const GPT_4_0125_PREVIEW: ModelRef = ModelRef::from_static("openai/gpt-4-0125-preview");
        /// `openai/gpt-4-0314` · 8192 ctx
        pub const GPT_4_0314: ModelRef = ModelRef::from_static("openai/gpt-4-0314");
        /// `openai/gpt-4-0613` · 8192 ctx
        pub const GPT_4_0613: ModelRef = ModelRef::from_static("openai/gpt-4-0613");
        /// `openai/gpt-4-1106-preview` · 128K ctx
        pub const GPT_4_1106_PREVIEW: ModelRef = ModelRef::from_static("openai/gpt-4-1106-preview");
        /// `openai/gpt-4-turbo` · 128K ctx · vision
        pub const GPT_4_TURBO: ModelRef = ModelRef::from_static("openai/gpt-4-turbo");
        /// `openai/gpt-4-turbo-2024-04-09` · 128K ctx · vision
        pub const GPT_4_TURBO_2024_04_09: ModelRef = ModelRef::from_static("openai/gpt-4-turbo-2024-04-09");
        /// `openai/gpt-4-turbo-preview` · 128K ctx
        pub const GPT_4_TURBO_PREVIEW: ModelRef = ModelRef::from_static("openai/gpt-4-turbo-preview");
        /// `openai/gpt-4.1` · 1047576 ctx · vision
        pub const GPT_4_1: ModelRef = ModelRef::from_static("openai/gpt-4.1");
        /// `openai/gpt-4.1-2025-04-14` · 1047576 ctx · vision
        pub const GPT_4_1_2025_04_14: ModelRef = ModelRef::from_static("openai/gpt-4.1-2025-04-14");
        /// `openai/gpt-4.1-mini` · 1047576 ctx · vision
        pub const GPT_4_1_MINI: ModelRef = ModelRef::from_static("openai/gpt-4.1-mini");
        /// `openai/gpt-4.1-mini-2025-04-14` · 1047576 ctx · vision
        pub const GPT_4_1_MINI_2025_04_14: ModelRef = ModelRef::from_static("openai/gpt-4.1-mini-2025-04-14");
        /// `openai/gpt-4.1-nano` · 1047576 ctx · vision
        pub const GPT_4_1_NANO: ModelRef = ModelRef::from_static("openai/gpt-4.1-nano");
        /// `openai/gpt-4.1-nano-2025-04-14` · 1047576 ctx · vision
        pub const GPT_4_1_NANO_2025_04_14: ModelRef = ModelRef::from_static("openai/gpt-4.1-nano-2025-04-14");
        /// `openai/gpt-4o` · 128K ctx · vision
        pub const GPT_4O: ModelRef = ModelRef::from_static("openai/gpt-4o");
        /// `openai/gpt-4o-2024-05-13` · 128K ctx · vision
        pub const GPT_4O_2024_05_13: ModelRef = ModelRef::from_static("openai/gpt-4o-2024-05-13");
        /// `openai/gpt-4o-2024-08-06` · 128K ctx · vision
        pub const GPT_4O_2024_08_06: ModelRef = ModelRef::from_static("openai/gpt-4o-2024-08-06");
        /// `openai/gpt-4o-2024-11-20` · 128K ctx · vision
        pub const GPT_4O_2024_11_20: ModelRef = ModelRef::from_static("openai/gpt-4o-2024-11-20");
        /// `openai/gpt-4o-audio-preview` · 128K ctx
        pub const GPT_4O_AUDIO_PREVIEW: ModelRef = ModelRef::from_static("openai/gpt-4o-audio-preview");
        /// `openai/gpt-4o-audio-preview-2024-12-17` · 128K ctx
        pub const GPT_4O_AUDIO_PREVIEW_2024_12_17: ModelRef = ModelRef::from_static("openai/gpt-4o-audio-preview-2024-12-17");
        /// `openai/gpt-4o-audio-preview-2025-06-03` · 128K ctx
        pub const GPT_4O_AUDIO_PREVIEW_2025_06_03: ModelRef = ModelRef::from_static("openai/gpt-4o-audio-preview-2025-06-03");
        /// `openai/gpt-4o-mini` · 128K ctx · vision
        pub const GPT_4O_MINI: ModelRef = ModelRef::from_static("openai/gpt-4o-mini");
        /// `openai/gpt-4o-mini-2024-07-18` · 128K ctx · vision
        pub const GPT_4O_MINI_2024_07_18: ModelRef = ModelRef::from_static("openai/gpt-4o-mini-2024-07-18");
        /// `openai/gpt-4o-mini-audio-preview` · 128K ctx
        pub const GPT_4O_MINI_AUDIO_PREVIEW: ModelRef = ModelRef::from_static("openai/gpt-4o-mini-audio-preview");
        /// `openai/gpt-4o-mini-audio-preview-2024-12-17` · 128K ctx
        pub const GPT_4O_MINI_AUDIO_PREVIEW_2024_12_17: ModelRef = ModelRef::from_static("openai/gpt-4o-mini-audio-preview-2024-12-17");
        /// `openai/gpt-4o-mini-search-preview` · 128K ctx · vision
        pub const GPT_4O_MINI_SEARCH_PREVIEW: ModelRef = ModelRef::from_static("openai/gpt-4o-mini-search-preview");
        /// `openai/gpt-4o-mini-search-preview-2025-03-11` · 128K ctx · vision
        pub const GPT_4O_MINI_SEARCH_PREVIEW_2025_03_11: ModelRef = ModelRef::from_static("openai/gpt-4o-mini-search-preview-2025-03-11");
        /// `openai/gpt-4o-search-preview` · 128K ctx · vision
        pub const GPT_4O_SEARCH_PREVIEW: ModelRef = ModelRef::from_static("openai/gpt-4o-search-preview");
        /// `openai/gpt-4o-search-preview-2025-03-11` · 128K ctx · vision
        pub const GPT_4O_SEARCH_PREVIEW_2025_03_11: ModelRef = ModelRef::from_static("openai/gpt-4o-search-preview-2025-03-11");
        /// `openai/gpt-5` · 272K ctx · reasoning · vision
        pub const GPT_5: ModelRef = ModelRef::from_static("openai/gpt-5");
        /// `openai/gpt-5-2025-08-07` · 272K ctx · reasoning · vision
        pub const GPT_5_2025_08_07: ModelRef = ModelRef::from_static("openai/gpt-5-2025-08-07");
        /// `openai/gpt-5-chat` · 128K ctx · reasoning · vision
        pub const GPT_5_CHAT: ModelRef = ModelRef::from_static("openai/gpt-5-chat");
        /// `openai/gpt-5-chat-latest` · 128K ctx · reasoning · vision
        pub const GPT_5_CHAT_LATEST: ModelRef = ModelRef::from_static("openai/gpt-5-chat-latest");
        /// `openai/gpt-5-mini` · 272K ctx · reasoning · vision
        pub const GPT_5_MINI: ModelRef = ModelRef::from_static("openai/gpt-5-mini");
        /// `openai/gpt-5-mini-2025-08-07` · 272K ctx · reasoning · vision
        pub const GPT_5_MINI_2025_08_07: ModelRef = ModelRef::from_static("openai/gpt-5-mini-2025-08-07");
        /// `openai/gpt-5-nano` · 272K ctx · reasoning · vision
        pub const GPT_5_NANO: ModelRef = ModelRef::from_static("openai/gpt-5-nano");
        /// `openai/gpt-5-nano-2025-08-07` · 272K ctx · reasoning · vision
        pub const GPT_5_NANO_2025_08_07: ModelRef = ModelRef::from_static("openai/gpt-5-nano-2025-08-07");
        /// `openai/gpt-5-search-api` · 272K ctx · vision
        pub const GPT_5_SEARCH_API: ModelRef = ModelRef::from_static("openai/gpt-5-search-api");
        /// `openai/gpt-5-search-api-2025-10-14` · 272K ctx · vision
        pub const GPT_5_SEARCH_API_2025_10_14: ModelRef = ModelRef::from_static("openai/gpt-5-search-api-2025-10-14");
        /// `openai/gpt-5.1` · 272K ctx · reasoning · vision · image output
        pub const GPT_5_1: ModelRef = ModelRef::from_static("openai/gpt-5.1");
        /// `openai/gpt-5.1-2025-11-13` · 272K ctx · reasoning · vision · image output
        pub const GPT_5_1_2025_11_13: ModelRef = ModelRef::from_static("openai/gpt-5.1-2025-11-13");
        /// `openai/gpt-5.1-chat-latest` · 128K ctx · reasoning · vision · image output
        pub const GPT_5_1_CHAT_LATEST: ModelRef = ModelRef::from_static("openai/gpt-5.1-chat-latest");
        /// `openai/gpt-5.2` · 272K ctx · reasoning · vision · image output
        pub const GPT_5_2: ModelRef = ModelRef::from_static("openai/gpt-5.2");
        /// `openai/gpt-5.2-2025-12-11` · 272K ctx · reasoning · vision · image output
        pub const GPT_5_2_2025_12_11: ModelRef = ModelRef::from_static("openai/gpt-5.2-2025-12-11");
        /// `openai/gpt-5.2-chat-latest` · 128K ctx · reasoning · vision
        pub const GPT_5_2_CHAT_LATEST: ModelRef = ModelRef::from_static("openai/gpt-5.2-chat-latest");
        /// `openai/gpt-5.3-chat-latest` · 128K ctx · reasoning · vision
        pub const GPT_5_3_CHAT_LATEST: ModelRef = ModelRef::from_static("openai/gpt-5.3-chat-latest");
        /// `openai/gpt-5.4` · 1050K ctx · reasoning · vision
        pub const GPT_5_4: ModelRef = ModelRef::from_static("openai/gpt-5.4");
        /// `openai/gpt-5.4-2026-03-05` · 1050K ctx · reasoning · vision
        pub const GPT_5_4_2026_03_05: ModelRef = ModelRef::from_static("openai/gpt-5.4-2026-03-05");
        /// `openai/gpt-5.4-mini` · 272K ctx · reasoning · vision
        pub const GPT_5_4_MINI: ModelRef = ModelRef::from_static("openai/gpt-5.4-mini");
        /// `openai/gpt-5.4-mini-2026-03-17` · 272K ctx · reasoning · vision
        pub const GPT_5_4_MINI_2026_03_17: ModelRef = ModelRef::from_static("openai/gpt-5.4-mini-2026-03-17");
        /// `openai/gpt-5.4-nano` · 272K ctx · reasoning · vision
        pub const GPT_5_4_NANO: ModelRef = ModelRef::from_static("openai/gpt-5.4-nano");
        /// `openai/gpt-5.4-nano-2026-03-17` · 272K ctx · reasoning · vision
        pub const GPT_5_4_NANO_2026_03_17: ModelRef = ModelRef::from_static("openai/gpt-5.4-nano-2026-03-17");
        /// `openai/gpt-5.5` · 1050K ctx · reasoning · vision
        pub const GPT_5_5: ModelRef = ModelRef::from_static("openai/gpt-5.5");
        /// `openai/gpt-5.5-2026-04-23` · 1050K ctx · reasoning · vision
        pub const GPT_5_5_2026_04_23: ModelRef = ModelRef::from_static("openai/gpt-5.5-2026-04-23");
        /// `openai/gpt-5.6` · 1050K ctx · reasoning · vision
        pub const GPT_5_6: ModelRef = ModelRef::from_static("openai/gpt-5.6");
        /// `openai/gpt-5.6-luna` · 1050K ctx · reasoning · vision
        pub const GPT_5_6_LUNA: ModelRef = ModelRef::from_static("openai/gpt-5.6-luna");
        /// `openai/gpt-5.6-sol` · 1050K ctx · reasoning · vision
        pub const GPT_5_6_SOL: ModelRef = ModelRef::from_static("openai/gpt-5.6-sol");
        /// `openai/gpt-5.6-terra` · 1050K ctx · reasoning · vision
        pub const GPT_5_6_TERRA: ModelRef = ModelRef::from_static("openai/gpt-5.6-terra");
        /// `openai/gpt-audio` · 128K ctx
        pub const GPT_AUDIO: ModelRef = ModelRef::from_static("openai/gpt-audio");
        /// `openai/gpt-audio-1.5` · 128K ctx
        pub const GPT_AUDIO_1_5: ModelRef = ModelRef::from_static("openai/gpt-audio-1.5");
        /// `openai/gpt-audio-2025-08-28` · 128K ctx
        pub const GPT_AUDIO_2025_08_28: ModelRef = ModelRef::from_static("openai/gpt-audio-2025-08-28");
        /// `openai/gpt-audio-mini` · 128K ctx
        pub const GPT_AUDIO_MINI: ModelRef = ModelRef::from_static("openai/gpt-audio-mini");
        /// `openai/gpt-audio-mini-2025-10-06` · 128K ctx
        pub const GPT_AUDIO_MINI_2025_10_06: ModelRef = ModelRef::from_static("openai/gpt-audio-mini-2025-10-06");
        /// `openai/gpt-audio-mini-2025-12-15` · 128K ctx
        pub const GPT_AUDIO_MINI_2025_12_15: ModelRef = ModelRef::from_static("openai/gpt-audio-mini-2025-12-15");
        /// `openai/o1` · 200K ctx · reasoning · vision
        pub const O1: ModelRef = ModelRef::from_static("openai/o1");
        /// `openai/o1-2024-12-17` · 200K ctx · reasoning · vision
        pub const O1_2024_12_17: ModelRef = ModelRef::from_static("openai/o1-2024-12-17");
        /// `openai/o3` · 200K ctx · reasoning · vision
        pub const O3: ModelRef = ModelRef::from_static("openai/o3");
        /// `openai/o3-2025-04-16` · 200K ctx · reasoning · vision
        pub const O3_2025_04_16: ModelRef = ModelRef::from_static("openai/o3-2025-04-16");
        /// `openai/o3-mini` · 200K ctx · reasoning
        pub const O3_MINI: ModelRef = ModelRef::from_static("openai/o3-mini");
        /// `openai/o3-mini-2025-01-31` · 200K ctx · reasoning
        pub const O3_MINI_2025_01_31: ModelRef = ModelRef::from_static("openai/o3-mini-2025-01-31");
        /// `openai/o4-mini` · 200K ctx · reasoning · vision
        pub const O4_MINI: ModelRef = ModelRef::from_static("openai/o4-mini");
        /// `openai/o4-mini-2025-04-16` · 200K ctx · reasoning · vision
        pub const O4_MINI_2025_04_16: ModelRef = ModelRef::from_static("openai/o4-mini-2025-04-16");
    }

    /// qwen model handles.
    pub mod qwen {
        use super::ModelRef;
        /// `qwen/deepseek-v4-flash` · 1M ctx · reasoning
        pub const DEEPSEEK_V4_FLASH: ModelRef = ModelRef::from_static("qwen/deepseek-v4-flash");
        /// `qwen/deepseek-v4-flash-0731` · 1M ctx · reasoning
        pub const DEEPSEEK_V4_FLASH_0731: ModelRef = ModelRef::from_static("qwen/deepseek-v4-flash-0731");
        /// `qwen/deepseek-v4-pro` · 1M ctx · reasoning
        pub const DEEPSEEK_V4_PRO: ModelRef = ModelRef::from_static("qwen/deepseek-v4-pro");
        /// `qwen/glm-5.1` · 202745 ctx · reasoning
        pub const GLM_5_1: ModelRef = ModelRef::from_static("qwen/glm-5.1");
        /// `qwen/glm-5.2` · 1048576 ctx · reasoning
        pub const GLM_5_2: ModelRef = ModelRef::from_static("qwen/glm-5.2");
        /// `qwen/kimi-k2.7-code` · 229376 ctx · reasoning · vision
        pub const KIMI_K2_7_CODE: ModelRef = ModelRef::from_static("qwen/kimi-k2.7-code");
        /// `qwen/qwen-coder` · 1M ctx · reasoning
        pub const QWEN_CODER: ModelRef = ModelRef::from_static("qwen/qwen-coder");
        /// `qwen/qwen-max` · 30720 ctx · reasoning
        pub const QWEN_MAX: ModelRef = ModelRef::from_static("qwen/qwen-max");
        /// `qwen/qwen-plus` · 129024 ctx · reasoning
        pub const QWEN_PLUS: ModelRef = ModelRef::from_static("qwen/qwen-plus");
        /// `qwen/qwen-plus-2025-01-25` · 129024 ctx · reasoning
        pub const QWEN_PLUS_2025_01_25: ModelRef = ModelRef::from_static("qwen/qwen-plus-2025-01-25");
        /// `qwen/qwen-plus-2025-04-28` · 129024 ctx · reasoning
        pub const QWEN_PLUS_2025_04_28: ModelRef = ModelRef::from_static("qwen/qwen-plus-2025-04-28");
        /// `qwen/qwen-plus-2025-07-14` · 129024 ctx · reasoning
        pub const QWEN_PLUS_2025_07_14: ModelRef = ModelRef::from_static("qwen/qwen-plus-2025-07-14");
        /// `qwen/qwen-turbo` · 129024 ctx · reasoning
        pub const QWEN_TURBO: ModelRef = ModelRef::from_static("qwen/qwen-turbo");
        /// `qwen/qwen-turbo-2024-11-01` · 1M ctx · reasoning
        pub const QWEN_TURBO_2024_11_01: ModelRef = ModelRef::from_static("qwen/qwen-turbo-2024-11-01");
        /// `qwen/qwen-turbo-2025-04-28` · 1M ctx · reasoning
        pub const QWEN_TURBO_2025_04_28: ModelRef = ModelRef::from_static("qwen/qwen-turbo-2025-04-28");
        /// `qwen/qwen-turbo-latest` · 1M ctx · reasoning
        pub const QWEN_TURBO_LATEST: ModelRef = ModelRef::from_static("qwen/qwen-turbo-latest");
        /// `qwen/qwen3-next-80b-a3b-instruct` · 262144 ctx
        pub const QWEN3_NEXT_80B_A3B_INSTRUCT: ModelRef = ModelRef::from_static("qwen/qwen3-next-80b-a3b-instruct");
        /// `qwen/qwen3-next-80b-a3b-thinking` · 262144 ctx · reasoning
        pub const QWEN3_NEXT_80B_A3B_THINKING: ModelRef = ModelRef::from_static("qwen/qwen3-next-80b-a3b-thinking");
        /// `qwen/qwen3-vl-235b-a22b-instruct` · 131072 ctx · vision
        pub const QWEN3_VL_235B_A22B_INSTRUCT: ModelRef = ModelRef::from_static("qwen/qwen3-vl-235b-a22b-instruct");
        /// `qwen/qwen3-vl-235b-a22b-thinking` · 131072 ctx · reasoning · vision
        pub const QWEN3_VL_235B_A22B_THINKING: ModelRef = ModelRef::from_static("qwen/qwen3-vl-235b-a22b-thinking");
        /// `qwen/qwen3-vl-32b-instruct` · 131072 ctx · vision
        pub const QWEN3_VL_32B_INSTRUCT: ModelRef = ModelRef::from_static("qwen/qwen3-vl-32b-instruct");
        /// `qwen/qwen3-vl-32b-thinking` · 131072 ctx · reasoning · vision
        pub const QWEN3_VL_32B_THINKING: ModelRef = ModelRef::from_static("qwen/qwen3-vl-32b-thinking");
        /// `qwen/qwen3.7-max` · 991808 ctx · reasoning
        pub const QWEN3_7_MAX: ModelRef = ModelRef::from_static("qwen/qwen3.7-max");
        /// `qwen/qwen3.8-max` · 991808 ctx · reasoning · vision
        pub const QWEN3_8_MAX: ModelRef = ModelRef::from_static("qwen/qwen3.8-max");
        /// `qwen/qwq-plus` · 98304 ctx · reasoning
        pub const QWQ_PLUS: ModelRef = ModelRef::from_static("qwen/qwq-plus");
    }
}
