//! Shared helpers used by multiple adapters.

use askama::Template;

use crate::{DeploySpec, ProcessSpec};

/// Sentinel `flush_one` checks before overwriting a file — hand-edited
/// Dockerfiles / `fly.toml` / `Dockerfile.dockerignore` lack it.
pub const GENERATED_MARKER: &str = "Generated by pocopine-deploy";

/// Subdirectory under each project root where `pocopine deploy` writes
/// generated build artefacts (Dockerfile, dockerignore, host-specific
/// config like `fly.toml` / `render.yaml` / `railway.json`). Mirrors
/// Rust's `target/` convention: one path to gitignore (`.pocopine/`),
/// one path to wipe for a clean rebuild (`rm -rf .pocopine/build`).
pub const BUILD_DIR: &str = ".pocopine/build";

/// Static body of `Dockerfile.dockerignore`. The template file under
/// `templates/` is the auditable source; we don't run it through
/// askama because it has no per-spec data.
pub fn dockerignore() -> &'static str {
    include_str!("../templates/Dockerfile.dockerignore.tmpl")
}

/// Multi-stage Dockerfile generator (RFC 080 §4.2 + §5.4); see
/// `templates/Dockerfile.tmpl` for the rendered shape.
pub fn render_dockerfile(spec: &DeploySpec) -> String {
    let process_envs: Vec<DockerfileProcEnv<'_>> = spec
        .processes()
        .map(|(name, p)| DockerfileProcEnv {
            env_name: process_env_var_name(name),
            bin: p.bin.as_str(),
        })
        .collect();
    if process_envs.is_empty() {
        return String::from(
            "# pocopine: no processes declared; nothing to build for fullstack mode\n",
        );
    }

    let project_dir = if spec.workspace_subpath.is_empty() {
        "/app".to_owned()
    } else {
        format!("/app/{}", spec.workspace_subpath)
    };

    DockerfileTemplate {
        package_name: spec.package_name.as_str(),
        project_dir,
        static_files: spec.static_files.as_slice(),
        process_envs,
        has_rust_toolchain: spec.has_rust_toolchain,
    }
    .render()
    .expect("template render")
}

#[derive(Template)]
#[template(path = "Dockerfile.tmpl", escape = "none")]
struct DockerfileTemplate<'a> {
    package_name: &'a str,
    project_dir: String,
    static_files: &'a [String],
    process_envs: Vec<DockerfileProcEnv<'a>>,
    has_rust_toolchain: bool,
}

struct DockerfileProcEnv<'a> {
    env_name: String,
    bin: &'a str,
}

/// `("PORT", port)` for a public process with a declared port — every
/// adapter injects this so the app's bind and the host's ingress agree
/// on the same value. Returns `None` for private procs (no ingress).
pub fn port_env(proc: &ProcessSpec) -> Option<(String, String)> {
    let port = proc.port?;
    proc.is_public().then(|| ("PORT".into(), port.to_string()))
}

/// `web` → `POCOPINE_PROC_WEB`. Must agree with
/// `pocopine-launcher::env_var_name` — the two crates encode the same
/// rule and drift here breaks process dispatch.
pub fn process_env_var_name(process: &str) -> String {
    let normalised: String = process
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect();
    format!("POCOPINE_PROC_{normalised}")
}

/// Find process names that collide under [`process_env_var_name`].
/// The launcher's env-var dispatch is keyed on that encoding, so any
/// two names that normalise to the same key would silently exec each
/// other's binary (Docker's `ENV` keeps the later value).
///
/// Returns `(env_var_name, sorted_colliding_process_names)` for each
/// group of size ≥ 2; an empty vec means there are no collisions.
/// Adapters surface these as `Constraint::Refuse` in `detect_constraints`.
pub fn process_env_collisions(spec: &DeploySpec) -> Vec<(String, Vec<String>)> {
    use std::collections::BTreeMap;
    let mut by_env: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for (name, _) in spec.processes() {
        let env = process_env_var_name(name);
        by_env.entry(env).or_default().push(name.to_owned());
    }
    by_env
        .into_iter()
        .filter_map(|(env, mut names)| {
            if names.len() < 2 {
                return None;
            }
            names.sort();
            Some((env, names))
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{ProcessSpec, Scale};
    use std::collections::BTreeMap;

    fn spec_with_processes(processes: &[(&str, &str)]) -> DeploySpec {
        let mut map = BTreeMap::new();
        for (name, bin) in processes {
            map.insert(
                (*name).to_owned(),
                ProcessSpec {
                    bin: (*bin).to_owned(),
                    port: None,
                    healthcheck: None,
                    scale: Scale { min: 1, max: 1 },
                    public: None,
                },
            );
        }
        DeploySpec {
            app_name: "app".into(),
            package_name: "app".into(),
            git_sha: "sha".into(),
            git_remote: None,
            mode: crate::Mode::Fullstack,
            processes: map,
            services: Default::default(),
            env: Default::default(),
            host_overrides: Default::default(),
            uses_jobs: false,
            uses_collab: false,
            uses_storage: false,
            uses_websocket: false,
            first_deploy: false,
            skip_build: false,
            environment: None,
            workspace_subpath: String::new(),
            has_rust_toolchain: false,
            static_files: vec!["index.html".into(), "pkg".into()],
            build_dir: None,
        }
    }

    #[test]
    fn process_env_var_name_matches_launcher() {
        assert_eq!(process_env_var_name("web"), "POCOPINE_PROC_WEB");
        assert_eq!(process_env_var_name("my-api"), "POCOPINE_PROC_MY_API");
    }

    #[test]
    fn render_dockerfile_emits_one_env_per_process() {
        let spec = spec_with_processes(&[("web", "server"), ("worker", "worker")]);
        let dockerfile = render_dockerfile(&spec);
        assert!(dockerfile.contains("ENV POCOPINE_PROC_WEB=/usr/local/bin/server"));
        assert!(dockerfile.contains("ENV POCOPINE_PROC_WORKER=/usr/local/bin/worker"));
    }

    #[test]
    fn render_dockerfile_handles_custom_process_name_with_distinct_bin() {
        let spec = spec_with_processes(&[("web", "server"), ("scheduler", "scheduler-bin")]);
        let dockerfile = render_dockerfile(&spec);
        assert!(dockerfile.contains("--bin scheduler-bin"));
        assert!(dockerfile.contains(
            "COPY --from=build /app/target/release/scheduler-bin /usr/local/bin/scheduler-bin"
        ));
        assert!(dockerfile.contains("ENV POCOPINE_PROC_SCHEDULER=/usr/local/bin/scheduler-bin"));
    }

    #[test]
    fn render_dockerfile_empty_processes_emits_placeholder() {
        let spec = spec_with_processes(&[]);
        let dockerfile = render_dockerfile(&spec);
        assert!(dockerfile.contains("no processes declared"));
    }

    #[test]
    fn render_dockerfile_copies_index_html_and_pkg_not_dist() {
        let spec = spec_with_processes(&[("web", "server")]);
        let dockerfile = render_dockerfile(&spec);
        assert!(dockerfile.contains("/app/index.html /var/lib/pocopine/dist/index.html"));
        assert!(dockerfile.contains("/app/pkg /var/lib/pocopine/dist/pkg"));
        assert!(!dockerfile.contains("/app/dist "));
    }

    #[test]
    fn render_dockerfile_scopes_cargo_build_to_the_project_package() {
        let mut spec = spec_with_processes(&[("web", "server")]);
        spec.package_name = "keep-example".into();
        let dockerfile = render_dockerfile(&spec);
        assert!(dockerfile.contains(
            "cargo build --release -p keep-example --bin server -p pocopine-launcher --bin pocopine-launcher"
        ));
    }

    #[test]
    fn render_dockerfile_honors_custom_static_files() {
        let mut spec = spec_with_processes(&[("web", "server")]);
        spec.static_files = vec![
            "index.html".into(),
            "pkg".into(),
            "app.css".into(),
            "public".into(),
        ];
        let dockerfile = render_dockerfile(&spec);
        assert!(dockerfile.contains("/app/app.css /var/lib/pocopine/dist/app.css"));
        assert!(dockerfile.contains("/app/public /var/lib/pocopine/dist/public"));
    }

    #[test]
    fn render_dockerfile_pre_installs_pinned_toolchain_when_present() {
        let mut spec = spec_with_processes(&[("web", "server")]);
        spec.has_rust_toolchain = true;
        let dockerfile = render_dockerfile(&spec);
        assert!(dockerfile.contains("COPY rust-toolchain.toml ."));
        assert!(dockerfile.contains("RUN rustup show"));
    }

    #[test]
    fn render_dockerfile_skips_toolchain_block_when_absent() {
        let spec = spec_with_processes(&[("web", "server")]);
        let dockerfile = render_dockerfile(&spec);
        assert!(!dockerfile.contains("rust-toolchain.toml"));
    }

    #[test]
    fn render_dockerfile_uses_workspace_subpath_for_workspace_members() {
        let mut spec = spec_with_processes(&[("web", "server")]);
        spec.workspace_subpath = "examples/keep".into();
        let dockerfile = render_dockerfile(&spec);
        assert!(
            dockerfile.contains("/app/examples/keep/index.html /var/lib/pocopine/dist/index.html")
        );
        assert!(dockerfile.contains("/app/examples/keep/pkg /var/lib/pocopine/dist/pkg"));
    }

    #[test]
    fn process_env_collisions_detects_underscore_hyphen_collision() {
        // `api-worker` and `api_worker` both encode to `POCOPINE_PROC_API_WORKER`.
        let spec = spec_with_processes(&[("api-worker", "a"), ("api_worker", "b")]);
        let collisions = process_env_collisions(&spec);
        assert_eq!(collisions.len(), 1);
        let (env, names) = &collisions[0];
        assert_eq!(env, "POCOPINE_PROC_API_WORKER");
        assert_eq!(
            names,
            &vec!["api-worker".to_owned(), "api_worker".to_owned()]
        );
    }

    #[test]
    fn process_env_collisions_empty_on_unique_names() {
        let spec = spec_with_processes(&[("web", "server"), ("worker", "worker")]);
        assert!(process_env_collisions(&spec).is_empty());
    }
}
