//! Shared helpers used by multiple adapters.

use crate::DeploySpec;

pub const DOCKERIGNORE: &str = "\
# Generated by pocopine-deploy (RFC 080). Safe to overwrite.
target/
node_modules/
.git/
.pocopine/
dist/
*.log
";

/// Marker string included at the top of every file pocopine renders.
/// The CLI checks for this before overwriting an existing file at the
/// same path, so hand-edited Dockerfiles / `fly.toml` / `.dockerignore`
/// don't get silently clobbered.
pub const GENERATED_MARKER: &str = "Generated by pocopine-deploy";

/// Multi-stage Dockerfile generator (RFC 080 §4.2 + §5.4). Identical
/// across full-stack adapters; only the host config file differs.
///
/// Emits one `ENV POCOPINE_PROC_<NAME>=/usr/local/bin/<bin>` per
/// declared process so the launcher (RFC 080 §5.3 + Phase 6) can
/// dispatch any process name without a code change.
pub fn render_dockerfile(spec: &DeploySpec) -> String {
    let procs: Vec<(&str, &str)> = spec
        .processes()
        .map(|(name, p)| (name, p.bin.as_str()))
        .collect();
    if procs.is_empty() {
        return String::from(
            "# pocopine: no processes declared; nothing to build for fullstack mode\n",
        );
    }

    let bin_args = procs
        .iter()
        .map(|(_, b)| format!("--bin {b}"))
        .collect::<Vec<_>>()
        .join(" ");
    let bin_copies = procs
        .iter()
        .map(|(_, b)| format!("COPY --from=build /app/target/release/{b} /usr/local/bin/{b}"))
        .collect::<Vec<_>>()
        .join("\n");
    let process_envs = procs
        .iter()
        .map(|(name, b)| format!("ENV {}=/usr/local/bin/{b}", process_env_var_name(name),))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        "# Generated by pocopine-deploy (RFC 080 §4.2 + §5.4). Do not hand-edit;\n\
         # changes go in Pocopine.toml [deploy] or the host-specific override\n\
         # block (e.g. [deploy.fly]). To pin this file as authoritative, set\n\
         # `[deploy.<host>] generated = \"freeze\"` in Pocopine.toml (§7).\n\
         \n\
         FROM rust:1.84-slim-bookworm AS build\n\
         WORKDIR /app\n\
         COPY . .\n\
         RUN cargo build --release {bin_args} --bin pocopine-launcher\n\
         \n\
         FROM gcr.io/distroless/cc-debian12\n\
         {bin_copies}\n\
         COPY --from=build /app/target/release/pocopine-launcher /usr/local/bin/pocopine-launcher\n\
         COPY --from=build /app/dist /var/lib/pocopine/dist\n\
         ENV POCOPINE_DIST=/var/lib/pocopine/dist\n\
         {process_envs}\n\
         ENTRYPOINT [\"pocopine-launcher\"]\n"
    )
}

/// `web` → `POCOPINE_PROC_WEB`, `my-api` → `POCOPINE_PROC_MY_API`.
/// Matches `pocopine-launcher`'s `env_var_name` exactly — the two must
/// agree on the encoding or process dispatch breaks. The function is
/// defined here so adapters can mention the env-var name in error
/// messages without duplicating the rule.
pub fn process_env_var_name(process: &str) -> String {
    let normalised: String = process
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect();
    format!("POCOPINE_PROC_{normalised}")
}

/// Find process names that collide under [`process_env_var_name`].
/// The launcher's env-var dispatch is keyed on that encoding, so any
/// two names that normalise to the same key would silently exec each
/// other's binary (Docker's `ENV` keeps the later value).
///
/// Returns `(env_var_name, sorted_colliding_process_names)` for each
/// group of size ≥ 2; an empty vec means there are no collisions.
/// Adapters surface these as `Constraint::Refuse` in `detect_constraints`.
pub fn process_env_collisions(spec: &DeploySpec) -> Vec<(String, Vec<String>)> {
    use std::collections::BTreeMap;
    let mut by_env: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for (name, _) in spec.processes() {
        let env = process_env_var_name(name);
        by_env.entry(env).or_default().push(name.to_owned());
    }
    by_env
        .into_iter()
        .filter_map(|(env, mut names)| {
            if names.len() < 2 {
                return None;
            }
            names.sort();
            Some((env, names))
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{ProcessSpec, Scale};
    use std::collections::BTreeMap;

    fn spec_with_processes(processes: &[(&str, &str)]) -> DeploySpec {
        let mut map = BTreeMap::new();
        for (name, bin) in processes {
            map.insert(
                (*name).to_owned(),
                ProcessSpec {
                    bin: (*bin).to_owned(),
                    port: None,
                    healthcheck: None,
                    scale: Scale { min: 1, max: 1 },
                    public: None,
                },
            );
        }
        DeploySpec {
            app_name: "app".into(),
            git_sha: "sha".into(),
            git_remote: None,
            mode: crate::Mode::Fullstack,
            processes: map,
            services: Default::default(),
            env: Default::default(),
            host_overrides: Default::default(),
            uses_jobs: false,
            uses_collab: false,
            uses_storage: false,
            uses_websocket: false,
            first_deploy: false,
            skip_build: false,
            environment: None,
        }
    }

    #[test]
    fn process_env_var_name_matches_launcher() {
        // Must agree with pocopine-launcher::env_var_name — the
        // launcher reads what render_dockerfile writes.
        assert_eq!(process_env_var_name("web"), "POCOPINE_PROC_WEB");
        assert_eq!(process_env_var_name("my-api"), "POCOPINE_PROC_MY_API");
    }

    #[test]
    fn render_dockerfile_emits_one_env_per_process() {
        let spec = spec_with_processes(&[("web", "server"), ("worker", "worker")]);
        let dockerfile = render_dockerfile(&spec);
        assert!(dockerfile.contains("ENV POCOPINE_PROC_WEB=/usr/local/bin/server"));
        assert!(dockerfile.contains("ENV POCOPINE_PROC_WORKER=/usr/local/bin/worker"));
    }

    #[test]
    fn render_dockerfile_handles_custom_process_name_with_distinct_bin() {
        let spec = spec_with_processes(&[("web", "server"), ("scheduler", "scheduler-bin")]);
        let dockerfile = render_dockerfile(&spec);
        assert!(dockerfile.contains("--bin scheduler-bin"));
        assert!(dockerfile.contains(
            "COPY --from=build /app/target/release/scheduler-bin /usr/local/bin/scheduler-bin"
        ));
        assert!(dockerfile.contains("ENV POCOPINE_PROC_SCHEDULER=/usr/local/bin/scheduler-bin"));
    }

    #[test]
    fn render_dockerfile_empty_processes_emits_placeholder() {
        let spec = spec_with_processes(&[]);
        let dockerfile = render_dockerfile(&spec);
        assert!(dockerfile.contains("no processes declared"));
    }

    #[test]
    fn process_env_collisions_detects_underscore_hyphen_collision() {
        // Both `api-worker` and `api_worker` encode to
        // `POCOPINE_PROC_API_WORKER`, which would clobber.
        let spec = spec_with_processes(&[("api-worker", "a"), ("api_worker", "b")]);
        let collisions = process_env_collisions(&spec);
        assert_eq!(collisions.len(), 1);
        let (env, names) = &collisions[0];
        assert_eq!(env, "POCOPINE_PROC_API_WORKER");
        assert_eq!(
            names,
            &vec!["api-worker".to_owned(), "api_worker".to_owned()]
        );
    }

    #[test]
    fn process_env_collisions_empty_on_unique_names() {
        let spec = spec_with_processes(&[("web", "server"), ("worker", "worker")]);
        assert!(process_env_collisions(&spec).is_empty());
    }
}
