//! Typed, target-independent semantic node descriptors.
//!
//! These types describe the persisted meaning of an extension node. Browser
//! node views and wire-version materialization build on this module, but this
//! module itself has no DOM, wasm, or Pocopine dependency.

use std::any::TypeId;
use std::error::Error;
use std::fmt;

use serde::de::DeserializeOwned;
use serde::{Deserialize, Serialize};

use crate::model::{Attrs, Mark, NodeSpec};

/// A closed serde object-map contract for one semantic node's attributes.
///
/// Implementations are generated by `#[derive(RichTextNodeAttrs)]`. `KEYS`
/// contains the emitted wire keys after applying supported serde renames.
pub trait RichTextNodeAttrs:
    Serialize + DeserializeOwned + Clone + PartialEq + Send + Sync + 'static
{
    /// Complete closed set of serde wire keys, in struct declaration order.
    const KEYS: &'static [&'static str];
}

/// Target-independent identity and schema for one semantic rich-text node.
pub trait RichTextNodeType: Send + Sync + 'static {
    /// Stable persisted node type name.
    const NAME: &'static str;
    /// Current persisted schema version. Typed nodes start at version 1.
    const VERSION: u32;
    /// Complete typed attribute map owned by this semantic node.
    type Attrs: RichTextNodeAttrs;

    /// Schema shape contributed for this node.
    fn spec() -> NodeSpec;

    /// Ordered one-version-at-a-time wire migrations.
    fn migrations() -> &'static [NodeMigration] {
        &[]
    }
}

/// Schema-independent node representation passed through migrations.
///
/// It intentionally is not integrated into [`crate::model::Node`]'s JSON
/// implementation yet. Keeping it separate lets migrations inspect and
/// rewrite old data before schema materialization is attempted.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WireNode {
    /// Persisted semantic node type discriminator.
    #[serde(rename = "type")]
    pub name: String,
    /// Persisted typed-node schema version. `None` represents legacy or
    /// built-in unversioned data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version: Option<u32>,
    /// Raw node attributes, deliberately not typed until after migration.
    #[serde(default, skip_serializing_if = "Attrs::is_empty")]
    pub attrs: Attrs,
    /// Marks attached to this node.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub marks: Vec<Mark>,
    /// Raw child nodes.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub content: Vec<WireNode>,
    /// Text payload for text nodes.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    /// Leaf metadata carried by the existing node JSON shape.
    #[serde(default)]
    pub leaf: bool,
}

impl WireNode {
    /// Construct an empty wire node with the given semantic name and version.
    pub fn new(name: impl Into<String>, version: Option<u32>) -> Self {
        Self {
            name: name.into(),
            version,
            attrs: Attrs::new(),
            marks: Vec::new(),
            content: Vec::new(),
            text: None,
            leaf: false,
        }
    }

    /// Borrow the semantic node type name.
    pub fn type_name(&self) -> &str {
        &self.name
    }
}

/// One explicit transition between adjacent semantic wire versions.
#[derive(Clone, Copy, Debug)]
pub struct NodeMigration {
    /// Version accepted by this migration.
    pub from: u32,
    /// Version produced by this migration.
    pub to: u32,
    /// Pure migration callback. Runtime validation later verifies that the
    /// returned node retained its semantic type and produced `to`.
    pub apply: fn(WireNode) -> Result<WireNode, NodeMigrationError>,
}

impl NodeMigration {
    /// Construct a migration descriptor.
    pub const fn new(
        from: u32,
        to: u32,
        apply: fn(WireNode) -> Result<WireNode, NodeMigrationError>,
    ) -> Self {
        Self { from, to, apply }
    }
}

/// Error returned by an extension-provided wire migration.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NodeMigrationError {
    message: String,
}

impl NodeMigrationError {
    /// Create an error with an extension-facing diagnostic message.
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }

    /// Borrow the diagnostic message.
    pub fn message(&self) -> &str {
        &self.message
    }
}

impl fmt::Display for NodeMigrationError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.message)
    }
}

impl Error for NodeMigrationError {}

/// Type-erased semantic descriptor retained by an editor runtime.
#[derive(Clone, Debug)]
pub struct TypedNodeSpec {
    semantic_type_id: TypeId,
    semantic_rust_type: &'static str,
    name: &'static str,
    version: u32,
    attr_keys: &'static [&'static str],
    spec: NodeSpec,
    migrations: &'static [NodeMigration],
    decode_attrs: fn(&Attrs) -> Result<(), TypedNodeAttrsError>,
}

impl TypedNodeSpec {
    /// Erase a semantic marker after Rust has proved its complete typed attrs
    /// and schema contract.
    pub fn of<N: RichTextNodeType>() -> Self {
        Self {
            semantic_type_id: TypeId::of::<N>(),
            semantic_rust_type: std::any::type_name::<N>(),
            name: N::NAME,
            version: N::VERSION,
            attr_keys: N::Attrs::KEYS,
            spec: N::spec(),
            migrations: N::migrations(),
            decode_attrs: decode_attrs::<N>,
        }
    }

    /// Exact Rust semantic marker identity.
    pub fn semantic_type_id(&self) -> TypeId {
        self.semantic_type_id
    }

    /// Fully qualified Rust semantic marker name, for diagnostics only.
    pub fn semantic_rust_type(&self) -> &'static str {
        self.semantic_rust_type
    }

    /// Stable persisted semantic node name.
    pub fn name(&self) -> &'static str {
        self.name
    }

    /// Current persisted schema version.
    pub fn version(&self) -> u32 {
        self.version
    }

    /// Complete closed serde wire-key set.
    pub fn attr_keys(&self) -> &'static [&'static str] {
        self.attr_keys
    }

    /// Untyped model schema shape contributed by the semantic descriptor.
    pub fn spec(&self) -> &NodeSpec {
        &self.spec
    }

    /// Declared wire migrations.
    pub fn migrations(&self) -> &'static [NodeMigration] {
        self.migrations
    }

    /// Reject unknown same-version keys and prove that known attrs decode as
    /// this semantic node's concrete `Attrs` type.
    pub fn validate_attrs(&self, attrs: &Attrs) -> Result<(), TypedNodeAttrsError> {
        (self.decode_attrs)(attrs)
    }
}

fn decode_attrs<N: RichTextNodeType>(attrs: &Attrs) -> Result<(), TypedNodeAttrsError> {
    if let Some(key) = attrs
        .keys()
        .find(|key| !N::Attrs::KEYS.contains(&key.as_str()))
    {
        return Err(TypedNodeAttrsError::UnknownKey {
            node_type: N::NAME,
            key: key.clone(),
        });
    }

    let value = serde_json::to_value(attrs).map_err(|source| TypedNodeAttrsError::Decode {
        node_type: N::NAME,
        source,
    })?;
    serde_json::from_value::<N::Attrs>(value)
        .map(|_| ())
        .map_err(|source| TypedNodeAttrsError::Decode {
            node_type: N::NAME,
            source,
        })
}

/// Failure to validate a wire attr map against a typed semantic descriptor.
#[derive(Debug)]
pub enum TypedNodeAttrsError {
    /// A same-version key is outside the derive-generated closed set.
    UnknownKey {
        /// Semantic node type being decoded.
        node_type: &'static str,
        /// Unexpected wire key.
        key: String,
    },
    /// The closed map did not decode into the concrete Rust attrs type.
    Decode {
        /// Semantic node type being decoded.
        node_type: &'static str,
        /// Serde decoding failure.
        source: serde_json::Error,
    },
}

impl fmt::Display for TypedNodeAttrsError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::UnknownKey { node_type, key } => {
                write!(
                    formatter,
                    "typed node `{node_type}` has unknown attr `{key}`"
                )
            }
            Self::Decode { node_type, source } => {
                write!(
                    formatter,
                    "typed node `{node_type}` attrs failed to decode: {source}"
                )
            }
        }
    }
}

impl Error for TypedNodeAttrsError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::UnknownKey { .. } => None,
            Self::Decode { source, .. } => Some(source),
        }
    }
}
