[package]
name = "tailwind-demo"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.pocopine]
port = 3005

[package.metadata.pocopine.tailwind]
input = "app.css"
output = "pkg/tailwind.css"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pocopine = { path = "../../crates/pocopine" }
wasm-bindgen = { workspace = true }
serde = { workspace = true }
