use std::{collections::BTreeMap, fmt::Write};

use super::{Compilation, MessageSignature};
use crate::{ArgumentKind, CatalogAudience, Locales};

/// Generated source for OUT_DIR/pocopine_locale.rs. Include once at crate root;
/// it exposes `t::module::message(locale, arguments...)`. Host catalog bytes are
/// inside a host-gated module and never enter the wasm translation module.
pub fn generate_rust(
    compilation: &Compilation,
    locales: &Locales,
    runtime_path: &str,
) -> Result<String, String> {
    if compilation.has_errors() {
        return Err("cannot generate Rust from a failed catalog compilation".into());
    }
    let build_id = compilation
        .build_id
        .as_deref()
        .ok_or("compiled catalogs have no build ID")?;
    let path: syn::Path = syn::parse_str(runtime_path)
        .map_err(|error| format!("invalid locale runtime path: {error}"))?;
    if path
        .segments
        .iter()
        .any(|segment| !matches!(segment.arguments, syn::PathArguments::None))
    {
        return Err("locale runtime path cannot contain generic arguments".into());
    }
    let first = path
        .segments
        .first()
        .ok_or("locale runtime path is empty")?
        .ident
        .to_string();
    if first == "self" || first == "super" {
        return Err("locale runtime path must be crate-relative or absolute".into());
    }
    let runtime_path = if path.leading_colon.is_some() || first == "crate" {
        runtime_path.to_owned()
    } else {
        format!("::{runtime_path}")
    };
    // Isolate runtime imports/types from application message namespaces.
    let mut state_module = "__state".to_owned();
    while compilation
        .messages
        .keys()
        .any(|key| key.split('.').next() == Some(state_module.as_str()))
    {
        state_module.push('_');
    }
    let mut source = String::from(
        "// Generated by Pocopine locale. Do not edit.\n#[allow(non_snake_case)]\npub mod t {\n",
    );
    let mut defaults = BTreeMap::new();
    for catalog in &compilation.catalogs {
        if catalog.artifact.locale == *locales.default_locale()
            && catalog.artifact.audience == CatalogAudience::Host
        {
            for (key, signature) in &compilation.messages {
                if let Some(Some(entry)) = catalog.artifact.messages.get(signature.id.0 as usize) {
                    defaults.insert(key.clone(), entry.message.clone());
                }
            }
        }
    }
    for audience in [CatalogAudience::Host, CatalogAudience::Browser] {
        writeln!(
            source,
            "#[cfg({})] mod __platform {{",
            if audience == CatalogAudience::Host {
                "not(target_arch = \"wasm32\")"
            } else {
                "target_arch = \"wasm32\""
            }
        )
        .unwrap();
        writeln!(source,"mod {state_module} {{\nuse {runtime_path} as __runtime;\npub const BUILD_ID: &str = {build_id:?};\npub const MESSAGE_COUNT: usize = {};",compilation.messages.len()).unwrap();
        if audience == CatalogAudience::Host {
            host_state(&mut source, compilation, locales)?;
        } else {
            client_state(&mut source);
        }
        writeln!(source, "}}\npub use self::{state_module}::*;").unwrap();
        let mut tree = Module::default();
        for (key, signature) in &compilation.messages {
            if (audience == CatalogAudience::Host || signature.browser)
                && signature.elements.is_empty()
            {
                tree.insert(
                    &key.split('.').collect::<Vec<_>>(),
                    signature,
                    defaults.get(key).map(String::as_str).unwrap_or(""),
                );
            }
        }
        tree.emit(&mut source, 0, &runtime_path)?;
        source.push_str("}\n");
    }
    source.push_str("pub use __platform::*;\n}\n");
    syn::parse_file(&source).map_err(|error| format!("invalid generated locale Rust: {error}"))?;
    Ok(source)
}

fn host_state(
    out: &mut String,
    compilation: &Compilation,
    locales: &Locales,
) -> Result<(), String> {
    out.push_str("static CATALOGS: std::sync::OnceLock<__runtime::server::ServerCatalogs> = std::sync::OnceLock::new();\n");
    out.push_str("/// Prepare all embedded host catalogs before starting requests or jobs.\npub fn initialize() -> Result<(), __runtime::TranslationError> {\nif CATALOGS.get().is_some() { return Ok(()); }\n");
    writeln!(out,"let locales = __runtime::Locales::new(__runtime::Locale::parse({:?}).expect(\"generated locale\"), [",locales.default_locale().as_str()).unwrap();
    for locale in locales.supported() {
        writeln!(
            out,
            "__runtime::Locale::parse({:?}).expect(\"generated locale\"),",
            locale.as_str()
        )
        .unwrap();
    }
    out.push_str("]).expect(\"generated locale set\");\nlet catalogs = __runtime::server::ServerCatalogs::load(locales, BUILD_ID, MESSAGE_COUNT, [\n");
    for catalog in &compilation.catalogs {
        if catalog.artifact.audience == CatalogAudience::Host {
            let bytes = std::str::from_utf8(&catalog.bytes).map_err(|e| e.to_string())?;
            writeln!(
                out,
                "(__runtime::Locale::parse({:?}).expect(\"generated locale\"), {:?}.as_bytes()),",
                catalog.artifact.locale.as_str(),
                bytes
            )
            .unwrap();
        }
    }
    out.push_str("])?;\nlet _ = CATALOGS.set(catalogs);\nOk(())\n}\n");
    out.push_str("#[doc(hidden)] pub fn __format(locale: &__runtime::Locale, id: u32, args: &[(&str, __runtime::Value<'_>)]) -> Result<String, __runtime::TranslationError> {\nCATALOGS.get().ok_or(__runtime::TranslationError::NotInitialized)?.format(locale, __runtime::MessageId(id), args)\n}\n");
    out.push_str("#[doc(hidden)] pub fn __render(locale: &__runtime::Locale, id: u32, args: &[(&str, __runtime::Value<'_>)]) -> Result<Vec<__runtime::RenderedPart>, __runtime::TranslationError> {\nCATALOGS.get().ok_or(__runtime::TranslationError::NotInitialized)?.render(locale, __runtime::MessageId(id), args)\n}\n");
    Ok(())
}

fn client_state(out: &mut String) {
    out.push_str("std::thread_local! { static CATALOGS: std::cell::RefCell<Option<__runtime::client::ClientCatalogs>> = const { std::cell::RefCell::new(None) }; }\n");
    out.push_str("/// Initialize with the locale configuration delivered by the matching build.\npub fn initialize(locales: __runtime::Locales) -> Result<(), __runtime::TranslationError> { CATALOGS.with(|slot| {\nlet mut slot = slot.borrow_mut();\nif let Some(existing) = slot.as_ref() {\nif existing.locales() == &locales { return Ok(()); }\nreturn Err(__runtime::TranslationError::Initialization(\"locale runtime already has different configuration\".into()));\n}\n*slot = Some(__runtime::client::ClientCatalogs::new(locales, BUILD_ID, MESSAGE_COUNT)?);\nOk(())\n}) }\n");
    out.push_str("/// Install a fetched catalog before committing the corresponding UI locale.\npub fn install(locale: __runtime::Locale, bytes: &[u8]) -> Result<(), __runtime::TranslationError> {\nCATALOGS.with(|slot| slot.borrow_mut().as_mut().ok_or(__runtime::TranslationError::NotInitialized)?.install(locale, bytes))\n}\n");
    out.push_str("/// Share the generated API's cache with the browser locale controller.\npub fn catalogs() -> Result<__runtime::client::ClientCatalogs, __runtime::TranslationError> {\nCATALOGS.with(|slot| slot.borrow().as_ref().cloned().ok_or(__runtime::TranslationError::NotInitialized))\n}\n");
    out.push_str("#[doc(hidden)] pub fn __format(locale: &__runtime::Locale, id: u32, args: &[(&str, __runtime::Value<'_>)]) -> Result<String, __runtime::TranslationError> {\nCATALOGS.with(|slot| slot.borrow().as_ref().ok_or(__runtime::TranslationError::NotInitialized)?.format(locale, __runtime::MessageId(id), args))\n}\n");
    out.push_str("#[doc(hidden)] pub fn __render(locale: &__runtime::Locale, id: u32, args: &[(&str, __runtime::Value<'_>)]) -> Result<Vec<__runtime::RenderedPart>, __runtime::TranslationError> {\nCATALOGS.with(|slot| slot.borrow().as_ref().ok_or(__runtime::TranslationError::NotInitialized)?.catalog(locale)?.render(__runtime::MessageId(id), args))\n}\n");
}

#[derive(Default)]
struct Module<'a> {
    modules: BTreeMap<String, Module<'a>>,
    functions: BTreeMap<String, (&'a MessageSignature, &'a str)>,
}
impl<'a> Module<'a> {
    fn insert(&mut self, parts: &[&str], signature: &'a MessageSignature, default: &'a str) {
        if parts.len() == 1 {
            self.functions.insert(parts[0].into(), (signature, default));
        } else if let Some(first) = parts.first() {
            self.modules.entry((*first).into()).or_default().insert(
                &parts[1..],
                signature,
                default,
            );
        }
    }
    fn emit(&self, out: &mut String, depth: usize, runtime: &str) -> Result<(), String> {
        for (name, (signature, default)) in &self.functions {
            // Catalog names are identifiers; raw identifiers also cover Rust
            // keywords without inventing a second catalog-key spelling.
            let ident = rust_ident(name)?;
            let mut locale_arg = "__locale".to_owned();
            while signature.arguments.contains_key(&locale_arg) {
                locale_arg.push('_');
            }
            let mut parameters = BTreeMap::new();
            for (index, name) in signature.arguments.keys().enumerate() {
                let parameter = match rust_ident(name) {
                    Ok(ident) => ident,
                    Err(_) => {
                        let mut replacement = format!("__arg_{index}");
                        while signature.arguments.contains_key(&replacement)
                            || replacement == locale_arg
                        {
                            replacement.push('_');
                        }
                        replacement
                    }
                };
                parameters.insert(name, parameter);
            }
            writeln!(
                out,
                "#[doc = {default:?}]\npub fn {ident}({locale_arg}: {runtime}::Locale,"
            )
            .unwrap();
            for (name, kind) in &signature.arguments {
                let ty = match kind {
                    ArgumentKind::Text => "&str".into(),
                    ArgumentKind::Number => format!("{runtime}::PluralArg"),
                    ArgumentKind::DateTime => format!("{runtime}::DateTimeArg"),
                };
                writeln!(out, "{}: {ty},", parameters[name]).unwrap();
            }
            writeln!(
                out,
                ") -> ::std::string::String {{\n{}__format(&{locale_arg}, {}, &[",
                "super::".repeat(depth),
                signature.id.0
            )
            .unwrap();
            for (name, kind) in &signature.arguments {
                let ident = &parameters[name];
                let value = match kind {
                    ArgumentKind::Text => format!("Text({ident})"),
                    ArgumentKind::Number => format!("Number({ident})"),
                    ArgumentKind::DateTime => format!("DateTime(&{ident})"),
                };
                writeln!(out, "({name:?}, {runtime}::Value::{value}),").unwrap();
            }
            out.push_str("]).expect(\"translation runtime must be initialized and its catalog contract valid\")\n}\n");
        }
        for (name, module) in &self.modules {
            writeln!(out, "pub mod {} {{", rust_ident(name)?).unwrap();
            module.emit(out, depth + 1, runtime)?;
            out.push_str("}\n");
        }
        Ok(())
    }
}
fn rust_ident(name: &str) -> Result<String, String> {
    let raw = format!("r#{name}");
    syn::parse_str::<syn::Ident>(&raw)
        .map_err(|error| format!("invalid generated identifier {name:?}: {error}"))?;
    Ok(raw)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::server::{CatalogSource, MessageReference, ReferenceKind, Span, compile_catalogs};
    #[test]
    fn generation_has_explicit_typed_arguments_and_separate_platform_modules() {
        let locales = Locales::new("en".parse().unwrap(), ["en".parse().unwrap()]).unwrap();
        let compilation=compile_catalogs(&locales,&[CatalogSource {locale:"en".parse().unwrap(),file:0,source:r#"{"cart.items":"{count, number} {at, date, short} {name}","auth.denied":"HOST_ONLY_SENTINEL","type.match":"Keyword {self} {__locale}"}"#.into()}],
            &[ ("cart.items","cart",CatalogAudience::Browser),("auth.denied","auth",CatalogAudience::Host),("type.match","type",CatalogAudience::Browser)]
                .map(|(key,module,audience)|MessageReference {key:key.into(),module:module.into(),audience,kind:ReferenceKind::Rust,span:Span::UNKNOWN}));
        assert!(!compilation.has_errors(), "{:?}", compilation.diagnostics);
        let generated = generate_rust(&compilation, &locales, "::pocopine_locale").unwrap();
        assert!(generated.contains("__locale: ::pocopine_locale::Locale"));
        assert!(generated.contains("r#at: ::pocopine_locale::DateTimeArg"));
        assert!(generated.contains("r#count: ::pocopine_locale::PluralArg"));
        assert!(generated.contains("r#name: &str"));
        let browser = generated
            .split("#[cfg(target_arch = \"wasm32\")]")
            .nth(1)
            .unwrap();
        assert!(!browser.contains("HOST_ONLY_SENTINEL"));
        assert!(!browser.contains("r#denied"));
        assert!(browser.contains("pub mod r#type"));
        assert_eq!(
            generate_rust(&compilation, &locales, "::pocopine_locale").unwrap(),
            generated
        );
    }
}
