[package]
name = "pocopine-client-build"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Cargo build-script helper for generated Pocopine client module bindings."

[dependencies]
anyhow = "1"
pocopine-client-codegen = { workspace = true }
