use crate::{CardinalRule, Locales};
use std::collections::BTreeSet;

/// Keep the checked-in predicates, with only configured tags and their rules.
/// Parent resolution remains complete for incoming negotiation preferences.
pub fn plural_data(locales: &Locales) -> Result<String, String> {
    let mut file =
        syn::parse_file(include_str!("../../generated.rs")).map_err(|e| e.to_string())?;
    file.attrs.clear();
    let tags: Vec<_> = locales.supported().map(|locale| locale.as_str()).collect();
    let rules: Vec<_> = locales
        .supported()
        .map(|locale| CardinalRule::for_locale(locale).id())
        .collect();
    let needed: BTreeSet<_> = rules
        .iter()
        .copied()
        .chain([crate::generated::OTHER_RULE])
        .collect();
    for item in &mut file.items {
        let syn::Item::Fn(function) = item else {
            continue;
        };
        if function.sig.ident == "category" {
            let Some(syn::Stmt::Expr(syn::Expr::Match(selection), _)) =
                function.block.stmts.first_mut()
            else {
                return Err("generated plural category shape changed".into());
            };
            selection.arms.retain(|arm| match &arm.pat {
                syn::Pat::Lit(syn::ExprLit {
                    lit: syn::Lit::Int(value),
                    ..
                }) => value
                    .base10_parse::<u8>()
                    .is_ok_and(|rule| needed.contains(&rule)),
                syn::Pat::Wild(_) => true,
                _ => false,
            });
            if needed.len() == 1 {
                let Some(syn::FnArg::Typed(argument)) = function.sig.inputs.iter_mut().nth(1)
                else {
                    return Err("generated plural operands changed".into());
                };
                *argument.pat = syn::parse_quote!(_a);
            }
        }
        if function.sig.ident == "rule_for_tag" {
            *function.block =
                syn::parse_quote!({ match tag { #(#tags => Some(#rules),)* _ => None } });
        }
    }
    Ok(format!(
        "// Configured CLDR subset; generated by Pocopine.\n{}\n",
        prettyplease::unparse(&file)
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use quote::quote;
    #[test]
    fn subset_retains_only_configured_tags_and_cardinal_predicates() {
        let locales = Locales::new(
            "en".parse().unwrap(),
            ["en", "fr-CA"].map(|s| s.parse().unwrap()),
        )
        .unwrap();
        let source = plural_data(&locales).unwrap();
        assert_eq!(source, plural_data(&locales).unwrap());
        let file = syn::parse_file(&source).unwrap();
        let function = |name: &str| {
            file.items
                .iter()
                .find_map(|item| match item {
                    syn::Item::Fn(f) if f.sig.ident == name => Some(f),
                    _ => None,
                })
                .unwrap()
        };
        let tags = function("rule_for_tag");
        let tags = quote!(#tags).to_string();
        assert!(tags.contains("\"en\"") && tags.contains("\"fr-CA\""));
        assert!(!tags.contains("\"de\"") && !tags.contains("\"ar\""));
        let syn::Stmt::Expr(syn::Expr::Match(selection), _) = &function("category").block.stmts[0]
        else {
            panic!("category match")
        };
        assert_eq!(selection.arms.len(), 4); // English, French, other and wildcard
        let japanese = Locales::new("ja".parse().unwrap(), ["ja".parse().unwrap()]).unwrap();
        assert!(plural_data(&japanese).unwrap().contains("_a"));
    }
}
