use std::collections::HashMap;
use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;

use pocopine_core::{ServerError, ServerResult};
use pocopine_events::SharedEventBackend;
use pocopine_server::auth::{Predicate, RequestContext};
use pocopine_server::axum::body::Body;
use pocopine_server::axum::extract::{FromRequest, State};
use pocopine_server::axum::http::Request;
use pocopine_server::axum::response::Json;
use pocopine_server::axum::routing::post;
use pocopine_server::{Server, ServerPlugin};
use serde::de::DeserializeOwned;
use serde_json::Value;

use crate::{
    sync_stream_tag, MigrationOutcome, SyncError, SyncOpenRequest, SyncOpenResponse,
    SyncOpenStream, SyncPullRequest, SyncPullResponse, SyncPushRequest, SyncPushResponse,
    SyncResult, SYNC_OPEN_PATH, SYNC_PULL_PATH, SYNC_PUSH_PATH,
};

/// Future returned by a stream source.
pub type SyncBoxFuture<'a, T> = Pin<Box<dyn Future<Output = SyncResult<T>> + Send + 'a>>;

/// Future returned by a stream guard.
pub type SyncGuardFuture<'a> = Pin<Box<dyn Future<Output = ServerResult<()>> + Send + 'a>>;

/// Server-side access check for a sync stream.
pub trait SyncStreamGuard: Send + Sync + 'static {
    /// Authorize one request before the stream source runs.
    fn check(&self, ctx: RequestContext) -> SyncGuardFuture<'_>;
}

impl<F, Fut> SyncStreamGuard for F
where
    F: Fn(RequestContext) -> Fut + Send + Sync + 'static,
    Fut: Future<Output = ServerResult<()>> + Send + 'static,
{
    fn check(&self, ctx: RequestContext) -> SyncGuardFuture<'_> {
        Box::pin((self)(ctx))
    }
}

struct PredicateStreamGuard<P>(P);

impl<P> SyncStreamGuard for PredicateStreamGuard<P>
where
    P: Predicate,
{
    fn check(&self, ctx: RequestContext) -> SyncGuardFuture<'_> {
        let result: ServerResult<()> = self.0.check(&ctx.user).into();
        Box::pin(async move { result })
    }
}

/// Server-side source for one registered sync stream.
///
/// The request context is passed into each source call after stream-level
/// authorization has succeeded. Sources still own tenant filtering, cursor
/// validation, and any per-row visibility rules.
pub trait SyncStreamSource: Send + Sync + 'static {
    /// Server-registered stream name.
    fn stream(&self) -> &crate::SyncStreamName;

    /// Public collection name represented by this stream.
    fn collection(&self) -> &crate::SyncCollectionName;

    /// Current cursor, if the source can cheaply report it.
    fn current_cursor(&self, ctx: &RequestContext) -> Option<crate::SyncCursor> {
        let _ = ctx;
        None
    }

    /// Application-level schema version for this stream's row/draft shape.
    ///
    /// Bump this whenever the row, draft, or payload shape changes in a way
    /// that older cached data or queued mutations cannot deserialize into.
    /// The version is advertised on every `/open` response so the client
    /// can detect mismatches and either drop its cache + queue (default
    /// from `SyncLocalStore::clear_stream`) or migrate via the opt-in
    /// `migrate_payload` path on this trait (shipping in a follow-up).
    ///
    /// Defaults to `1` — apps that never bump never need to think about
    /// this. Authors using `#[resource]` set this through the
    /// `schema_version = N` attribute; bare `SyncStreamSource` impls
    /// override this method directly.
    fn schema_version(&self) -> u32 {
        crate::protocol::default_schema_version_one()
    }

    /// Validate the subscription parameters sent by the client on
    /// `/open`, `/pull`, and `/push`.
    ///
    /// **Safe default:** any non-empty params map is rejected. Sources
    /// that have not declared a `params(...)` schema cannot know what
    /// the keys mean, so silently letting arbitrary params travel to
    /// `pull`/`push` would let a malicious client smuggle filter state
    /// the source has no contract for. Override this method (or use
    /// `#[resource(params(...))]`, which generates a typed validator)
    /// to opt into shape subscriptions.
    ///
    /// Sources generated by `#[resource(params(...))]` override this
    /// with a strongly-typed validator that:
    ///
    /// * Rejects unknown param keys (`InvalidValue { field, value }`).
    /// * Coerces each value into its declared comparator type
    ///   (`InSet<T>`, `Range<T>`, `Contains`, bare `T`, `Option<T>`).
    /// * Requires all non-`Option` params to be present.
    ///
    /// `Err` here surfaces as `BadRequest` via `server_error`; the
    /// open/pull/push handler rejects the request before invoking
    /// the source.
    fn validate_params(&self, params: &crate::StreamParams) -> SyncResult<()> {
        // The default validator accepts empty params AND
        // reserved-only params (keys prefixed with `__`). Reserved
        // keys carry framework-level metadata — `__order_by`,
        // `__limit`, etc. — that any source can safely ignore.
        // Sources that don't declare a shape should still pass for
        // wire envelopes that only carry reserved-key metadata.
        // Non-reserved keys still require an opt-in override.
        if params.keys().all(|k| k.starts_with("__")) {
            Ok(())
        } else {
            Err(SyncError::invalid_value(
                "params",
                "stream does not declare any subscription params (override SyncStreamSource::validate_params or use #[resource(params(...))])",
            ))
        }
    }

    /// Validate subscription parameters specifically for the `/push`
    /// endpoint. Defaults to [`validate_params`] so a single
    /// declaration governs `/open`, `/pull`, AND `/push` for sources
    /// that want strict shape validation everywhere.
    ///
    /// CRUD-style sources opt out of strict push validation by
    /// overriding this method to accept an empty `params` map (and
    /// only an empty map) — see `CrudResource::validate_push_params`.
    /// The rationale: generated CRUD `create`/`save`/`remove` writes
    /// don't know which subscription they belong to and the per-row
    /// tenant identity lives inside the mutation payload (see
    /// `docs/sync-shape-subscriptions.md`'s pitfalls). For shape-
    /// aware sources that DO require params on every push, the
    /// default keeps the strict gate.
    ///
    /// [`validate_params`]: SyncStreamSource::validate_params
    fn validate_push_params(&self, params: &crate::StreamParams) -> SyncResult<()> {
        self.validate_params(params)
    }

    /// Pull changes or a snapshot for this stream.
    fn pull<'a>(
        &'a self,
        ctx: RequestContext,
        request: SyncPullRequest,
    ) -> SyncBoxFuture<'a, SyncPullResponse<Value>>;

    /// Push client mutations for this stream.
    fn push<'a>(
        &'a self,
        ctx: RequestContext,
        request: SyncPushRequest<Value>,
    ) -> SyncBoxFuture<'a, SyncPushResponse<Value>> {
        let _ = ctx;
        let _ = request;
        Box::pin(async {
            Err(SyncError::unsupported(
                "push is not implemented for this stream",
            ))
        })
    }

    /// Migrate a client-side mutation payload encoded under `from` to
    /// the source's currently-advertised schema version `to`.
    ///
    /// The framework's `push_handler` invokes this once per mutation
    /// when the request's `schema_version` is **strictly less than**
    /// `self.schema_version()`. A newer client pushing to an older
    /// server (rolling-deploy edge case) is NOT routed through
    /// migration — the source receives the newer-shape payload as-is.
    ///
    /// The default implementation returns `SyncError::SchemaMigration`
    /// so any out-of-tree source that hasn't opted in surfaces a clean
    /// per-mutation rejection rather than silently mis-deserializing
    /// stale payloads into the new shape. Apps that want to accept
    /// stale pushes (e.g. to preserve side-effecting writes like
    /// payments across a schema bump) override this method directly or
    /// use the `#[resource(schema_version = N, migrate_with = path)]`
    /// macro attribute which generates the impl.
    ///
    /// On `Ok`, the framework stores the migrated payload alongside
    /// the original (via `ClientMutation::migration_outcome`) so the
    /// source can deserialize the migrated value while still keying
    /// its idempotency log on the original wire payload. On `Err`,
    /// the framework stores the error reason in the same sidecar —
    /// the source surfaces it as a per-mutation rejection ONLY for
    /// mutations not already in its idempotency log (a retry of an
    /// already-accepted mutation succeeds even if the migrator now
    /// rejects). See `ClientMutation::take_processing_payload`.
    ///
    /// **Envelope constraint.** This method migrates the
    /// `serde_json::Value` payload only — it CANNOT migrate the
    /// outer `ClientMutation` (`key`, `op`, `base_version`). For
    /// changes to row-key shape (e.g. ID rename), prefer the
    /// default drop-the-cache path: bump `schema_version`, let the
    /// client wipe pending mutations + canonical rows, and rebuild
    /// from `/pull`.
    fn migrate_payload<'a>(&'a self, from: u32, to: u32, value: Value) -> SyncBoxFuture<'a, Value> {
        let _ = value;
        let stream = self.stream().as_str().to_string();
        Box::pin(async move { Err(SyncError::schema_migration(stream, from, to)) })
    }

    /// Project a canonical row payload into the [`StreamParams`] that
    /// identify which subscribers care about it (RFC 088 §C).
    ///
    /// The server hashes the returned params and publishes the
    /// resulting invalidation to a per-(stream, params_hash) topic
    /// so only clients whose subscription params match wake up.
    /// Clients on the matching `(stream, params)` subscription
    /// compute the SAME hash and listen on the SAME topic — see
    /// [`crate::protocol::stream_params_hash`] for the contract.
    ///
    /// Default: empty params, equivalent to bare-topic publish only
    /// (backwards-compatible). The `#[query_resource]` macro
    /// auto-emits an override that projects each `#[query_param]`
    /// field into the params map; sources written by hand can
    /// override to opt into precise routing.
    ///
    /// The framework calls this AFTER the source's `push` returned
    /// `accepted` and the row has been persisted, so it sees the
    /// post-mutation row shape. A `None` return falls back to the
    /// bare-topic publish path (no per-params routing).
    ///
    /// Errors propagate up to `invalidate_stream_with_row`, which
    /// logs them via `tracing::warn!` and falls back to bare publish
    /// — a malformed row must NOT block the canonical write.
    fn row_to_params(&self, _row: &Value) -> SyncResult<crate::StreamParams> {
        Ok(crate::StreamParams::new())
    }
}

#[derive(Clone)]
struct RegisteredSyncStream {
    source: Arc<dyn SyncStreamSource>,
    guard: Option<Arc<dyn SyncStreamGuard>>,
}

impl RegisteredSyncStream {
    async fn authorize(&self, ctx: RequestContext) -> ServerResult<()> {
        if let Some(guard) = &self.guard {
            guard.check(ctx).await
        } else {
            Ok(())
        }
    }
}

#[derive(Clone)]
struct SyncServerInner {
    streams: Arc<HashMap<String, Arc<RegisteredSyncStream>>>,
    events: Option<SharedEventBackend>,
}

/// Host-side sync server service.
#[derive(Clone)]
pub struct SyncServer {
    inner: Arc<SyncServerInner>,
}

impl SyncServer {
    /// Start building a sync server.
    pub fn builder() -> SyncServerBuilder {
        SyncServerBuilder::default()
    }

    /// Return the live query tags this server can publish for streams.
    pub fn live_query_tags(&self) -> Vec<String> {
        self.inner
            .streams
            .keys()
            .map(|stream| sync_stream_tag(stream))
            .collect()
    }

    /// Return the live topics this server can publish for streams.
    pub fn live_topics(&self) -> pocopine_events::EventResult<Vec<pocopine_events::Topic>> {
        self.live_query_tags()
            .into_iter()
            .map(|tag| pocopine_live::query_tag_topic(&tag))
            .collect()
    }

    /// Return the live topic PREFIXES this server publishes against
    /// for each registered stream. Each prefix matches the bare
    /// topic AND every RFC 088 §C per-`(stream, params_hash)`
    /// variant: `query:sync:stream:{name}` covers `query:sync:stream:{name}`
    /// and `query:sync:stream:{name}:abc…`.
    ///
    /// Pair with [`pocopine_live::LiveHub::allow_topic_prefixes`]
    /// to permit clients to subscribe to per-params topics that the
    /// exact-match `allow_topics` couldn't accept (the hashes are
    /// computed at runtime, so the allowlist must be a prefix).
    pub fn live_topic_prefixes(&self) -> Vec<String> {
        self.live_query_tags()
            .into_iter()
            .map(|tag| format!("query:{tag}"))
            .collect()
    }

    /// Publish a live wake-up for one stream when an event backend is
    /// attached. The sync data still moves through pull; this only wakes
    /// browsers to pull with their current sync cursor.
    pub async fn invalidate_stream(&self, stream: &str) -> SyncResult<()> {
        let Some(events) = self.inner.events.as_ref() else {
            return Ok(());
        };
        let tag = sync_stream_tag(stream);
        let topic = pocopine_live::query_tag_topic(&tag)
            .map_err(|err| SyncError::backend(err.to_string()))?;
        let draft = pocopine_live::query_invalidated(topic, [tag])
            .map_err(|err| SyncError::backend(err.to_string()))?;
        events
            .publish(draft)
            .await
            .map_err(|err| SyncError::backend(err.to_string()))?;
        Ok(())
    }

    /// Publish a live wake-up scoped to the (stream, params_hash)
    /// audience the row's params identify (RFC 088 §C). Per-params
    /// ONLY — the caller is responsible for the bare-topic publish
    /// once per push (see the `/push` handler).
    ///
    /// If the stream's source overrides
    /// [`SyncStreamSource::row_to_params`] AND the projection
    /// returns non-empty params, publishes to
    /// `sync:stream:{stream}:{hash:016x}` so new clients listening
    /// on the per-params topic wake up. Sources that don't override
    /// (or that return empty params) make this a no-op — the
    /// caller's bare publish already reaches everyone.
    ///
    /// If `row_to_params` errors, the per-params publish is skipped
    /// and a `tracing::warn!` is emitted. The caller's bare publish
    /// (issued once per push, regardless of how many rows were
    /// accepted or whether any rows were returned) is the back-
    /// compat lifeline; a malformed row MUST NOT block it.
    pub async fn invalidate_stream_with_row(&self, stream: &str, row: &Value) -> SyncResult<()> {
        let Some(events) = self.inner.events.as_ref() else {
            return Ok(());
        };
        let registered = self.stream(stream)?;
        let params = match registered.source.row_to_params(row) {
            Ok(p) => p,
            Err(err) => {
                tracing::warn!(
                    target: "pocopine.log",
                    stream = stream,
                    error = %err,
                    "RFC 088 §C: row_to_params failed; skipping per-params publish",
                );
                return Ok(());
            }
        };
        if params.is_empty() {
            // Source doesn't override row_to_params, or this row
            // projects to no required partition keys. The caller's
            // bare publish already covers everyone.
            return Ok(());
        }
        let hash = crate::stream_params_hash(stream, &params);
        let params_tag = crate::sync_stream_params_tag(stream, hash);
        let params_topic = pocopine_live::query_tag_topic(&params_tag)
            .map_err(|err| SyncError::backend(err.to_string()))?;
        let params_draft = pocopine_live::query_invalidated(params_topic, [params_tag])
            .map_err(|err| SyncError::backend(err.to_string()))?;
        events
            .publish(params_draft)
            .await
            .map_err(|err| SyncError::backend(err.to_string()))?;
        Ok(())
    }

    /// Batched variant of [`Self::invalidate_stream_with_row`] —
    /// project each row in `rows` to its params, DEDUPLICATE by
    /// `(stream, params_hash)`, and publish ONCE per distinct hash.
    ///
    /// The dedup matters for bulk pushes: a single push that
    /// accepts N rows all belonging to the same workspace (or
    /// other partition) would otherwise issue N identical publishes
    /// to the same topic — wasting broker capacity and waking
    /// matching clients N times only for them to /pull-with-cursor
    /// N times (the second through Nth are no-ops, but each costs
    /// a round-trip). With dedup the same push issues one publish
    /// per distinct hash.
    ///
    /// Per-row `row_to_params` errors are logged via
    /// `tracing::warn!` and skipped; the rest of the batch still
    /// publishes. The bare-topic publish is the caller's
    /// responsibility (issued once per push regardless of row
    /// count), so partial per-params publish failures don't break
    /// back-compat clients.
    pub async fn invalidate_stream_with_rows<'a, I>(&self, stream: &str, rows: I) -> SyncResult<()>
    where
        I: IntoIterator<Item = &'a Value>,
    {
        let Some(events) = self.inner.events.as_ref() else {
            return Ok(());
        };
        let registered = self.stream(stream)?;
        let mut seen: std::collections::HashSet<u64> = std::collections::HashSet::new();
        for row in rows {
            let params = match registered.source.row_to_params(row) {
                Ok(p) => p,
                Err(err) => {
                    tracing::warn!(
                        target: "pocopine.log",
                        stream = stream,
                        error = %err,
                        "RFC 088 §C: row_to_params failed; skipping per-params publish for row",
                    );
                    continue;
                }
            };
            if params.is_empty() {
                continue;
            }
            let hash = crate::stream_params_hash(stream, &params);
            if !seen.insert(hash) {
                // Same partition already published in this batch.
                continue;
            }
            let params_tag = crate::sync_stream_params_tag(stream, hash);
            let params_topic = pocopine_live::query_tag_topic(&params_tag)
                .map_err(|err| SyncError::backend(err.to_string()))?;
            let params_draft = pocopine_live::query_invalidated(params_topic, [params_tag])
                .map_err(|err| SyncError::backend(err.to_string()))?;
            events
                .publish(params_draft)
                .await
                .map_err(|err| SyncError::backend(err.to_string()))?;
        }
        Ok(())
    }

    fn stream(&self, stream: &str) -> SyncResult<Arc<RegisteredSyncStream>> {
        self.inner
            .streams
            .get(stream)
            .cloned()
            .ok_or_else(|| SyncError::UnknownStream(stream.to_string()))
    }
}

/// Builder for [`SyncServer`].
#[derive(Default)]
pub struct SyncServerBuilder {
    streams: HashMap<String, Arc<RegisteredSyncStream>>,
    events: Option<SharedEventBackend>,
}

impl SyncServerBuilder {
    /// Register one explicitly public stream source.
    pub fn public_stream<S>(mut self, stream: S) -> Self
    where
        S: SyncStreamSource,
    {
        self.insert_stream(stream, None);
        self
    }

    /// Register one stream guarded by a sync auth predicate.
    pub fn guarded_stream<S, P>(mut self, stream: S, predicate: P) -> Self
    where
        S: SyncStreamSource,
        P: Predicate,
    {
        self.insert_stream(stream, Some(Arc::new(PredicateStreamGuard(predicate))));
        self
    }

    /// Register one stream guarded by an async request-context guard.
    pub fn guarded_stream_with<S, G>(mut self, stream: S, guard: G) -> Self
    where
        S: SyncStreamSource,
        G: SyncStreamGuard,
    {
        self.insert_stream(stream, Some(Arc::new(guard)));
        self
    }

    /// Attach the event backend shared with `pocopine-live`.
    pub fn events(mut self, events: SharedEventBackend) -> Self {
        self.events = Some(events);
        self
    }

    /// Finish the sync server.
    pub fn build(self) -> SyncServer {
        SyncServer {
            inner: Arc::new(SyncServerInner {
                streams: Arc::new(self.streams),
                events: self.events,
            }),
        }
    }

    fn insert_stream<S>(&mut self, stream: S, guard: Option<Arc<dyn SyncStreamGuard>>)
    where
        S: SyncStreamSource,
    {
        self.streams.insert(
            stream.stream().as_str().to_string(),
            Arc::new(RegisteredSyncStream {
                source: Arc::new(stream),
                guard,
            }),
        );
    }
}

/// Server plugin that mounts sync routes and provides [`SyncServer`].
///
/// Installing this plugin exposes `/__pocopine/sync/v1/open`, `/pull`, and
/// `/push` for every registered stream. Streams must be registered as either
/// explicitly public or guarded; there is no implicit public registration.
#[derive(Clone)]
pub struct SyncServerPlugin {
    sync: SyncServer,
}

/// Build a sync server plugin.
pub fn sync_server_plugin(sync: SyncServer) -> SyncServerPlugin {
    SyncServerPlugin { sync }
}

impl ServerPlugin for SyncServerPlugin {
    fn name(&self) -> &'static str {
        "pocopine-sync"
    }

    fn install(self, server: Server) -> Server {
        let sync = self.sync;
        server
            .provide_plugin(sync.clone())
            .route(SYNC_OPEN_PATH, post(open_handler).with_state(sync.clone()))
            .route(SYNC_PULL_PATH, post(pull_handler).with_state(sync.clone()))
            .route(SYNC_PUSH_PATH, post(push_handler).with_state(sync))
    }
}

async fn open_handler(
    State(sync): State<SyncServer>,
    request: Request<Body>,
) -> Json<ServerResult<SyncOpenResponse>> {
    Json(
        async {
            let (ctx, request) = parse_json_request::<SyncOpenRequest>(request).await?;
            open(sync, ctx, request).await
        }
        .await,
    )
}

async fn open(
    sync: SyncServer,
    ctx: RequestContext,
    request: SyncOpenRequest,
) -> ServerResult<SyncOpenResponse> {
    let mut streams = Vec::with_capacity(request.streams.len());
    for requested in request.streams {
        let stream = sync
            .stream(requested.stream.as_str())
            .map_err(server_error)?;
        stream.authorize(ctx.clone()).await?;
        // Run the source's `validate_params` after authorization so
        // params logic cannot be abused to bypass auth. Default impl
        // accepts anything; sources declaring `params(...)` via the
        // macro get a strongly-typed validator that rejects unknown
        // keys + wrong types.
        stream
            .source
            .validate_params(&requested.params)
            .map_err(server_error)?;
        streams.push(SyncOpenStream {
            stream: stream.source.stream().clone(),
            collection: stream.source.collection().clone(),
            cursor: stream.source.current_cursor(&ctx),
            schema_version: stream.source.schema_version(),
            params: requested.params,
        });
    }
    Ok(SyncOpenResponse::new(streams))
}

async fn pull_handler(
    State(sync): State<SyncServer>,
    request: Request<Body>,
) -> Json<ServerResult<SyncPullResponse<Value>>> {
    let result = async {
        let (ctx, request) = parse_json_request::<SyncPullRequest>(request).await?;
        let stream = sync.stream(request.stream.as_str()).map_err(server_error)?;
        stream.authorize(ctx.clone()).await?;
        // Pull-time params validation is ALWAYS strict (unlike push,
        // which is loose-on-empty). The /pull endpoint returns rows;
        // a parameterized source that lets an empty-params pull
        // through would return the unfiltered, auth-scoped view —
        // which is broader than any single subscription's filter and
        // is an exfiltration vector for shape-aware tenancy
        // (workspace_id, channel_id, etc). Sources that want to
        // accept empty-params pulls (e.g. CRUD post-push
        // reconciliation pulls) MUST override `validate_params` to
        // make the empty case explicit.
        stream
            .source
            .validate_params(&request.params)
            .map_err(server_error)?;
        stream.source.pull(ctx, request).await.map_err(server_error)
    }
    .await;
    Json(result)
}

async fn push_handler(
    State(sync): State<SyncServer>,
    request: Request<Body>,
) -> Json<ServerResult<SyncPushResponse<Value>>> {
    let result = async {
        let (ctx, mut request) = parse_json_request::<SyncPushRequest<Value>>(request).await?;
        // Reject malformed wire payloads up-front: `schema_version == 0`
        // is not a valid version (versions start at 1) and the macro,
        // builder, and `/open` response validators all reject it. Match
        // here so a malicious or buggy client can't tunnel through
        // `migrate_payload` with `from = 0`.
        if request.schema_version == 0 {
            return Err(server_error(SyncError::invalid_value(
                "schema_version",
                "must be >= 1 (schema versions start at 1)",
            )));
        }
        let stream = sync.stream(request.stream.as_str()).map_err(server_error)?;
        stream.authorize(ctx.clone()).await?;
        // Push-time params validation routes through the dedicated
        // `validate_push_params` trait method. Default impl delegates
        // to `validate_params` (strict). CRUD-style sources override
        // to accept the empty-params CRUD write case explicitly —
        // shape-aware out-of-tree sources keep the strict gate.
        stream
            .source
            .validate_push_params(&request.params)
            .map_err(server_error)?;
        let server_schema_version = stream.source.schema_version();
        // Reject `request.schema_version > server_schema_version` at
        // the wire layer. A newer client pushing to an older server
        // (rolling-deploy edge case) cannot safely fall through to
        // `source.push`: serde's default behaviour DROPS unknown
        // fields, so the older deserializer would silently accept a
        // newer-shape payload with fields missing. The client must
        // back off and retry; the durable queue stays intact thanks
        // to the typed error.
        if request.schema_version > server_schema_version {
            tracing::info!(
                target: "pocopine.log",
                stream = stream.source.stream().as_str(),
                request_schema_version = request.schema_version,
                server_schema_version,
                "sync push rejected: client schema_version newer than server (likely mid-deploy)"
            );
            return Err(server_error(SyncError::schema_migration(
                stream.source.stream().as_str().to_string(),
                request.schema_version,
                server_schema_version,
            )));
        }
        // When the client is on an OLDER schema version, attach a
        // per-mutation `migration_outcome` to each mutation. The
        // outcome is consumed by the source's `push`:
        //
        //   * `MigrationOutcome::Migrated(value)` — successful
        //     migration; the source applies the migrated value.
        //   * `MigrationOutcome::Failed { reason }` — the migrator
        //     rejected; the source surfaces the reason ONLY if its
        //     idempotency log doesn't already have this mutation_id+
        //     payload as accepted. This preserves replay-safety
        //     across migrator changes (e.g., a v1 mutation was
        //     accepted via a now-removed migrator; a retry from the
        //     same client hits the log and accepts despite the
        //     migrator no longer being registered).
        //
        // No pre-rejection happens at this layer — the source has
        // final say.
        if request.schema_version < server_schema_version {
            let from = request.schema_version;
            let to = server_schema_version;
            for mutation in request.mutations.iter_mut() {
                match stream
                    .source
                    .migrate_payload(from, to, mutation.payload.clone())
                    .await
                {
                    Ok(migrated) => {
                        mutation.migration_outcome = Some(MigrationOutcome::Migrated(migrated));
                    }
                    Err(err) => {
                        tracing::info!(
                            target: "pocopine.log",
                            stream = stream.source.stream().as_str(),
                            from,
                            to,
                            mutation_id = mutation.id.as_str(),
                            reason = %err,
                            "sync push migrate_payload failed; deferring to source idempotency check"
                        );
                        mutation.migration_outcome = Some(MigrationOutcome::Failed {
                            reason: err.to_string(),
                        });
                    }
                }
            }
            // NOTE: we deliberately leave `request.schema_version` as
            // the client's wire value. Custom `SyncStreamSource::push`
            // impls may consult it for logging/audit/version-aware
            // routing; rewriting it would silently lie about what the
            // client claimed.
        }
        let collection_name = stream.source.collection().clone();
        let mut response = stream
            .source
            .push(ctx, request)
            .await
            .map_err(server_error)?;
        if response.collection.is_none() {
            response.collection = Some(collection_name);
        }
        if !response.accepted.is_empty() {
            // BARE topic — one publish per push, regardless of how
            // many rows were accepted or returned. This preserves
            // the pre-RFC 088 §C behavior for delete-only pushes
            // (where `response.rows` may be empty even though
            // `accepted` is non-empty) and stops old clients on the
            // bare topic from receiving N redundant wakeups for a
            // multi-row push.
            if let Err(err) = sync.invalidate_stream(response.stream.as_str()).await {
                tracing::warn!(
                    target: "pocopine.log",
                    error = %err,
                    stream = response.stream.as_str(),
                    "failed to publish bare sync stream invalidation after push"
                );
            }

            // PER-PARAMS topics — batch all accepted rows, project
            // each through `row_to_params`, and publish ONCE per
            // distinct hash (multiple rows hitting the same
            // partition collapse to one wakeup). Sources that don't
            // override `row_to_params` (default impl returns empty)
            // make this a no-op via the empty-params guard inside
            // the helper. Sources that DO override route precisely
            // to the audience whose subscription params project to
            // the same hash (RFC 088 §C). Pushes that accepted but
            // returned no rows (deletes that don't echo the removed
            // row) get bare-only invalidation — that's the right
            // semantic since per-params routing needs a row to
            // project.
            // Collect into a `Vec<&Value>` rather than passing the
            // lazy `map(|r| &r.value)` iterator directly. The map
            // closure infers a single concrete lifetime for its
            // argument, which trips the route-handler's HRTB FnOnce
            // bound (axum needs `for<'r>` generality). Collecting
            // sidesteps the HRTB by handing
            // `invalidate_stream_with_rows` an already-erased
            // iterator type.
            let row_values: ::std::vec::Vec<&Value> =
                response.rows.iter().map(|r| &r.value).collect();
            if let Err(err) = sync
                .invalidate_stream_with_rows(response.stream.as_str(), row_values)
                .await
            {
                tracing::warn!(
                    target: "pocopine.log",
                    error = %err,
                    stream = response.stream.as_str(),
                    "failed to publish per-params sync stream invalidations after push"
                );
            }
        }
        Ok(response)
    }
    .await;
    Json(result)
}

async fn parse_json_request<T>(request: Request<Body>) -> ServerResult<(RequestContext, T)>
where
    T: DeserializeOwned + Send + 'static,
{
    let (parts, body) = request.into_parts();
    let ctx = RequestContext::from_parts(
        parts.method.clone(),
        parts.uri.clone(),
        parts.headers.clone(),
        parts.extensions.clone(),
    );
    let request = Request::from_parts(parts, body);
    let Json(payload) = Json::<T>::from_request(request, &())
        .await
        .map_err(|err| ServerError::BadRequest(err.to_string()))?;
    Ok((ctx, payload))
}

fn server_error(error: SyncError) -> ServerError {
    match error {
        SyncError::InvalidValue { .. } => ServerError::BadRequest(error.to_string()),
        SyncError::UnknownStream(_) => ServerError::Forbidden(error.to_string()),
        SyncError::Unsupported(_) => ServerError::BadRequest(error.to_string()),
        SyncError::Gap(_) => ServerError::BadRequest(error.to_string()),
        SyncError::SchemaMigration { .. } => ServerError::BadRequest(error.to_string()),
        SyncError::Unauthorized(msg) => ServerError::Unauthorized(msg),
        SyncError::Json(err) => {
            tracing::error!(target: "pocopine.log", error = %err, "sync json error");
            ServerError::App("sync internal error".to_string())
        }
        SyncError::Client(msg) | SyncError::Backend(msg) => {
            tracing::error!(target: "pocopine.log", error = %msg, "sync backend error");
            ServerError::App("sync internal error".to_string())
        }
        SyncError::Network(msg) => {
            // Server-side handlers don't generate Network errors —
            // that variant is for the sync-query driver classifying
            // transport failures from a `Mutator::apply_remote`
            // future. If we ever observe one here it's a bug; map
            // to a generic 500 with the message in the log.
            tracing::error!(
                target: "pocopine.log",
                error = %msg,
                "unexpected SyncError::Network surfaced from a sync request handler"
            );
            ServerError::App("sync internal error".to_string())
        }
    }
}

#[cfg(test)]
mod tests {
    use std::sync::{Arc, Mutex};

    use http_body_util::BodyExt;
    use pocopine_core::ServerError;
    use pocopine_server::auth::{
        require_auth, require_role, AuthUser, Predicate, Principal, RequestContext, Role,
    };
    use pocopine_server::axum::body::Body;
    use pocopine_server::axum::http::{Request, StatusCode};
    use pocopine_server::axum::Router;
    use serde::de::DeserializeOwned;
    use serde::Serialize;
    use serde_json::{json, Value};
    use tower::ServiceExt;

    use super::*;
    use crate::{
        ClientMutation, MemorySyncStream, MutationId, RowKey, SyncCollectionName, SyncOp,
        SyncOpenRequest, SyncPullMode, SyncPushRequest, SyncRow, SyncStreamName, SYNC_PROTOCOL_V1,
    };

    #[tokio::test]
    async fn pull_route_is_public_for_registered_streams() {
        let router = router_with_posts_stream();

        let request = SyncPullRequest::new(SyncStreamName::new("posts_for_tenant").unwrap());
        let outer: ServerResult<SyncPullResponse<String>> =
            post_json(router, SYNC_PULL_PATH, &request, None).await;
        let response = outer.unwrap();
        assert_eq!(response.protocol, SYNC_PROTOCOL_V1);
        assert_eq!(response.mode, SyncPullMode::Snapshot);
        let mut expected = SyncRow::new("post_1", "hello".to_string()).unwrap();
        expected.version = Some(crate::RowVersion::new("v1").unwrap());
        assert_eq!(response.rows, vec![expected]);
    }

    #[tokio::test]
    async fn pull_unknown_stream_returns_forbidden() {
        let router = router_with_posts_stream();

        let request = SyncPullRequest::new(SyncStreamName::new("unknown_stream").unwrap());
        let outer: ServerResult<SyncPullResponse<String>> =
            post_json(router, SYNC_PULL_PATH, &request, None).await;
        assert!(matches!(
            outer,
            Err(ServerError::Forbidden(message)) if message.contains("unknown sync stream")
        ));
    }

    #[tokio::test]
    async fn push_route_applies_memory_mutation_for_registered_streams() {
        let router = router_with_posts_stream();

        let request = SyncPushRequest::new(
            SyncStreamName::new("posts_for_tenant").unwrap(),
            [ClientMutation {
                id: MutationId::new("device_1:1").unwrap(),
                key: Some(RowKey::new("post_2").unwrap()),
                op: SyncOp::Upsert,
                base_version: None,
                payload: "from push".to_string(),
                migration_outcome: None,
            }],
        );
        let outer: ServerResult<SyncPushResponse<String>> =
            post_json(router, SYNC_PUSH_PATH, &request, None).await;
        let response = outer.unwrap();
        assert_eq!(response.accepted.len(), 1);
        assert!(response.rejected.is_empty());
        assert!(response.conflicts.is_empty());
        assert_eq!(response.rows[0].key.as_str(), "post_2");
        assert_eq!(response.rows[0].value, "from push");
    }

    #[tokio::test]
    async fn guarded_stream_denies_anonymous_open_and_pull() {
        let router = router_with_guarded_posts_stream(require_auth());

        let open = SyncOpenRequest::new([SyncStreamName::new("posts_for_tenant").unwrap()]);
        let opened: ServerResult<SyncOpenResponse> =
            post_json(router.clone(), SYNC_OPEN_PATH, &open, None).await;
        assert!(matches!(opened, Err(ServerError::Unauthorized(_))));

        let pull = SyncPullRequest::new(SyncStreamName::new("posts_for_tenant").unwrap());
        let pulled: ServerResult<SyncPullResponse<String>> =
            post_json(router, SYNC_PULL_PATH, &pull, None).await;
        assert!(matches!(pulled, Err(ServerError::Unauthorized(_))));
    }

    #[tokio::test]
    async fn guarded_stream_allows_authenticated_principal() {
        let router = router_with_guarded_posts_stream(require_auth());
        let principal = Principal::from_user(AuthUser::new("user_1"));

        let pull = SyncPullRequest::new(SyncStreamName::new("posts_for_tenant").unwrap());
        let pulled: ServerResult<SyncPullResponse<String>> =
            post_json(router, SYNC_PULL_PATH, &pull, Some(principal)).await;

        assert!(pulled.is_ok());
    }

    #[tokio::test]
    async fn role_guard_checks_authenticated_principal_roles() {
        let router = router_with_guarded_posts_stream(require_role("admin"));
        let viewer = Principal::from_user(AuthUser::new("viewer").with_role(Role::user()));
        let admin = Principal::from_user(AuthUser::new("admin").with_role(Role::admin()));
        let pull = SyncPullRequest::new(SyncStreamName::new("posts_for_tenant").unwrap());

        let denied: ServerResult<SyncPullResponse<String>> =
            post_json(router.clone(), SYNC_PULL_PATH, &pull, Some(viewer)).await;
        assert!(matches!(denied, Err(ServerError::Forbidden(_))));

        let allowed: ServerResult<SyncPullResponse<String>> =
            post_json(router, SYNC_PULL_PATH, &pull, Some(admin)).await;
        assert!(allowed.is_ok());
    }

    #[tokio::test]
    async fn source_receives_request_context_after_guard_passes() {
        let seen = Arc::new(Mutex::new(Vec::new()));
        let sync = SyncServer::builder()
            .public_stream(ContextCaptureStream::new(seen.clone()))
            .build();
        let router = finalize(sync);
        let principal = Principal::from_user(AuthUser::new("ctx_user"));
        let pull = SyncPullRequest::new(SyncStreamName::new("context_stream").unwrap());

        let pulled: ServerResult<SyncPullResponse<String>> =
            post_json(router, SYNC_PULL_PATH, &pull, Some(principal)).await;

        assert!(pulled.is_ok());
        assert_eq!(seen.lock().unwrap().as_slice(), &["ctx_user".to_string()]);
    }

    #[tokio::test]
    async fn guarded_stream_denies_push_before_default_unsupported() {
        let router = router_with_guarded_posts_stream(require_auth());
        let request = SyncPushRequest::<String> {
            protocol: SYNC_PROTOCOL_V1.to_string(),
            stream: SyncStreamName::new("posts_for_tenant").unwrap(),
            params: ::std::collections::BTreeMap::new(),
            schema_version: crate::default_schema_version_one(),
            mutations: Vec::new(),
        };

        let pushed: ServerResult<SyncPushResponse<String>> =
            post_json(router, SYNC_PUSH_PATH, &request, None).await;

        assert!(matches!(pushed, Err(ServerError::Unauthorized(_))));
    }

    #[test]
    fn server_error_hides_internal_details() {
        assert!(matches!(
            server_error(SyncError::backend("lock poisoned with internal detail")),
            ServerError::App(message) if message == "sync internal error"
        ));

        let json_err = serde_json::from_str::<serde_json::Value>("not-json").unwrap_err();
        assert!(matches!(
            server_error(SyncError::Json(json_err)),
            ServerError::App(message) if message == "sync internal error"
        ));
    }

    #[test]
    fn schema_migration_error_maps_to_bad_request() {
        let err = server_error(SyncError::schema_migration("posts", 1, 2));
        match err {
            ServerError::BadRequest(msg) => {
                assert!(msg.contains("posts"), "unexpected message: {msg}");
                assert!(msg.contains("v1"), "missing from-version: {msg}");
                assert!(msg.contains("v2"), "missing to-version: {msg}");
            }
            other => panic!("expected BadRequest, got: {other:?}"),
        }
    }

    #[tokio::test]
    async fn open_response_includes_schema_version_from_source() {
        // Default MemorySyncStream returns schema_version = 1 via the
        // trait default. The wire response should carry that explicitly.
        let router = router_with_posts_stream();
        let open = SyncOpenRequest::new([SyncStreamName::new("posts_for_tenant").unwrap()]);
        let opened: SyncOpenResponse = post_json(router, SYNC_OPEN_PATH, &open, None)
            .await
            .unwrap();
        assert_eq!(opened.streams.len(), 1);
        assert_eq!(opened.streams[0].schema_version, 1);
    }

    #[test]
    fn open_response_without_schema_version_field_deserializes_as_one() {
        // Backwards-compat: an old server response that omits the field
        // must round-trip through serde with schema_version = 1. Use a
        // literal JSON string (not the `json!{}` macro) so the test
        // exercises the actual wire-deserialization path.
        let payload = format!(
            r#"{{"protocol":"{SYNC_PROTOCOL_V1}","streams":[{{"stream":"posts_for_tenant","collection":"posts","cursor":null}}]}}"#
        );
        let response: SyncOpenResponse = serde_json::from_str(&payload).unwrap();
        assert_eq!(response.streams[0].schema_version, 1);
    }

    fn router_with_posts_stream() -> pocopine_server::axum::Router {
        let posts = MemorySyncStream::<String>::new("posts_for_tenant", "posts").unwrap();
        posts.upsert("post_1", "hello".to_string()).unwrap();
        let sync = SyncServer::builder().public_stream(posts).build();
        finalize(sync)
    }

    // ---- RFC 088 §C: invalidate_stream_with_row dual publish -------

    /// Test source: overrides `row_to_params` to project
    /// `workspace_id` into the params map so we can assert the
    /// per-params topic is published.
    struct ParamsRoutedStream {
        name: SyncStreamName,
        collection: SyncCollectionName,
    }
    impl ParamsRoutedStream {
        fn new() -> Self {
            Self {
                name: SyncStreamName::new("issues").unwrap(),
                collection: SyncCollectionName::new("issues").unwrap(),
            }
        }
    }
    impl SyncStreamSource for ParamsRoutedStream {
        fn stream(&self) -> &SyncStreamName {
            &self.name
        }
        fn collection(&self) -> &SyncCollectionName {
            &self.collection
        }
        fn pull(
            &self,
            _ctx: RequestContext,
            _request: SyncPullRequest,
        ) -> SyncBoxFuture<'_, SyncPullResponse<Value>> {
            Box::pin(async move { Err(SyncError::Unsupported("test stream".into())) })
        }
        fn push(
            &self,
            _ctx: RequestContext,
            _request: SyncPushRequest<Value>,
        ) -> SyncBoxFuture<'_, SyncPushResponse<Value>> {
            Box::pin(async move { Err(SyncError::Unsupported("test stream".into())) })
        }
        fn row_to_params(&self, row: &Value) -> SyncResult<crate::StreamParams> {
            let mut params = crate::StreamParams::new();
            if let Some(ws) = row.get("workspace_id") {
                params.insert("workspace_id".into(), ws.clone());
            }
            Ok(params)
        }
    }

    #[tokio::test]
    async fn invalidate_stream_with_row_publishes_per_params_only() {
        // Post-codex-review (P2.2): `invalidate_stream_with_row` no
        // longer emits the bare-topic publish. The caller (the
        // `/push` handler) issues a SINGLE bare publish per push
        // and lets this helper publish only the per-params topic
        // per row.
        use pocopine_events::{MemoryEventBackend, ReplayRequest};
        use std::sync::Arc;

        let backend: SharedEventBackend = Arc::new(MemoryEventBackend::new());
        let sync = SyncServer::builder()
            .public_stream(ParamsRoutedStream::new())
            .events(backend.clone())
            .build();

        let row = json!({"id": "i1", "workspace_id": "W1"});
        sync.invalidate_stream_with_row("issues", &row)
            .await
            .unwrap();

        let bare_tag = sync_stream_tag("issues");
        let mut expected_params = crate::StreamParams::new();
        expected_params.insert("workspace_id".into(), json!("W1"));
        let hash = crate::stream_params_hash("issues", &expected_params);
        let params_tag = crate::sync_stream_params_tag("issues", hash);
        let bare_topic = pocopine_live::query_tag_topic(&bare_tag).unwrap();
        let params_topic = pocopine_live::query_tag_topic(&params_tag).unwrap();

        let replay = backend
            .replay(ReplayRequest::new(vec![
                bare_topic.clone(),
                params_topic.clone(),
            ]))
            .await
            .unwrap();
        let bare_count = replay
            .events
            .iter()
            .filter(|e| e.topic == bare_topic)
            .count();
        let params_count = replay
            .events
            .iter()
            .filter(|e| e.topic == params_topic)
            .count();
        assert_eq!(bare_count, 0, "no bare publish (caller's responsibility)");
        assert_eq!(params_count, 1, "exactly one per-params publish");
    }

    /// When `row_to_params` returns empty params (the default impl,
    /// or a source that opts out), the per-params publish is a
    /// no-op — and since the bare publish is now the caller's
    /// responsibility, this test verifies the helper emits NO
    /// events at all in that case.
    struct DefaultRoutedStream {
        name: SyncStreamName,
        collection: SyncCollectionName,
    }
    impl DefaultRoutedStream {
        fn new() -> Self {
            Self {
                name: SyncStreamName::new("comments").unwrap(),
                collection: SyncCollectionName::new("comments").unwrap(),
            }
        }
    }
    impl SyncStreamSource for DefaultRoutedStream {
        fn stream(&self) -> &SyncStreamName {
            &self.name
        }
        fn collection(&self) -> &SyncCollectionName {
            &self.collection
        }
        fn pull(
            &self,
            _ctx: RequestContext,
            _request: SyncPullRequest,
        ) -> SyncBoxFuture<'_, SyncPullResponse<Value>> {
            Box::pin(async move { Err(SyncError::Unsupported("test stream".into())) })
        }
        fn push(
            &self,
            _ctx: RequestContext,
            _request: SyncPushRequest<Value>,
        ) -> SyncBoxFuture<'_, SyncPushResponse<Value>> {
            Box::pin(async move { Err(SyncError::Unsupported("test stream".into())) })
        }
        // No override of row_to_params → trait default → empty params.
    }

    #[tokio::test]
    async fn invalidate_stream_with_row_skips_per_params_when_empty() {
        use pocopine_events::{MemoryEventBackend, ReplayRequest};
        use std::sync::Arc;

        let backend: SharedEventBackend = Arc::new(MemoryEventBackend::new());
        let sync = SyncServer::builder()
            .public_stream(DefaultRoutedStream::new())
            .events(backend.clone())
            .build();

        let row = json!({"id": "c1"});
        sync.invalidate_stream_with_row("comments", &row)
            .await
            .unwrap();

        let bare_tag = sync_stream_tag("comments");
        let bare_topic = pocopine_live::query_tag_topic(&bare_tag).unwrap();
        let replay = backend
            .replay(ReplayRequest::new(vec![bare_topic.clone()]))
            .await
            .unwrap();
        // No events: the helper publishes per-params only, and
        // row_to_params returned empty so the per-params publish
        // was skipped. The bare invalidation is the `/push`
        // handler's responsibility (a separate code path), so this
        // direct invocation produces zero events.
        assert_eq!(replay.events.len(), 0);
    }

    fn router_with_guarded_posts_stream<P>(predicate: P) -> Router
    where
        P: Predicate,
    {
        let posts = MemorySyncStream::<String>::new("posts_for_tenant", "posts").unwrap();
        posts.upsert("post_1", "hello".to_string()).unwrap();
        let sync = SyncServer::builder()
            .guarded_stream(posts, predicate)
            .build();
        finalize(sync)
    }

    fn finalize(sync: SyncServer) -> Router {
        pocopine_server::__reset_for_test();
        pocopine_server::Server::new(pocopine_server::axum::Router::new())
            .plugin(sync_server_plugin(sync))
            .try_finalize()
            .unwrap()
    }

    async fn post_json<T, R>(
        router: Router,
        uri: &str,
        payload: &T,
        principal: Option<Principal>,
    ) -> ServerResult<R>
    where
        T: Serialize,
        R: DeserializeOwned,
    {
        let response = router
            .oneshot(sync_request(uri, payload, principal))
            .await
            .unwrap();

        assert_eq!(response.status(), StatusCode::OK);
        let bytes = response.into_body().collect().await.unwrap().to_bytes();
        serde_json::from_slice(&bytes).unwrap()
    }

    fn sync_request<T>(uri: &str, payload: &T, principal: Option<Principal>) -> Request<Body>
    where
        T: Serialize,
    {
        let mut builder = Request::builder()
            .method("POST")
            .uri(uri)
            .header("content-type", "application/json");
        if let Some(principal) = principal {
            builder = builder.extension(principal);
        }
        builder
            .body(Body::from(serde_json::to_string(payload).unwrap()))
            .unwrap()
    }

    struct ContextCaptureStream {
        stream: SyncStreamName,
        collection: SyncCollectionName,
        seen: Arc<Mutex<Vec<String>>>,
    }

    impl ContextCaptureStream {
        fn new(seen: Arc<Mutex<Vec<String>>>) -> Self {
            Self {
                stream: SyncStreamName::new("context_stream").unwrap(),
                collection: SyncCollectionName::new("context").unwrap(),
                seen,
            }
        }
    }

    impl SyncStreamSource for ContextCaptureStream {
        fn stream(&self) -> &SyncStreamName {
            &self.stream
        }

        fn collection(&self) -> &SyncCollectionName {
            &self.collection
        }

        fn pull<'a>(
            &'a self,
            ctx: RequestContext,
            request: SyncPullRequest,
        ) -> SyncBoxFuture<'a, SyncPullResponse<Value>> {
            let _ = request;
            let user_id = ctx
                .user
                .user()
                .map(|user| user.id.clone())
                .unwrap_or_else(|| "anonymous".to_string());
            self.seen.lock().unwrap().push(user_id.clone());
            Box::pin(async move {
                Ok(SyncPullResponse::snapshot(
                    SyncStreamName::new("context_stream").unwrap(),
                    SyncCollectionName::new("context").unwrap(),
                    vec![SyncRow::new("ctx", json!(user_id))?],
                    None,
                ))
            })
        }
    }
}
