[package]
name = "website"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pine = { path = "../../crates/pine" }
pine-icons = { path = "../../crates/pine-icons" }
pocopine = { path = "../../crates/pocopine" }
wasm-bindgen = { workspace = true }
serde = { workspace = true }
web-sys = { version = "0.3", features = ["Performance", "Window"] }
