#!/bin/sh
# pocopine CLI installer — https://pocopine.dev/install.sh
#
# A thin wrapper that downloads and runs the latest prebuilt-binary
# installer (generated by cargo-dist for each GitHub release). Using the
# `releases/latest` URL means this short link always installs the newest
# pocopine CLI without re-hosting a versioned script here.
#
#   curl -fsSL https://pocopine.dev/install.sh | sh
set -e
curl --proto '=https' --tlsv1.2 -LsSf \
  https://github.com/mambisi/pocopine/releases/latest/download/pocopine-cli-installer.sh | sh
