#!/usr/bin/env python3
"""Generate RFC-120 cardinal predicates from the pinned Unicode CLDR JSON.

No runtime CLDR parser, network, or ICU dependency. Reject unrecognized grammar
so a CLDR update cannot silently emit an incomplete predicate.
"""

import argparse
import json
from pathlib import Path
import re
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
CRATE = ROOT / "crates/pocopine-locale"
CATEGORIES = ("zero", "one", "two", "few", "many")


def relation(text):
    match = re.fullmatch(r"([nivwftce])(?: % ([1-9][0-9]*))? (!=|=) ([0-9.,]+)", text)
    if match is None:
        raise ValueError(f"Unsupported CLDR relation: {text!r}")
    operand, modulo, operator, values = match.groups()
    if operand in ("c", "e"):
        bounds = [tuple(map(int, value.split(".."))) for value in values.split(",")]
        contains_zero = any(bound[0] <= 0 <= bound[-1] for bound in bounds)
        return str(contains_zero == (operator == "=")).lower()
    # Our MF1 subset has no compact/scientific number formatting. c/e = 0.
    operands = {"n": "a.i", "i": "a.i", "v": "u64::from(a.v)",
                "f": "a.f", "t": "a.t()", "e": "0u64", "c": "0u64"}
    if operand not in operands:
        raise ValueError(f"New operand needs an exact implementation: {operand}")
    expression = operands[operand]
    if modulo:
        expression = f"({expression} % {modulo})"
    conditions = []
    for value in values.split(","):
        if ".." in value:
            lo, hi = map(int, value.split(".."))
            if lo > hi:
                raise ValueError(text)
            conditions.append(f"({lo}..={hi}).contains(&{expression})")
        else:
            conditions.append(f"{expression} == {int(value)}")
    result = "(" + " || ".join(conditions) + ")"
    # CLDR '='/'!=' are integer-membership relations. A nonzero fraction
    # cannot equal an integer/range, even after a modulo operation.
    if operand == "n":
        result = f"(a.f == 0 && {result})"
    if operator == "!=":
        result = f"!{result}"
    return result


def condition(text):
    arms = []
    for arm in text.split(" or "):
        parts = [relation(x) for x in arm.split(" and ")]
        if "false" in parts:
            continue
        parts = [part for part in parts if part != "true"]
        if not parts:
            return "true"
        arms.append("(" + " && ".join(parts) + ")")
    return " || ".join(arms) or "false"


def generate():
    data = json.loads((CRATE / "data/cldr/plurals.json").read_text())["supplemental"]["plurals-type-cardinal"]
    parent_data = json.loads((CRATE / "data/cldr/parentLocales.json").read_text())["supplemental"]["parentLocales"]
    if parent_data.get("plurals") != {}:
        raise ValueError("CLDR plural parent overrides changed; update CardinalRule::for_locale")
    parents = parent_data["parentLocale"]
    sets = {}
    locales = {}
    for locale, rules in sorted(data.items()):
        signature = tuple((cat, rules[f"pluralRule-count-{cat}"].split("@")[0].strip())
                          for cat in CATEGORIES if f"pluralRule-count-{cat}" in rules)
        if signature not in sets:
            sets[signature] = len(sets)
        locales[locale] = sets[signature]
    lines = ["// @generated by tools/gen-locale-cldr.py; DO NOT EDIT.",
             "// Source/license: ../data/cldr/README.md. Exact decimal predicates, no float rounding.",
             "// Preserve CLDR relation grouping and modulo syntax for review against source.",
             "#![allow(unused_parens, clippy::nonminimal_bool, clippy::manual_is_multiple_of)]",
             "use crate::{PluralArg, PluralCategory};",
             f"pub(crate) const OTHER_RULE: u8 = {sets[()]};",
             "pub(crate) fn category(rule: u8, a: PluralArg) -> PluralCategory {", "match rule {"]
    for signature, index in sets.items():
        lines.append(f"{index} => {{")
        for category, rule in signature:
            lines.append(f"if {condition(rule)} {{ return PluralCategory::{category.title()}; }}")
        lines.append("PluralCategory::Other },")
    lines.extend(["_ => PluralCategory::Other,", "}}", "pub(crate) fn rule_for_tag(tag: &str) -> Option<u8> {", "match tag {"])
    for index in sets.values():
        names = " | ".join(json.dumps(tag) for tag, rule in locales.items() if rule == index)
        lines.append(f"{names} => Some({index}),")
    lines.extend(["_ => None,", "}}", "pub(crate) fn parent(tag: &str) -> Option<&'static str> {", "match tag {"])
    for parent in sorted(set(parents.values())):
        children = " | ".join(json.dumps(tag) for tag in sorted(parents) if parents[tag] == parent)
        lines.append(f"{children} => Some({json.dumps(parent)}),")
    lines.extend(["_ => None,", "}}", ""])
    # Use the workspace formatter so regeneration is also a formatting fixed point.
    with tempfile.TemporaryDirectory(prefix="pocopine-cldr-") as directory:
        path = Path(directory) / "generated.rs"
        path.write_text("\n".join(lines))
        subprocess.run(["rustfmt", "--edition", "2024", str(path)], check=True)
        return path.read_text()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = CRATE / "src/generated.rs"
    generated = generate()
    if args.check:
        if not output.exists() or output.read_text() != generated:
            raise SystemExit("CLDR generated code has drifted; run python3 tools/gen-locale-cldr.py")
        print("CLDR generated code matches the vendored snapshot")
    else:
        output.write_text(generated)
        print(f"Generated {output}")
