[package]
name = "richtext"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pine-richtext = { path = "../../crates/pine-richtext", features = ["view"] }
pocopine = { path = "../../crates/pocopine" }
serde = { workspace = true }
serde_json = { workspace = true }
wasm-bindgen = { workspace = true }
web-sys = { version = "0.3", features = [
    "Document",
    "DomRect",
    "HtmlTextAreaElement",
    "Window",
] }
